src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <inlineHelpText>End date for this term.</inlineHelpText>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <inlineHelpText>Start date for this term.</inlineHelpText>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Program_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in. Used to build the Opportunity Key for the Interaction Processor to determine whether to create a new Opportunity or update an existing Opportunity.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age displayed is as of interaction create date.  The age does not update over time.</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>High_School_Graduation_Year__c</fullName>
        <description>The year a student will graduate high school. Populated from RFI forms. Zapier does a lookup to find a term, but this is for reference if it doesn&apos;t find one.</description>
        <label>High School Graduation Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Search_Text__c</fullName>
        <description>Used by the TDTM_Term_Program_Lookup to find a Program. Value should match the Program_Name_on_Application__c field on the Program__c object (not Account).</description>
        <label>Program Search Text</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>The School in which the student is interested</description>
        <inlineHelpText>The School in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Search_Text__c</fullName>
        <description>Used by the TDTM_Term_Program_Lookup to find a term. Value should be like &quot;Fall 2019&quot; or &quot;Spring 2020&quot;. CAS Interactions will use the Graduation Year field instead of this one.</description>
        <label>Term Search Text</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name_on_Application__c</fullName>
        <inlineHelpText>Name of the program to display on the application</inlineHelpText>
        <label>Program Name on Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year_List.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <description>Year list used for picking High School Graduation Year</description>
    <masterLabel>Year List</masterLabel>
</GlobalValueSet>

src/classes/Test_TDTM_Term_Program_Lookup.cls
/**
 * Created by ejc84332 on 2019-03-07.
 */

@IsTest
private class Test_TDTM_Term_Program_Lookup {


    @IsTest
    static void test_undergrad() {


        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Term_Program_Lookup', 'Interaction__c', 'BeforeInsert;BeforeUpdate', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);


        Test.startTest();
        BethelTestDataFactory.createTerms(2);

        // create a term with start and end date on either side of today to test the date lookup
        Academic_Term__c date_term = new Academic_Term__c(Name='TERM BY DATE - CAPS/GS', Term_Start_Date__c=System.today()-1, Term_End_Date__c=System.today()+1);
        insert date_term;

        BethelTestDataFactory.createPrograms();


        // create undergrad Interaction with age instead of grad year, and no program to test for Undecided Program.
        Interaction__c i_cas = new Interaction__c(First_Name__c='First1', Last_Name__c='Last1', Email__c='test1@test.com', Age__c=20, School_College__c='Undergraduate');

        try{
            insert i_cas;
        }catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Age cannot be over 18') ? true : false;
            System.assert(expectedExceptionThrown, true);
        }
	
        i_cas.Age__c=16;
        insert i_cas;
        i_cas = [SELECT Id, First_Name__c, Last_Name__c, Email__c, School_College__c, Academic_Term__c, Academic_Program__c,
                Academic_Program__r.Program_Name_on_Application__c, Age__c, High_School_Graduation_Year__c FROM Interaction__c WHERE Id=:i_cas.Id];

        System.assert(i_cas.High_School_Graduation_Year__c != null);

        if(System.today().month()<=8){
            System.assert(i_cas.High_School_Graduation_Year__c == String.valueOf(System.today().year()+(17-16)));
        }else{
            System.assert(i_cas.High_School_Graduation_Year__c == String.valueOf(System.today().year()+(18-16)));
        }

        System.assert(i_cas.Academic_Program__r.Program_Name_on_Application__c == 'Undecided');

        // Test a CAS with Term Search Text instead of age
        String term_search = 'Fall ' + String.valueOf(System.today().year());
        i_cas = new Interaction__c(First_Name__c='First1', Last_Name__c='Last1', Email__c='test1@test.com', Term_Search_Text__c=term_search, School_College__c='Undergraduate');
		insert i_cas;
        i_cas = [SELECT Id, First_Name__c, Last_Name__c, Email__c, School_College__c, Academic_Term__c, Academic_Program__c,
                 Academic_Program__r.Program_Name_on_Application__c, Age__c, High_School_Graduation_Year__c FROM Interaction__c WHERE Id=:i_cas.Id];
        System.assert(i_cas.Academic_Term__c != null);
        
        // Test a CAPS/GS and SEM using Program and Term search text.


        String term_search_prefix = 'Fall ' + String.valueOf(System.today().year());
        Interaction__c i_capsgs = new Interaction__c(First_Name__c='First2', Last_Name__c='Last2', Email__c='test2@test.com',
                School_College__c='Graduate', Term_Search_Text__c=term_search_prefix, Program_Search_Text__c='Strategic Leadership (M.A.)');

        Interaction__c i_sem = new Interaction__c(First_Name__c='First3', Last_Name__c='Last3', Email__c='test3@test.com',
                School_College__c='Seminary', Term_Search_Text__c=term_search_prefix, Program_Search_Text__c='Theological Studies Certificate');

        // test capsgs without term or term search text.
        Interaction__c i_capsgs_no_term = new Interaction__c(First_Name__c='First2', Last_Name__c='Last2', Email__c='test2@test.com',
                School_College__c='Graduate', Program_Search_Text__c='Strategic Leadership (M.A.)');

        insert i_capsgs;
        insert i_sem;
        insert i_capsgs_no_term;

        i_capsgs = [SELECT Id, First_Name__c, Last_Name__c, Email__c, School_College__c, Academic_Term__c, Academic_Term__r.Name, Academic_Program__c,
                Academic_Program__r.Program_Name_on_Application__c, Term_Search_Text__c, Program_Search_Text__c FROM Interaction__c WHERE Id=:i_capsgs.Id];

        i_sem = [SELECT Id, First_Name__c, Last_Name__c, Email__c, School_College__c, Academic_Term__c, Academic_Term__r.Name, Academic_Program__c,
                Academic_Program__r.Program_Name_on_Application__c, Term_Search_Text__c, Program_Search_Text__c FROM Interaction__c WHERE Id=:i_sem.Id];

        i_capsgs_no_term = [SELECT Id, First_Name__c, Last_Name__c, Email__c, School_College__c, Academic_Term__c, Academic_Term__r.Name, Academic_Program__c,
                Academic_Program__r.Program_Name_on_Application__c, Term_Search_Text__c, Program_Search_Text__c FROM Interaction__c WHERE Id=:i_capsgs_no_term.Id];

        System.assert(i_capsgs.Academic_Program__r.Program_Name_on_Application__c == 'Strategic Leadership (M.A.)');
        System.assert(i_sem.Academic_Program__r.Program_Name_on_Application__c == 'Theological Studies Certificate');

        System.assert(i_capsgs.Academic_Term__r.Name == term_search_prefix + ' - CAPS/GS');
        System.assert(i_sem.Academic_Term__r.Name == term_search_prefix + ' - SEM');
        System.assert(i_capsgs_no_term.Academic_Term__r.Name == date_term.Name);

    }
}