src/objects/Academic_Interest_Mapping__c.object
<CustomObject>
    <description>Mapping object that translates generic Interests (such as on an RFI when a student says they are interested in &quot;math&quot;) into the actual Program Account.</description>
    <fields>
        <fullName>Academic_Interest__c</fullName>
        <label>Academic Interest</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <filterItems>
                <field>Program__c.School_College__c</field>
                <operation>equals</operation>
                <value>Undergraduate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Academic Interest Mappings</relationshipLabel>
        <relationshipName>Academic_Interest_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Interest Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Academic Interest Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academic Interest Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Program_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Academic_Interests__c</fullName>
        <description>A coma separated list of Academic Interests, from RFI Forms, Tell Me More cards, etc.</description>
        <label>All Academic Interests</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Status__c</fullName>
        <description>When set to &quot;New,&quot; the Interaction Processor runs, then updates the Status based on the result to &quot;Imported&quot; or &quot;Audit Needed.&quot;</description>
        <inlineHelpText>Set the Status to &quot;New&quot; and save to kick off the Interaction process.</inlineHelpText>
        <label>Interaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Audit Required</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <inlineHelpText>Required to create or update an Opportunity.</inlineHelpText>
        <label>Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inquired</fullName>
                    <default>true</default>
                    <label>Inquired</label>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Wait Listed</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>File Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>The School in which the student is interested</description>
        <inlineHelpText>The School in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Secondary Academic Program)</relationshipLabel>
        <relationshipName>InteractionsSecondary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Academic_Interest_Handler.cls
global class TDTM_Academic_Interest_Handler extends TDTMVirtualTriggerHandler {


    global override void onBeforeInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        process(newList);
        
    }

    global override void onBeforeUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        process(newList);
    }

    private Boolean valid_interaction(Interaction__c interaction){

        if(interaction.Interaction_Status__c != 'New'){
            System.debug('Interaction not being processed, skipping');
            return false;
        }

        if(interaction.Opportunity_Stage__c != 'Inquired'){
            System.debug('Opportunity Stage is not Inquired');
            System.debug('Got Opportunity Stage ' + interaction.Opportunity_Stage__c);
            return false;
        }

        // don't process if not Undergrad interaction
        if (interaction.School_College__c == null || interaction.School_College__c == ''){
            System.debug('School / College is blank, skipping');
            return false;
        }

        if (String.isBlank(interaction.All_Academic_Interests__c)){
            System.debug('No data for All Intended Programs');
            return false;
        }

        return true;
    }

    private void process(List<SObject> newList){

        Set<String> lookup_keys = new Set<String>();

        Interaction__c[] interactions_to_process = new List<Interaction__c>();

        for(SObject o : newList) {
            Interaction__c interaction = (Interaction__c) o;

            // check if interaction should be processed
            if(!valid_interaction(interaction)){
                continue;
            }

            interaction.All_Academic_Interests__c = interaction.All_Academic_Interests__c.toLowerCase();

            // populate Intended_Program__c and Secondary_Intended_Program__c from All_Academic_Interests__c
            String[] all_academic_interests = interaction.All_Academic_Interests__c.split(',');

            // there is some data in all_academic_interests so we know we can at least one
            String first_academic_interest = all_academic_interests.get(0).trim();
            String interest_key = first_academic_interest+'---'+interaction.School_College__c;
            lookup_keys.add(interest_key.toLowerCase());


            String second_academic_interest;
            if(all_academic_interests.size() > 1){
                second_academic_interest = all_academic_interests.get(1).trim();
                String second_interest_key = second_academic_interest+'---'+interaction.School_College__c;
                lookup_keys.add(second_interest_key.toLowerCase());
            }else{
                second_academic_interest = null;
            }

            // add to the list to process after SOQL query
            interactions_to_process.add(interaction);

        }

        System.debug('----------------KEYS----------------');
        System.debug(lookup_keys);
        System.debug('------------------------------------');

        // do SOQL queries for the records we need.
        Academic_Interest_Mapping__c[] academic_interests = [SELECT Program__c, Academic_Interest__c, School_College__c, Mapping_Key__c FROM Academic_Interest_Mapping__c WHERE Mapping_Key__c = :lookup_keys];

        Map<String, Id> interest_to_program_map = new Map<String, Id>();
        for( Academic_Interest_Mapping__c m : academic_interests){
            interest_to_program_map.put(m.Mapping_Key__c, m.Program__c);
        }

        System.debug('----------------MAP----------------');
        System.debug(interest_to_program_map);
        System.debug('------------------------------------');


        for(Interaction__c interaction : interactions_to_process){

            //todo:  this is repeated code
            interaction.All_Academic_Interests__c = interaction.All_Academic_Interests__c.toLowerCase();
            String school = interaction.School_College__c.toLowerCase();

            // populate Intended_Program__c and Secondary_Intended_Program__c from All_Academic_Interests__c
            String[] all_academic_interests = interaction.All_Academic_Interests__c.split(',');

            String first_academic_interest = all_academic_interests.get(0).trim();
            String second_academic_interest;
            if(all_academic_interests.size() > 1){
                second_academic_interest = all_academic_interests.get(1).trim();
            }else{
                second_academic_interest = null;
            }

            String first_mapping_key =  first_academic_interest+'---'+school;
            interaction.Academic_Program__c = interest_to_program_map.get(first_mapping_key);
            if(second_academic_interest != null){
                String second_mapping_key =  second_academic_interest+'---'+school;
                interaction.Secondary_Academic_Program__c = interest_to_program_map.get(second_mapping_key);
            }
        }   

    }
}