src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Intended_Term_of_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Term of Entry</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Key__c</fullName>
        <description>A unique external ID text field which determines whether an Interaction will create a new Opportunity or edit an existing Opportunity. Built using the Contact’s 18-digit ID, Career, Term’s 15-digit ID, and Recruitment/Academic Program’s 15-digit ID (if applicable) to ensure uniqueness and support of both a central and decentral recruitment process. Set by the Interactions Processor.</description>
        <externalId>true</externalId>
        <label>Opportunity Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdrawal_Reason__c</fullName>
        <description>Reason for not coming to Bethel; Data goes into Banner</description>
        <inlineHelpText>Reason for not coming to Bethel</inlineHelpText>
        <label>Withdrawal Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AN - Academic Fit</fullName>
                </value>
                <value>
                    <fullName>RA - Readmit</fullName>
                </value>
                <value>
                    <fullName>AT - Athletics</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Contact Info</fullName>
                </value>
                <value>
                    <fullName>BV - Bad Experience</fullName>
                </value>
                <value>
                    <fullName>CO - Community Fit</fullName>
                </value>
                <value>
                    <fullName>DR - Do Not Recruit</fullName>
                </value>
                <value>
                    <fullName>FA - Financial Aid</fullName>
                </value>
                <value>
                    <fullName>NA - App Not Complete</fullName>
                </value>
                <value>
                    <fullName>NR - No Response</fullName>
                </value>
                <value>
                    <fullName>PR - Personal</fullName>
                </value>
                <value>
                    <fullName>QD - Not Qualified</fullName>
                </value>
                <value>
                    <fullName>SC - STAR contact:not interested</fullName>
                </value>
                <value>
                    <fullName>ST - Switching Term/Prog</fullName>
                </value>
                <value>
                    <fullName>TC - Too close to home</fullName>
                </value>
                <value>
                    <fullName>TF - Too far from home</fullName>
                </value>
                <value>
                    <fullName>TU - High Tuition</fullName>
                </value>
                <value>
                    <fullName>UN - Unknown</fullName>
                </value>
                <value>
                    <fullName>WA - Wrong School/Catalog</fullName>
                </value>
                <value>
                    <fullName>WB - Wrong Bethel</fullName>
                </value>
                <value>
                    <fullName>WL - Waitlist/Not Selected</fullName>
                </value>
                <value>
                    <fullName>TL - Will transfer in later</fullName>
                </value>
                <value>
                    <fullName>SF - Switching to Future Term</fullName>
                </value>
                <value>
                    <fullName>BF - Better fit elsewhere</fullName>
                </value>
                <value>
                    <fullName>CH - Change of Plans</fullName>
                </value>
                <value>
                    <fullName>DF - Deferred to new term</fullName>
                </value>
                <value>
                    <fullName>WY - Wrong grad year</fullName>
                </value>
                <value>
                    <fullName>AC - Acad Dept Contact:not interest</fullName>
                </value>
                <value>
                    <fullName>AR - Admit record created</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Address</fullName>
                </value>
                <value>
                    <fullName>ST - Switching Terms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/OpportunityCloneController.cls
public with sharing class OpportunityCloneController {

    @AuraEnabled
    public static Opportunity cloneOpportunity(Id oppId) {
        Opportunity newOpp = null;
        try {
            Map<String, Schema.SObjectField> fieldMap = Opportunity.sObjectType.getDescribe().fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            List<Opportunity> opps = Database.query('SELECT ' + String.join(fieldNames, ',') + ' FROM Opportunity WHERE Id = :oppId');
            if (!opps.isEmpty()) {
                newOpp = opps[0].clone();

                // If we are cloning an enrolled app and the school is CAS, leave it at enrolled.
                // It is a PSEO app that we are cloning forward so they can apply for normal enrollment.
                if(!(newOpp.StageName == 'Enrolled' && newOpp.School_College__c == 'Undergraduate')){
                    newOpp.Application__c = null;
                    newOpp.StageName = 'File Closed';
                    newOpp.Withdrawal_Reason__c = 'ST - Switching Terms';

                    // if it is already File Closed, no need to calculate a new Stage Detail.
                    if(!newOpp.Stage_Detail__c.contains('File Closed')){
                        Set<String> details = new Set<String>{'Prospect', 'Inquired', 'Pre-Applied', 'App Started', 'App Submitted', 'App Completed', 'Wait Listed', 'Accepted', 'Fee Paid', 'Fee Waived', 'Registered'};
                        if (details.contains(newOpp.Stage_Detail__c)) {
                            newOpp.Stage_Detail__c = newOpp.Stage_Detail__c + ' - File Closed';
                        }
                        else {
                            newOpp.Stage_Detail__c = 'Unknown - File Closed';
                        }
                    }
                }

                if (newOpp.Opportunity_Key__c != null) {
                    newOpp.Opportunity_Key__c = newOpp.Opportunity_Key__c + '.Cloned';
                }
                insert newOpp;
            }
        }
        catch (Exception e) {
            System.debug(Logginglevel.ERROR, e);
            throw new AuraHandledException(e.getMessage());
        }
        return newOpp;
    }

    @AuraEnabled
    public static void updateApplication(Id oppId) {
        try {
            Opportunity opp = [SELECT Id, Name, Academic_Term__c, Application__c, Application__r.Intended_Term_of_Entry__c FROM Opportunity WHERE Id = :oppId];
            if (opp.Academic_Term__c != opp.Application__r.Intended_Term_of_Entry__c) {
                update new Application__c(Id = opp.Application__c, Intended_Term_of_Entry__c = opp.Academic_Term__c);
            }
        }
        catch (Exception e) {
            System.debug(Logginglevel.ERROR, e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}