src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <description>Loaded from Banner</description>
        <inlineHelpText>Options are from Banner</inlineHelpText>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Banner_Attributes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_International__c</fullName>
        <description>Used for Assignment Rule Engine to work around a bug (4/10/19)</description>
        <formula>Contact__r.Is_International__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is International</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Ownership__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, TDTM will not run the assignment rules for ownership of an Opportunity.</description>
        <inlineHelpText>Prevents Opportunity Ownership from being automatically assigned.</inlineHelpText>
        <label>Override Ownership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process_Assignments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Workflows from the Application and Contact object will check this field to trigger Opportunity Triggers, which will run the assignment rules. This should happen anytime a field on an App or Contact is edited that the Assignment Rules use as criteria.</description>
        <label>Process Assignments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>Student Type is a based on several values from the application to determine the type of student. BUILD by program, transfer by if they are transfering data, PSEO by the PSEO question on the application, New is default and New Student Previous PSEO will be done manually</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BUILD</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>New Student Previous PSEO</fullName>
                </value>
                <value>
                    <fullName>PSEO</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Banner_Attributes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Accepted to CAS Nursing Prog</fullName>
    </customValue>
    <customValue>
        <fullName>Audit</fullName>
    </customValue>
    <customValue>
        <fullName>Bringing in PSEO credits</fullName>
    </customValue>
    <customValue>
        <fullName>BUILD Student</fullName>
    </customValue>
    <customValue>
        <fullName>CAPS to Seminary Pathway</fullName>
    </customValue>
    <customValue>
        <fullName>Child of an Employee</fullName>
    </customValue>
    <customValue>
        <fullName>Child of a Pastor</fullName>
    </customValue>
    <customValue>
        <fullName>Combined Nursing BS/MS</fullName>
    </customValue>
    <customValue>
        <fullName>Converge School Church Ldrship</fullName>
    </customValue>
    <customValue>
        <fullName>Daystar Student</fullName>
    </customValue>
    <customValue>
        <fullName>Distance Residential</fullName>
    </customValue>
    <customValue>
        <fullName>DMin Self Directed Program</fullName>
    </customValue>
    <customValue>
        <fullName>DNP Preceptors</fullName>
    </customValue>
    <customValue>
        <fullName>FEC Continuing Degree Student</fullName>
    </customValue>
    <customValue>
        <fullName>FEC Partnership Participant</fullName>
    </customValue>
    <customValue>
        <fullName>Foundations of Acad. Readiness</fullName>
    </customValue>
    <customValue>
        <fullName>Honors Program Student</fullName>
    </customValue>
    <customValue>
        <fullName>Interim Full-Time Tuition</fullName>
    </customValue>
    <customValue>
        <fullName>Interim Half-Time Tuition</fullName>
    </customValue>
    <customValue>
        <fullName>Kern Candidates</fullName>
    </customValue>
    <customValue>
        <fullName>Kern Scholars</fullName>
    </customValue>
    <customValue>
        <fullName>Ministry Scholars</fullName>
    </customValue>
    <customValue>
        <fullName>Minn Theol Consortium Student</fullName>
    </customValue>
    <customValue>
        <fullName>NE Cert in Ministry Eff 2007</fullName>
    </customValue>
    <customValue>
        <fullName>No BA degree</fullName>
    </customValue>
    <customValue>
        <fullName>No MA degree</fullName>
    </customValue>
    <customValue>
        <fullName>Off-Campus Study Trip</fullName>
    </customValue>
    <customValue>
        <fullName>Partner - Campus Crusade</fullName>
    </customValue>
    <customValue>
        <fullName>Partner - Young Life</fullName>
    </customValue>
    <customValue>
        <fullName>Qualif Acad Beh Strat Licnse</fullName>
    </customValue>
    <masterLabel>Banner Attributes</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: Less than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: More than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
        <isActive>false</isActive>
        <label>Freshman</label>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
        <isActive>false</isActive>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
        <isActive>false</isActive>
        <label>PSEO</label>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Opportunity_Assignments.cls
/**
 * Created by ejc84332 on 2019-02-19.
 */



/* this is the signature for AssignmentRuleHander.execute (5/4/19)
public static void execute(List<sObject> newList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap){
 */

global class TDTM_Opportunity_Assignments extends TDTMVirtualTriggerHandler {

    global override void onAfterInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        AssignmentRuleHandler.execute(newList);
    }

    global override void onAfterUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        SObject[] update_list = new List<SObject>();

        for(SObject o : newList){

            Opportunity new_opp = (Opportunity)o;
            Opportunity old_opp = (Opportunity)oldMap.get(new_opp.Id);

            Boolean fields_changed =
                    new_opp.Attributes__c != old_opp.Attributes__c ||
                    new_opp.Academic_Program__c != old_opp.Academic_Program__c ||
                    new_opp.Academic_Term__c != old_opp.Academic_Term__c ||
                    new_opp.Student_Type__c != old_opp.Student_Type__c ||
                    new_opp.Is_International__c != old_opp.Is_International__c ||
                    (new_opp.Process_Assignments__c != old_opp.Process_Assignments__c && new_opp.Process_Assignments__c == true);

            if(fields_changed && new_opp.Override_Ownership__c == False){
                update_list.add(o);
            }
        }
        if(!update_list.isEmpty()){
            AssignmentRuleHandler.execute(update_list);
        }

    }

}