src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <inlineHelpText>End date for this term.</inlineHelpText>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <inlineHelpText>Start date for this term.</inlineHelpText>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expired_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <description>whether or not this Program Name/Code has been expired. Programs that are expired should not show up in searches or lookups.</description>
        <inlineHelpText>Whether this Program has expired, either due to being no longer offered or because it was replaced with a new Program (such as with a new Code)</inlineHelpText>
        <label>Expired Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Field based on Major from Banner to indicate the Application Type; SMAPRLE and SOACURR</description>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Program_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in. Used to build the Opportunity Key for the Interaction Processor to determine whether to create a new Opportunity or update an existing Opportunity.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age displayed is as of interaction create date.  The age does not update over time.</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>All_Academic_Interests__c</fullName>
        <description>A coma separated list of Academic Interests, from RFI Forms, Tell Me More cards, etc.</description>
        <label>All Academic Interests</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>High_School_Graduation_Year__c</fullName>
        <description>The year a student will graduate high school. Populated from RFI forms. Zapier does a lookup to find a term, but this is for reference if it doesn&apos;t find one.</description>
        <label>High School Graduation Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interaction_Status__c</fullName>
        <description>When set to &quot;New,&quot; the Interaction Processor runs, then updates the Status based on the result to &quot;Imported&quot; or &quot;Audit Needed.&quot;</description>
        <inlineHelpText>Set the Status to &quot;New&quot; and save to kick off the Interaction process.</inlineHelpText>
        <label>Interaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Audit Required</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Search_Text__c</fullName>
        <description>Used by the TDTM_Term_Program_Lookup to find a Program. Value should match the Program_Name_on_Application__c field on the Program__c object (not Account).</description>
        <label>Program Search Text</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>The School in which the student is interested</description>
        <inlineHelpText>The School in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Search_Text__c</fullName>
        <description>Used by the TDTM_Term_Program_Lookup to find a term. Value should be like &quot;Fall 2019&quot; or &quot;Spring 2020&quot;. CAS Interactions will use the Graduation Year field instead of this one.</description>
        <label>Term Search Text</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name_on_Application__c</fullName>
        <inlineHelpText>Name of the program to display on the application</inlineHelpText>
        <label>Program Name on Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Year_List.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2030</fullName>
    </customValue>
    <customValue>
        <fullName>2029</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <description>Year list used for picking High School Graduation Year</description>
    <masterLabel>Year List</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Term_Program_Lookup.cls
/**
 * Created by ejc84332 on 2019-03-05.
 */

global class TDTM_Term_Program_Lookup extends TDTMVirtualTriggerHandler {


    global override void onBeforeInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        process_term_program_lookups(newList);
    }

    global override void onBeforeUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        process_term_program_lookups(newList);
    }

    private void process_term_program_lookups(List<SObject> newList){
        Map<String, Id> program_map = get_programs();
        Map<String, Id> term_map = get_terms();

        for (SObject o : newList){
            Interaction__c interaction = (Interaction__c)o;

            System.debug('INTERACTION STATUS');
            System.debug(interaction.Interaction_Status__c);

            // handle CSG
            if(interaction.School_College__c != 'Undergraduate'){

                // get a program if no existing and we got search text.
                if(interaction.Academic_Program__c == null && interaction.Program_Search_Text__c != null){
                    System.debug('LOOKING FOR PROGRAM BY TEXT');
                    System.debug(interaction.Program_Search_Text__c);
                    System.debug(program_map.get(interaction.Program_Search_Text__c));
                    interaction.Academic_Program__c = program_map.get(interaction.Program_Search_Text__c);
                }

                String term_suffix;
                if(interaction.School_College__c == 'Seminary'){
                    term_suffix = ' - SEM';
                }else{
                    term_suffix = ' - CAPS/GS';
                }


                // get a term if no existing and we got search text.
                if(interaction.Academic_Term__c == null && interaction.Term_Search_Text__c != null){

                    String term_key = interaction.Term_Search_Text__c.trim() + term_suffix;

                    System.debug('LOOKING FOR TERM BY TEXT');
                    System.debug(term_key);
                    System.debug(term_map.get(term_key));

                    interaction.Academic_Term__c = term_map.get(term_key);
                }
                // otherwise get term by today's date, if there are more than one result (shouldn't be??), grab the first one.
                else if(interaction.Academic_Term__c == null && interaction.Term_Search_Text__c == null){
                    String term_search = '%' + term_suffix;
                    Academic_Term__c term_by_date = [select Id, Name from Academic_Term__c where Term_Start_Date__c <= TODAY and Term_End_Date__c > TODAY and Name like :term_search limit 1];
                    System.debug('FOUND THESE TERMS BY DATE');
                    System.debug(term_by_date);
                    if(term_by_date != null){
                        interaction.Academic_Term__c = term_by_date.Id;
                    }

                }

            // handle undergrad.
            }else{
                // Prioritze this over age or grad year
                if(interaction.Term_Search_Text__c != null){
                    String term_key = interaction.Term_Search_Text__c.trim() + ' - CAS';
                    System.debug('LOOKING FOR TERM BY TEXT');
                    System.debug(term_key);
                    System.debug(term_map.get(term_key));
                    interaction.Academic_Term__c = term_map.get(term_key);
                }
                else if(interaction.Academic_Term__c == null && (interaction.High_School_Graduation_Year__c != null || interaction.Age__c != null)){

                    if(interaction.Age__c != null && interaction.High_School_Graduation_Year__c == null){
                        Integer age = interaction.Age__c.intValue();
                        if(age > 18){
                            System.debug('AGE OVER 18');
                            System.debug(age);
                            interaction.Age__c.addError('Age cannot be over 18');
                        }else{
                            System.debug('AGE NOT OVER 18');
                            // calculate grad year. If the current month is Jan->August, do 18-1-age. This is to err
                            // on the side of sending them things sooner.
                            Integer grad_year;
                            if(System.today().month()<=8){
                                grad_year = System.today().year() + (17 - age);
                            }else{
                                grad_year = System.today().year() + (18 - age);
                            }
                            interaction.High_School_Graduation_Year__c = String.valueOf(grad_year);
                        }
                    }
                    System.debug('LOOKING FOR TERM');
                    System.debug('Fall ' + interaction.High_School_Graduation_Year__c + ' - CAS');
                    interaction.Academic_Term__c = term_map.get('Fall ' + interaction.High_School_Graduation_Year__c + ' - CAS');
                }

                // If there is a value in <>, Program is handled by TDTM_Academic_Interest_Handler.
                // If nothing, default to Undecided.
                // todo combine these two triggers?
                if(interaction.Academic_Program__c == null && interaction.All_Academic_Interests__c == null){
                    interaction.Academic_Program__c = program_map.get('Undecided');
                }
            }

            System.debug('INTERACTION STATUS END');
            System.debug(interaction.Interaction_Status__c);
        }
    }

    private Map<String, Id> get_programs(){
        // todo, add in filtering by actual list of programs we need.

        Map<String, Id> program_map = new Map<String, Id>();

        Program__c[] programs = [SELECT Id, Program_Name_on_Application__c FROM Program__c WHERE Academic_Program__r.Expired_Program__c=FALSE];

        for(Program__c p : programs){
            program_map.put(p.Program_Name_on_Application__c, p.Id);
        }

        return program_map;
    }


    private Map<String, Id> get_terms(){
        // todo, add in filtering by actual list of terms we need.

        Map<String, Id> term_map = new Map<String, Id>();

        Academic_Term__c[] terms = [SELECT Id, Name FROM Academic_Term__c];

        for(Academic_Term__c t : terms){
            term_map.put(t.Name, t.Id);
        }

        return term_map;
    }


}