src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term open.</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term close.</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Description__c</fullName>
        <description>Used for some formulas and automations.</description>
        <label>Term Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The HEDA Term record that maps to this Academic Term</description>
        <inlineHelpText>The HEDA Term record that maps to this Academic Term</inlineHelpText>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Academic Terms</relationshipLabel>
        <relationshipName>Academic_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Field based on Major from Banner to indicate the Application Type; SMAPRLE and SOACURR</description>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Academic_Program</fullName>
        <active>true</active>
        <description>An Academic Program offered at the University.</description>
        <label>Academic Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Submit_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Submit&quot; button shows-up for.</inlineHelpText>
        <label>Allow Submit From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Start_Status__c</fullName>
        <inlineHelpText>Application status that new applications are set to.</inlineHelpText>
        <label>Application Start Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Cancel&quot; button sets an application to</inlineHelpText>
        <label>Cancel Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this is the default Application Control when no URL Parameter is specified</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Application control for a specific school</description>
        <inlineHelpText>Application control for a specific school</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Submit&quot; button sets an application to</inlineHelpText>
        <label>Submit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <inlineHelpText>Text to be included at the end of a link to reference this Application Control. Format is &quot;?at=[URL_PARAMETER]&quot;</inlineHelpText>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Withdraw_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Withdraw&quot; button sets an application to</inlineHelpText>
        <label>Withdraw Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Program)</relationshipLabel>
        <relationshipName>CaseProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <formula>Related_Opportunity__r.Academic_Term__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Please enter the term.</inlineHelpText>
        <label>Term</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Banner_Id__c</fullName>
        <description>Banner identifier for this person</description>
        <externalId>true</externalId>
        <inlineHelpText>Banner identifier for this person</inlineHelpText>
        <label>Banner ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>hed__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/hed__Term__c.object
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <fields>
        <fullName>Term_Description__c</fullName>
        <label>Term Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>hed__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>hed__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Intended_Program_Term__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <inlineHelpText>Academic Term that this record is associated with.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Academic_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to open</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to close</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Program that this record applies to</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Intended_Program_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Intended Program Term</label>
    <nameField>
        <label>Intended Program Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intended Program Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Applications_Limit__c</fullName>
        <description>One Application (Any other applications, don&apos;t allow creation)
One Application Per Term (Only one application for the selected term)
One Application Per Program (Only one application for the selected program)
One Application Per Term Per Program (Only one application for the selected term and selected program)
~Blank~ No Restrictions</description>
        <label>Number of Applications Limit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One Application</fullName>
                </value>
                <value>
                    <fullName>One Application Per Term</fullName>
                </value>
                <value>
                    <fullName>One Application Per Program</fullName>
                </value>
                <value>
                    <fullName>One Application Per Term Per Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <recordTypes>
        <fullName>Academic_Program</fullName>
        <active>true</active>
        <description>The official degree or major a student applies to and is admitted into.</description>
        <label>Academic Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/classes/ReAdmissionHelperTest.cls
@isTest
public class ReAdmissionHelperTest {

	@TestSetup
	public static void testSetup() {
        createData();
    }

    public static void createData() {
        System.runAs(new User(Id = UserInfo.getUserId())){
            Group testGroup = new Group(Name='SSR_Advising', Type='Queue');
            insert testGroup;
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Case');
            insert testQueue;
        }

        Application_Control__c appControl = new Application_Control__c(
            Application_Start_Status__c = 'Started',
            Active__c = true,
            Allow_Submit_From__c = 'Started',
            Cancel_Status__c = 'Cancelled',
            Default__c = true,
            URL_Parameter__c ='st',
            Submit_Status__c = 'Submitted',
            Withdraw_Status__c = 'Withdrawn'
        );
        insert appControl;

        Account acc = new Account(Name='NewAcc');
        insert acc;
        hed__Term__c term = new hed__Term__c(Name = 'test', hed__Account__c = acc.Id, hed__Start_Date__c = Date.TODAY().addDays(2), hed__End_Date__c = Date.TODAY().addDays(20), Term_Description__c = 'Test');
        insert term;
		Academic_Term__c at = new Academic_Term__c(Name = 'test', Activate_Application_Date__c = Date.TODAY().addDays(2), End_Application_Date__c = Date.TODAY().addDays(20), School_College__c = 'Graduate', Term__c = term.Id);
        insert at;

        Account acc1 = new Account(Name = 'test1', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Academic_Program').getRecordTypeId());
        Account acc2 = new Account(Name = 'test2', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Academic_Program').getRecordTypeId());
        Account acc3 = new Account(Name = 'test3', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Academic_Program').getRecordTypeId());
        insert new List<Account>{acc1, acc2, acc3};

		Program__c p1 = new Program__c(Name = 'test1', Academic_Program__c = acc1.Id, Number_of_Applications_Limit__c = 'One Application Per Term', School_College__c = 'Graduate', Active__c = true);
        Program__c p2 = new Program__c(Name = 'test2', Academic_Program__c = acc2.Id, Number_of_Applications_Limit__c = 'One Application Per Term', School_College__c = 'Graduate', Active__c = true);
        Program__c p3 = new Program__c(Name = 'test3', Academic_Program__c = acc3.Id, Number_of_Applications_Limit__c = 'One Application Per Term', School_College__c = 'Graduate', Active__c = true);
        insert new List<Program__c>{p1, p2, p3};

		Intended_Program_Term__c ipt1 = new Intended_Program_Term__c(Academic_Term__c = at.Id, Intended_Program__c = p1.Id, Activate_Application_Date__c = Date.TODAY().addDays(-1), End_Application_Date__c = Date.TODAY().addDays(1), School_College__c = 'Graduate');
		Intended_Program_Term__c ipt2 = new Intended_Program_Term__c(Academic_Term__c = at.Id, Intended_Program__c = p2.Id, Activate_Application_Date__c = Date.TODAY().addDays(-1), End_Application_Date__c = Date.TODAY().addDays(1), School_College__c = 'Graduate');
		Intended_Program_Term__c ipt3 = new Intended_Program_Term__c(Academic_Term__c = at.Id, Intended_Program__c = p3.Id, Activate_Application_Date__c = Date.TODAY().addDays(-1), End_Application_Date__c = Date.TODAY().addDays(1), School_College__c = 'Graduate');
        insert new List<Intended_Program_Term__c>{ipt1, ipt2, ipt3};

        Contact student = new Contact(LastName='TestLast2', FirstName = 'TestFirst2', Email = 'TestContact2@example.bethel.com', MailingStateCode = 'MN', Banner_Id__c = 'TEST2');
        insert student;

   }

    static testMethod void updateContactTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        Contact theContact = new Contact();
        theContact.FirstName = 'TestFirst2';
        theContact.MiddleName = 'TestMiddle2';
        theContact.LastName = 'TestLast2';
        theContact.Email = 'TestContact2@example.bethel.com';
        theContact.MailingStreet = '123 Main St';
        theContact.MailingCity = 'Rochester';
        theContact.MailingStateCode = 'MN';
        theContact.MailingCountryCode = 'US';
        theContact.MailingPostalCode = '55901';
        theContact.HomePhone = '555-555-5555';
        theContact.MobilePhone = '555-555-5556';
        theContact.hed__Gender__c = 'Male';
        theContact.hed__Race__c = 'White';
        theContact.hed__Social_Security_Number__c = '123-45-6789';
        theContact.hed__WorkPhone__c = '555-555-5557';
        theContact.Banner_Id__c = 'TEST2';
        theContact.Citizenship__c = 'Citizen';
        theContact.Is_Hispanic__c = 'No';
        theContact.Is_Veteran__c = 'No';
        theContact.Pled_Guilty__c = 'No';

        test.startTest();
        ReAdmissionHelper.updateContact(theContact, existingContact);
        test.stopTest();

        System.assertEquals(theContact.LastName, existingContact.LastName);
        System.assertEquals(theContact.Email, existingContact.Email);
        System.assertEquals(theContact.hed__Gender__c, existingContact.hed__Gender__c);
    }

    static testMethod void createContactDataStringTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        Contact theContact = new Contact();
        theContact.FirstName = 'TestFirst2';
        theContact.MiddleName = 'TestMiddle2';
        theContact.LastName = 'TestLast2';
        theContact.Email = 'TestContact2@example.bethel.com';
        theContact.MailingStreet = '123 Main St';
        theContact.MailingCity = 'Rochester';
        theContact.MailingStateCode = 'MN';
        theContact.MailingCountryCode = 'US';
        theContact.MailingPostalCode = '55901';
        theContact.HomePhone = '555-555-5555';
        theContact.MobilePhone = '555-555-5556';
        theContact.hed__Gender__c = 'Male';
        theContact.hed__Race__c = 'White';
        theContact.hed__Social_Security_Number__c = '123-45-6789';
        theContact.hed__WorkPhone__c = '555-555-5557';
        theContact.Banner_Id__c = 'TEST2';
        theContact.Citizenship__c = 'Citizen';
        theContact.Is_Hispanic__c = 'No';
        theContact.Is_Veteran__c = 'No';
        theContact.Pled_Guilty__c = 'No';
        ReAdmissionController.ReAdmissionRequest request = new ReAdmissionController.ReAdmissionRequest();
        request.theContact = theContact;

        test.startTest();
        String data = ReAdmissionHelper.createContactDataString(request);
        test.stopTest();

        System.assert(data != null);
    }

    static testMethod void createCaseTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        ReAdmissionController.ReAdmissionRequest request = new ReAdmissionController.ReAdmissionRequest();
        request.school = 'Graduate';
        request.financialAid = 'No';
        request.hasChanged = 'Yes';
        request.program = [SELECT Id FROM Account WHERE Name = 'test1'].Id;
        request.term = 'Test';
        request.academicRecord = 'Went to school';
        request.employerName = 'ACME';
        request.employerAddress = '124 Main St.; Rochester, MN; US';
        request.responsibilities = 'Do stuff';
        request.hasOtherName = 'Yes';
        request.otherName = 'Tester2';
        request.hasBusinessOffice = 'no';
        request.whyLeftEssay = 'I do not know.';
        request.whyBackEssay = 'Why Not?';

        test.startTest();
        Case theCase = ReAdmissionHelper.createCase(existingContact, request, null);
        test.stopTest();

        System.assert(theCase != null);
    }

    static testMethod void assignCaseTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        ReAdmissionController.ReAdmissionRequest request = new ReAdmissionController.ReAdmissionRequest();
        request.school = 'Graduate';
        request.financialAid = 'No';
        request.hasChanged = 'Yes';
        request.program = [SELECT Id FROM Account WHERE Name = 'test1'].Id;
        request.term = 'Test';
        request.academicRecord = 'Went to school';
        request.employerName = 'ACME';
        request.employerAddress = '124 Main St.; Rochester, MN; US';
        request.responsibilities = 'Do stuff';
        request.hasOtherName = 'Yes';
        request.otherName = 'Tester2';
        request.hasBusinessOffice = 'no';
        request.whyLeftEssay = 'I do not know.';
        request.whyBackEssay = 'Why Not?';

        test.startTest();
        Case theCase = ReAdmissionHelper.createCase(existingContact, request, null);
        insert theCase;
        ReAdmissionHelper.assignCase(theCase);
        Case newCase = ReAdmissionHelper.getCase(theCase.Id);
        test.stopTest();

        System.assert(theCase.OwnerId != null);
        System.assert(newCase != null);
    }

    static testMethod void attachDocumentTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        ReAdmissionController.ReAdmissionRequest request = new ReAdmissionController.ReAdmissionRequest();
        request.school = 'Graduate';
        request.financialAid = 'No';
        request.hasChanged = 'Yes';
        request.program = [SELECT Id FROM Account WHERE Name = 'test1'].Id;
        request.term = 'Test';
        request.academicRecord = 'Went to school';
        request.employerName = 'ACME';
        request.employerAddress = '124 Main St.; Rochester, MN; US';
        request.responsibilities = 'Do stuff';
        request.hasOtherName = 'Yes';
        request.otherName = 'Tester2';
        request.hasBusinessOffice = 'no';
        request.whyLeftEssay = 'I do not know.';
        request.whyBackEssay = 'Why Not?';

        test.startTest();
        Case theCase = ReAdmissionHelper.createCase(existingContact, request, null);
        insert theCase;
        ContentVersion link = ReAdmissionHelper.attachDocument(theCase, Blob.valueOf('My Resume'), 'My Resume');
        test.stopTest();

        System.assert(theCase.Id != null);
        System.assert(link != null);
    }

    static testMethod void createEmploymentHistoryTest() {
        
        Contact existingContact = ContactHelper.getContactFromBethelId('TEST2');
        System.assert(existingContact != null);

        test.startTest();
        Employment_History__c history = ReAdmissionHelper.createEmploymentHistory(existingContact, 'ACME', '123 Main St; Chicago, IL; 66066 US', 'Do stuff');
        Employment_History__c newHistory = ReAdmissionHelper.getEmploymentHistory(existingContact.Id);
        test.stopTest();

        System.assert(newHistory != null);
    }

}