src/objects/Academic_Term__c.object
<CustomObject>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_SMS__Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Log__c.object
<CustomObject>
    <description>Generic object used to log events</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>Event_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mogli Gateway</label>
        <referenceTo>Mogli_SMS__Gateway__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>Event_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Report</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Funnel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mogli_SMS__Gateway__c.object
<CustomObject>
    <label>Gateway</label>
    <nameField>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mogli_SMS__SMS__c.object
<CustomObject>
    <fields>
        <fullName>Event_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Log</label>
        <referenceTo>Event_Log__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gateway</label>
        <referenceTo>Mogli_SMS__Gateway__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Mogli_Number__c</fullName>
        <externalId>true</externalId>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Flow_BulkSMS.cls
/**
 * Created by bej68982 on 1/30/20.
 */

global class Flow_BulkSMS {

    //Invocable Variables
    public class BulkSmsRequest {
        @InvocableVariable(Label='Request Type' Required=true)
        public String requestType;

        @InvocableVariable(Label='Report ID' Required=false)
        public String reportId;

        @InvocableVariable(Label='Campaign ID' Required=false)
        public String campaignId;

        @InvocableVariable(Label='SMS Message' Required=false)
        public String smsMessage;

        @InvocableVariable(Label='Gateway' Required=false)
        public String gateway;

        @InvocableVariable(Label='Term(s)' Required=false)
        public String requestedTerms;

        @InvocableVariable(Label='Stage Detail(s)' Required=false)
        public String stageDetails;

        @InvocableVariable(Label='Initiator' Required=false)
        public String initiator;
    }

    @InvocableMethod(Label='Bulk SMS Request' Description='Sends a SMS for each contact that matches the passed criteria')
    public static  List<String> BulkSMS(List<BulkSmsRequest> requests) {
        List<String> results = new List<String>();
        List<String> termList = new List<String>();
        List<String> stageDetailList = new List<String>();
        List<Contact> contacts = new List<Contact>();

        for(BulkSmsRequest request : requests) {
            switch on request.requestType {
                when 'report' {
                    Event_Log__c log1 = new Event_Log__c(Message__c=request.smsMessage, OwnerId=request.initiator, Gateway__c =request.gateway, Type__c='Report');
                    insert log1;
                    contacts = getContactsFromReport(request.reportId);
                    results.add(CreateSmsRecords(contacts, request.gateway, request.smsMessage, log1));
                }
                when 'funnel' {
                    termList = request.requestedTerms.split(';');
                    stageDetailList = request.stageDetails.split(';');
                    Event_Log__c log2 = new Event_Log__c(Message__c=request.smsMessage, OwnerId=request.initiator, Gateway__c =request.gateway, Type__c='Funnel');
                    insert log2;
                    contacts = getContactsFromFunnel(termList, stageDetailList, request.initiator);
                    results.add(CreateSmsRecords(contacts, request.gateway, request.smsMessage, log2));
                }
                when 'campaign' {
                    Event_Log__c log3 = new Event_Log__c(Message__c=request.smsMessage, OwnerId=request.initiator, Gateway__c =request.gateway, Campaign__c=request.campaignId, Type__c='Campaign');
                    insert log3;
                    contacts = getContactsFromCampaign(request.campaignId);
                    results.add(CreateSmsRecords(contacts, request.gateway, request.smsMessage, log3));
                }
                when 'report total' {
                    results.add(getListOfContacts('report', request.reportId, null, null, null, null));
                }
                when 'funnel total' {
                    stageDetailList = request.stageDetails.split(';');
                    termList = request.requestedTerms.split(';');
                    results.add(getListOfContacts('funnel', null, null, termList, stageDetailList, request.initiator));
                }
                when 'campaign total' {
                    results.add(getListOfContacts('campaign', null, request.campaignId, null, null, null));
                }
                when else {
                    results.add('Please enter a valid Request Type');
                }
            }
        }
        return results;
    }

    public static String CreateSmsRecords(List<Contact> contacts, Id gatewayId, String message, Event_Log__c log) {
        Try{
            List<Mogli_SMS__SMS__c> new_records = new List<Mogli_SMS__SMS__c>();

            //Loop through contacts and create SMS record for each
            for(Contact currentContact : contacts) {
                Mogli_SMS__SMS__c newSmsRecord = new Mogli_SMS__SMS__c(Mogli_SMS__Message__c=message, Mogli_SMS__Phone_Number__c=currentContact.Mogli_SMS__Mogli_Number__c, Mogli_SMS__Gateway__c=gatewayId, Event_Log__c=log.Id, Mogli_SMS__Status__c='Sent Successfully');
                new_records.add(newSmsRecord);
            }

            //Remove Duplicates
            Set<Mogli_SMS__SMS__c> tempSet = new Set<Mogli_SMS__SMS__c>();
            tempSet.addAll(new_records);
            List<Mogli_SMS__SMS__c> dedupedSMS = new List<Mogli_SMS__SMS__c>();
            dedupedSMS.addAll(tempSet);

            //Insert SMS Records
            insert dedupedSMS;

            //Return confirmation message
            return 'Successfully sent '+dedupedSMS.size()+' text messages';
        } catch(Exception e) {
            return 'Error: '+e;
        }
    }

    public static  List<Contact> getContactsFromReport(Id reportId) {
        List<Contact> contacts = new List<Contact>();

        // Get the Report Description
        Reports.ReportDescribeResult reportDescription = Reports.ReportManager.describeReport(reportId);
        // Get the Report Metadata
        Reports.ReportMetadata reportMetadata = reportDescription.getReportMetadata();
        //Get the Report Type
        Reports.ReportType rt = reportMetadata.getReportType();
        //Verify the report returns Contacts
        if(!rt.getType().startsWithIgnoreCase('contacts')) {
            return contacts;
        }

        // Run a report synchronously;
        Reports.ReportResults results = Reports.ReportManager.runReport(reportId, true);
        results.getAllData();

        // Get the fact map from the report results
        Reports.ReportFactWithDetails factDetails =
                (Reports.ReportFactWithDetails)results.getFactMap().get('T!T');

        //create a list of report rows and populate it with the result rows from fact map
        List<Reports.ReportDetailRow> reportRows = factDetails.getRows();

        //loop through each report detail row and store contact id
        List<Id> contactIds = new List<Id>();
        for(Reports.ReportDetailRow reportRow : reportRows) {
            List<Reports.ReportDataCell> datacells = reportRow.getDataCells();
            Reports.ReportDataCell datacell = datacells[0];
            contactIds.add((id)datacell.getValue());
        }
        contacts = [
                SELECT
                        Name,Id,Mogli_SMS__Mogli_Number__c
                FROM
                        Contact
                WHERE
                        Id IN :contactIds AND Mogli_SMS__Mogli_Number__c != null
        ];

        //Remove Duplicates from Contacts
        Set<Contact> tempSet = new Set<Contact>();
        tempSet.addAll(contacts);
        List<Contact> dedupedContacts = new List<Contact>();
        dedupedContacts.addAll(tempSet);
        return dedupedContacts;
    }

    public static  List<Contact> getContactsFromFunnel(List<String> termList, List<String> stageDetailList, Id initiatorId) {
        List<Opportunity> matchingOpps = new List<Opportunity>();
        List<Id> contact_ids = new List<Id>();
        //Find Opportunities that match the criteria given by the user
        matchingOpps = [
            SELECT
                    Contact__c
            FROM
                    Opportunity
            WHERE
                    Stage_Detail__c IN :stageDetailList AND Academic_Term__r.Name IN :termList AND OwnerId = :initiatorId
        ];
        //Get Contact IDs from each Opportunity
        for(Opportunity o : matchingOpps){
            contact_ids.add(o.Contact__c);
        }
        //Return all matching Contacts
        return [
            SELECT
                    Id, Name, Mogli_SMS__Mogli_Number__c
            FROM
                    Contact
            WHERE
                    Id IN :contact_ids AND Mogli_SMS__Mogli_Number__c != null
        ];
    }

    public static  List<Contact> getContactsFromCampaign(Id campaignId) {
        List<Contact> contacts = [
            SELECT
                    Id, Name, Mogli_SMS__Mogli_Number__c
            FROM
                    Contact
            WHERE
                    Id IN (
                            SELECT
                                    ContactId
                            FROM
                                    CampaignMember
                            WHERE
                            CampaignId = :campaignId AND ContactId != null
                    ) AND Mogli_SMS__Mogli_Number__c != null
        ];
        return contacts;
    }

    public static  String getListOfContacts(String type, Id reportId, ID campaignId, List<String> termList, List<String> stageDetailList, Id initiatorId) {
        String listOfContacts = '';
        List<Contact> returnedContacts = new List<Contact>();
        switch on type {
            when 'campaign'{
                returnedContacts = getContactsFromCampaign(campaignId);
            }
            when 'funnel'{
                returnedContacts = getContactsFromFunnel(termList, stageDetailList, initiatorId);
            }
            when 'report'{
                returnedContacts = getContactsFromReport(reportId);
            }
        }
        if(returnedContacts.size() > 0){
            for(Contact c : returnedContacts){
                listOfContacts = listOfContacts + '\N' + c.Name + ';';
            }
        }else{
            listOfContacts = 'No Contacts Found';
        }
        return listOfContacts;
    }
}