src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Term_of_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Term of Entry</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Program_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in. Used to build the Opportunity Key for the Interaction Processor to determine whether to create a new Opportunity or update an existing Opportunity.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used as part of the application creation process</description>
        <inlineHelpText>Used as part of the application creation process</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source__c</fullName>
        <description>The method by which the data is being added as an Interaction. Set to &quot;Manual Entry&quot; for hand entry, otherwise it represents the integration source (Webform, Purchase List, etc.) Also used in the Skip Mapping functionality on Interaction Mappings.</description>
        <label>Interaction Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Manual Entry</fullName>
                    <default>true</default>
                    <label>Manual Entry</label>
                </value>
                <value>
                    <fullName>Purchase List</fullName>
                </value>
                <value>
                    <fullName>Student Information System</fullName>
                </value>
                <value>
                    <fullName>Webform</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Register</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Family Member Create</fullName>
                </value>
                <value>
                    <fullName>Account Register</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>The way in which the Lead or Contact&apos;s information was first received. Value &quot;Office Visit&quot; is required by the Interactions package tests.</description>
        <inlineHelpText>Indicate the initial source of this data.</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Camps</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Conferences &amp; Fairs</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event &amp; Visits</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>List &amp; Vendor</fullName>
                </value>
                <value>
                    <fullName>Office Visit</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Registrar</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Transcripts</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Opportunity Stage Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Opportunity_Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <inlineHelpText>Required to create or update an Opportunity.</inlineHelpText>
        <label>Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inquired</fullName>
                    <default>true</default>
                    <label>Inquired</label>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Wait Listed</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>File Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>The School in which the student is interested</description>
        <inlineHelpText>The School in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/InteractionHelper.cls
/*
 * 
 * Test class - TDTMApplicationTriggerHandlerTest, InteractionHelperTest
 * 
 * 
 */ 
public class InteractionHelper {

    public static Interaction__c createInteractionForNewApplication(Application__c app) {
        Contact c = ContactHelper.getContact(app.Contact__c);
        Interaction__c i = new Interaction__c(
            Contact__c = app.Contact__c,
            First_Name__c = c.FirstName,
            Last_Name__c = c.LastName,
            Email__c = c.Email,
            School_College__c = app.School_College__c,
            Academic_Program__c = app.Intended_Program__c,
            Academic_Term__c = app.Intended_Term_of_Entry__c,
            Application__c = app.Id,
            Interaction_Source__c = 'Application',
            Lead_Source__c = 'Application Create',
            Opportunity_Stage__c = 'Inquired',
            Opportunity_Stage_Detail__c = 'App Started'
        );
        insert i;
        return i;
    }

    public static Interaction__c createInteractionForSubmittedApplication(Id appId) {
        Application__c app = getApplication(appId);
        Contact c = ContactHelper.getContact(app.Contact__c);
        Opportunity o = getOpportunityForApplication(appId);
        Interaction__c i = new Interaction__c(
            Contact__c = app.Contact__c,
            First_Name__c = c.FirstName,
            Last_Name__c = c.LastName,
            Email__c = c.Email,
            School_College__c = app.School_College__c,
            Academic_Program__c = app.Intended_Program__c,
            Academic_Term__c = app.Intended_Term_of_Entry__c,
            Application__c = app.Id,
            Interaction_Source__c = 'Application',
            Lead_Source__c = 'Application Submit',
            Opportunity_Stage__c = 'Applied',
            Opportunity_Stage_Detail__c = 'App Submitted',
            Opportunity__c = o.Id
        );
        insert i;
        return i;
    }

    public static Interaction__c createInteractionForChangedApplication(Application__c app) {
        Contact c = ContactHelper.getContact(app.Contact__c);
        Interaction__c i = new Interaction__c(
            Contact__c = app.Contact__c,
            First_Name__c = c.FirstName,
            Last_Name__c = c.LastName,
            Email__c = c.Email,
            School_College__c = app.School_College__c,
            Academic_Program__c = app.Intended_Program__c,
            Academic_Term__c = app.Intended_Term_of_Entry__c,
            Application__c = app.Id,
            Interaction_Source__c = 'Application',
            Lead_Source__c = 'Application Change'
        );
        insert i;
        return i;
    }

    public static void createInteractionForChangedApplication(List<Application__c> apps) {
        Set<Id> contactIds = new Set<Id>();
        for (Application__c app : apps) {
            contactIds.add(app.Contact__c);
        }
        Map<Id, Contact> contactMap = ContactHelper.getContactMap(contactIds);
        List<Interaction__c> interactions = new List<Interaction__c>();
        for (Application__c app : apps) {
            Contact c = contactMap.get(app.Contact__c);
            if (c != null) {
                Interaction__c i = new Interaction__c(
                    Contact__c = app.Contact__c,
                    First_Name__c = c.FirstName,
                    Last_Name__c = c.LastName,
                    Email__c = c.Email,
                    School_College__c = app.School_College__c,
                    Academic_Program__c = app.Intended_Program__c,
                    Academic_Term__c = app.Intended_Term_of_Entry__c,
                    Application__c = app.Id,
                    Interaction_Source__c = 'Application',
                    Lead_Source__c = 'Application Change'
                );
                interactions.add(i);
            }
        }
        insert interactions;
    }

    public static Academic_Term__c getAcademicTerm(Id theId) {
        Academic_Term__c term = null;
        List<Academic_Term__c> terms = [
           Select 
                Id, 
                Term_End_Date__c, 
                Term_Start_Date__c,
                Term_Status__c
            FROM 
                Academic_Term__c
            WHERE
                Id = :theId
        ];
        if (terms != null && !terms.isEmpty()) {
            term = terms[0];
        }
        return term;
    }

    public static Application__c getApplication(Id theId) {
        Application__c app = null;
        List<Application__c> apps = [
            SELECT 
                Id, 
                Contact__c,
                Intended_Program__c, 
                Intended_Term_of_Entry__c,
                School_College__c
            FROM 
                Application__c 
            WHERE 
                Id = :theId
        ];
        if (apps != null && !apps.isEmpty()) {
            app = apps[0];
        }
        return app;
    }

    public static Opportunity getOpportunityForApplication(Id appId) {
        Opportunity opp = null;
        List<Opportunity> opps = [
            SELECT
                Id
            FROM
                Opportunity
            WHERE
                Application__c = :appId
        ];
        if (opps != null && !opps.isEmpty()) {
            opp = opps[0];
        }
        return opp;
    }

}