src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intended_Program_Term__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <inlineHelpText>Academic Term that this record is associated with.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Academic_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Program that this record applies to</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Intended_Program_Periods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Intended Program Term</label>
    <nameField>
        <label>Intended Program Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intended Program Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Delivery_Format__c</fullName>
        <description>The format the student chooses on the Application.</description>
        <label>Preferred Delivery Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Delivery_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Face-to-Face</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Blended</fullName>
    </customValue>
    <customValue>
        <fullName>SemPM</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>On-Campus</fullName>
        <isActive>false</isActive>
        <label>On-Campus</label>
    </customValue>
    <customValue>
        <fullName>Evenings and Weekends</fullName>
        <isActive>false</isActive>
        <label>Evenings and Weekends</label>
    </customValue>
    <description>Types that a program can be delivered.</description>
    <masterLabel>Delivery Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Opportunity_Program_Term_Validate.cls
/**
 * Created by ejc84332 on 2019-04-02.
 */

global class TDTM_Opportunity_Program_Term_Validate extends TDTMVirtualTriggerHandler {

    global override void onBeforeInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        ValidateProgramTerm(newList);
    }

    global override void onBeforeUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        SObject[] process_list = new List<SObject>();

        for (SObject s : newList){
            Opportunity new_opp = (Opportunity)s;
            Opportunity old_opp = (Opportunity) oldMap.get(new_opp.Id);

            if(new_opp.Academic_Program__c != old_opp.Academic_Program__c || new_opp.Academic_Term__c != old_opp.Academic_Term__c){
                process_list.add(s);
            }
        }

        ValidateProgramTerm(process_list);
    }


    private void ValidateProgramTerm(List<SObject> newList) {

        Set<Id> program_ids = new Set<Id>();
        for (SObject o : newList) {
            Opportunity opp = (Opportunity) o;
            program_ids.add(opp.Academic_Term__c);
        }

        Intended_Program_Term__c[] intended_programs = [SELECT Academic_Term__c, Intended_Program__r.Name, Intended_Program__c, Academic_Term__r.Name, Delivery_Type__c FROM Intended_Program_Term__c WHERE Academic_Term__c IN :program_ids];

        // todo: I think this logic could be impoved.
        for (SObject o : newList) {
            Opportunity opp = (Opportunity) o;
            Boolean found_match = false;

            if (opp.Academic_Program__c == null || opp.Academic_Term__c == null){
                found_match = true;
                break;
            }

            if (opp.School_College__c == 'Seminary' && opp.Preferred_Delivery_Format__c != null) {
                for (Intended_Program_Term__c ip : intended_programs) {
                    String dt;
                    if(ip.Delivery_Type__c == null){
                        // all apply if this field is blank
                         dt = 'Online;Blended;Face-to-Face';
                    }else{
                        dt = ip.Delivery_Type__c;
                    }
                    if (ip.Academic_Term__c == opp.Academic_Term__c && ip.Intended_Program__c == opp.Academic_Program__c && dt.contains(opp.Preferred_Delivery_Format__c)) {
                        found_match = true;
                        break;
                    }
                }
            } else {
                for (Intended_Program_Term__c ip : intended_programs) {
                    if(ip.Intended_Program__r.Name == 'Marriage and Family Therapy Post-Graduate Certificate'){
                        System.debug('CHECKING PROGRAM');
                        System.debug(ip.Intended_Program__c);
                        System.debug('CHECKING TERM');
                        System.debug(ip.Academic_Term__c);
                        System.debug('Opp Fields');
                        System.debug(opp.Academic_Term__c);
                        System.debug(opp.Academic_Program__c);
                    }

                    if (ip.Academic_Term__c == opp.Academic_Term__c && ip.Intended_Program__c == opp.Academic_Program__c) {
                        found_match = true;
                        break;
                    }
                }
            }
            if(!found_match) {
                if(opp.School_College__c == 'Seminary') {
                    opp.addError('Program, Term, and Delivery not a valid combination.');
                }else {
                    opp.addError('Program and Term not a valid combination.');
                }
            }
        }
    }
}