src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term open.</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term close.</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Field based on Major from Banner to indicate the Application Type; SMAPRLE and SOACURR</description>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Cancel_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Cancel&quot; button shows-up for.</inlineHelpText>
        <label>Allow Cancel From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Submit_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Submit&quot; button shows-up for.</inlineHelpText>
        <label>Allow Submit From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Withdraw_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Withdraw&quot; button shows-up for.</inlineHelpText>
        <label>Allow Withdraw From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Start_Status__c</fullName>
        <inlineHelpText>Application status that new applications are set to.</inlineHelpText>
        <label>Application Start Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Cancel&quot; button sets an application to</inlineHelpText>
        <label>Cancel Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this is the default Application Control when no URL Parameter is specified</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Application control for a specific school</description>
        <inlineHelpText>Application control for a specific school</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Submit&quot; button sets an application to</inlineHelpText>
        <label>Submit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <inlineHelpText>Text to be included at the end of a link to reference this Application Control. Format is &quot;?at=[URL_PARAMETER]&quot;</inlineHelpText>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Withdraw_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Withdraw&quot; button sets an application to</inlineHelpText>
        <label>Withdraw Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intended_Program_Term__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <inlineHelpText>Academic Term that this record is associated with.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Academic_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to open</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to close</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Intended Program Term</label>
    <nameField>
        <label>Intended Program Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intended Program Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) that this program does not apply to (applies to all if blank)</inlineHelpText>
        <label>Hide Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) that this program does not apply to (applies to all if blank)</inlineHelpText>
        <label>Hide Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Student_Type__c</fullName>
        <inlineHelpText>Student type(s) that this program does not apply to (applies to all if blank)</inlineHelpText>
        <label>Hide Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Applications_Limit__c</fullName>
        <description>One Application (Any other applications, don&apos;t allow creation)
One Application Per Term (Only one application for the selected term)
One Application Per Program (Only one application for the selected program)
One Application Per Term Per Program (Only one application for the selected term and selected program)
~Blank~ No Restrictions</description>
        <label>Number of Applications Limit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One Application</fullName>
                </value>
                <value>
                    <fullName>One Application Per Term</fullName>
                </value>
                <value>
                    <fullName>One Application Per Program</fullName>
                </value>
                <value>
                    <fullName>One Application Per Term Per Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
        <isActive>false</isActive>
        <label>Seminary</label>
    </customValue>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
        <isActive>false</isActive>
        <label>Adult Undergraduate</label>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident Alien</fullName>
    </customValue>
    <customValue>
        <fullName>Not Citizen or Permanent Resident</fullName>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: Less than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: More than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
        <isActive>false</isActive>
        <label>Freshman</label>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
        <isActive>false</isActive>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
        <isActive>false</isActive>
        <label>PSEO</label>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/ApplicationHelperTest.cls
@isTest
public class ApplicationHelperTest {
	
	@TestSetup
	static void testSetup(){

		//create application data
       Application_Control__c appControl = new Application_Control__c(
            Application_Start_Status__c=Application_Control__c.Application_Start_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Active__c=true,
            Allow_Cancel_From__c=Application_Control__c.Allow_Cancel_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Withdraw_From__c=Application_Control__c.Allow_Withdraw_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Submit_From__c=Application_Control__c.Allow_Submit_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Cancel_Status__c=Application_Control__c.Cancel_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Default__c=true,
            URL_Parameter__c ='st',
            Submit_Status__c=Application_Control__c.Submit_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Withdraw_Status__c=Application_Control__c.Withdraw_Status__c.getDescribe().getPicklistValues()[0].getValue()
        );
        insert appControl;

		Academic_Term__c at = new Academic_Term__c(Name = 'test', Activate_Application_Date__c = Date.TODAY().addDays(-2), End_Application_Date__c = Date.TODAY().addDays(2));
        insert at;

		Program__c p1 = new Program__c(Name = 'test1', Number_of_Applications_Limit__c = 'One Application', Applicant_Type__c = Program__c.Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p2 = new Program__c(Name = 'test2', Number_of_Applications_Limit__c = 'One Application Per Term', Hide_Applicant_Type__c = Program__c.Hide_Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p3 = new Program__c(Name = 'test3', Number_of_Applications_Limit__c = 'One Application Per Program', Hide_Student_Type__c = Program__c.Hide_Student_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p4 = new Program__c(Name = 'test4', Hide_Citizenship__c = Program__c.Hide_Citizenship__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p5 = new Program__c(Name = 'test5');
        insert new List<Program__c>{p1, p2, p3, p4, p5};

		Intended_Program_Term__c ipt = new Intended_Program_Term__c(Academic_Term__c = at.Id, Activate_Application_Date__c = Date.TODAY().addDays(-1), End_Application_Date__c = Date.TODAY().addDays(-1), Applicant_Type__c = Intended_Program_Term__c.Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        insert ipt;

        Account acc = new Account(Name='NewAcc');
        insert acc;

        Contact studentResident = new Contact(LastName='TestLast', FirstName = 'TestFirst', Email = 'TestContact@example.bethel.com', MailingStateCode = 'MN');
        insert studentResident;

        Contact student = new Contact(LastName='TestLast2', FirstName = 'TestFirst2', Email = 'TestContact2@example.bethel.com', MailingStateCode = 'WI');
        insert student;

        List<Application__c> apps = new List<Application__c>();

        Application__c undergrad = new Application__c(
			Contact__c=studentResident.Id,
			School_College__c = 'Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

            apps.add(undergrad);


        Application__c undergradTransfer = new Application__c(
			Contact__c=student.Id,
			School_College__c = 'Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
            Is_Transfer_Student__c = 'Yes',
			Intended_Term_of_Entry__c = at.Id);

            apps.add(undergradTransfer);

        Application__c undergradIsApplyingForPSEO = new Application__c(
			Contact__c=student.Id,
			School_College__c = 'Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
            Is_Applying_For_PSEO__c = 'Yes',
			Intended_Term_of_Entry__c = at.Id);

            apps.add(undergradIsApplyingForPSEO);


            Application__c adultUndergradCollege = new Application__c(
			Contact__c=studentResident.Id,
            College_Credits_Transferred__c = 'No transfer credits',
			School_College__c = 'Adult Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

            apps.add(adultUndergradCollege);

            Application__c adultUndergradCollegeCreditsTransferred1to30 = new Application__c(
			Contact__c=studentResident.Id,
            College_Credits_Transferred__c = '1-30 transfer credits',
			School_College__c = 'Adult Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

            apps.add(adultUndergradCollegeCreditsTransferred1to30);

            Application__c adultUndergradCollegeCreditsTransferred30Plus = new Application__c(
			Contact__c=student.Id,
            College_Credits_Transferred__c = 'More than 30 transfer credits',
			School_College__c = 'Adult Undergraduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

            apps.add(adultUndergradCollegeCreditsTransferred30Plus);

            Application__c graduate = new Application__c(
			Contact__c=student.Id,
			School_College__c = 'Graduate',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

             apps.add(graduate);

            Application__c seminary = new Application__c(
			Contact__c=student.Id,
			School_College__c = 'Seminary',
			Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
			Intended_Program__c =  p3.Id,
			Intended_Term_of_Entry__c = at.Id);

             apps.add(seminary);

             insert apps;
	  
	}

	static testMethod void testUpdateFilters(){
		List<Application__c> apps = [SELECT Id, School_College__c, Is_Transfer_Student__c, Applicant_Type__c,
            Is_Applying_For_PSEO__c, College_Credits_Transferred__c,
            Student_Type__c, Residency__c, Contact__c, Contact__r.MailingStateCode FROM Application__c];
		ApplicationHelper.updateFilters(apps);

		for(Application__c app : apps){
			            if(app.School_College__c == 'Undergraduate'){
                if(app.Is_Transfer_Student__c == 'Yes'){
                    System.assertEquals('Transfer', app.Applicant_Type__c);
                }else if (app.Is_Applying_For_PSEO__c == 'Yes') {
                     System.assertEquals('PSEO', app.Applicant_Type__c);
                }else {
                    System.assertEquals('Freshman', app.Applicant_Type__c);
                }
            }else if(app.School_College__c == 'Adult Undergraduate'){
                if(app.College_Credits_Transferred__c != null){
                    if (app.College_Credits_Transferred__c == '1-30 transfer credits') {
                       System.assertEquals('Transfer', app.Applicant_Type__c);
                        System.assertEquals('Adult Transfer: Less than 30 Credits', app.Student_Type__c);
                    }
                    else if (app.College_Credits_Transferred__c == 'More than 30 transfer credits') {
                         System.assertEquals('Transfer', app.Applicant_Type__c);
                       System.assertEquals('Adult Transfer: More than 30 Credits', app.Student_Type__c);
                    }
                    else {
                        System.assertEquals('Freshman', app.Applicant_Type__c);
                        System.assertEquals('Adult', app.Student_Type__c);
                    }
                }
            }else if(app.School_College__c == 'Graduate'){
                System.assertEquals('Graduate', app.Applicant_Type__c);
            }

			if(app.Contact__r.MailingStateCode == 'MN'){
                System.assertEquals('Resident',  app.Residency__c);
            }else{
                 System.assertEquals('Non-Resident',  app.Residency__c);
            }
		}

	}

	static testMethod void testUpdateApplicantType(){
		for(Application__c app : [SELECT Id, School_College__c, Is_Transfer_Student__c, Applicant_Type__c,
            Is_Applying_For_PSEO__c, College_Credits_Transferred__c,
            Student_Type__c, Residency__c, Contact__c, Contact__r.MailingStateCode FROM Application__c]){
			
			ApplicationHelper.updateApplicantType(app);

			if(app.School_College__c == 'Undergraduate'){
                if(app.Is_Transfer_Student__c == 'Yes'){
                    System.assertEquals('Transfer', app.Applicant_Type__c);
                }else if (app.Is_Applying_For_PSEO__c == 'Yes') {
                     System.assertEquals('PSEO', app.Applicant_Type__c);
                }else {
                    System.assertEquals('Freshman', app.Applicant_Type__c);
                }
            }else if(app.School_College__c == 'Adult Undergraduate'){
                if(app.College_Credits_Transferred__c != null){
                    if (app.College_Credits_Transferred__c == '1-30 transfer credits') {
                       System.assertEquals('Transfer', app.Applicant_Type__c);
                        System.assertEquals('Adult Transfer: Less than 30 Credits', app.Student_Type__c);
                    }
                    else if (app.College_Credits_Transferred__c == 'More than 30 transfer credits') {
                         System.assertEquals('Transfer', app.Applicant_Type__c);
                       System.assertEquals('Adult Transfer: More than 30 Credits', app.Student_Type__c);
                    }
                    else {
                        System.assertEquals('Freshman', app.Applicant_Type__c);
                        System.assertEquals('Adult', app.Student_Type__c);
                    }
                }
            }else if(app.School_College__c == 'Graduate'){
                System.assertEquals('Graduate', app.Applicant_Type__c);
            }

		}
	}

	static testMethod void testUpdateResidency(){
		for(Application__c app : [SELECT Id, School_College__c, Is_Transfer_Student__c, Applicant_Type__c,
            Is_Applying_For_PSEO__c, College_Credits_Transferred__c,
            Student_Type__c, Residency__c, Contact__c, Contact__r.MailingStateCode FROM Application__c]){
			ApplicationHelper.updateResidency(app, app.Contact__r);

			 if(app.Contact__r.MailingStateCode == 'MN'){
                System.assertEquals('Resident',  app.Residency__c);
            }else{
                 System.assertEquals('Non-Resident',  app.Residency__c);
            }

		}
	}
}