src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>IF( 
Activate_Application_Date__c &lt;=  TODAY() &amp;&amp; End_Application_Date__c  &gt;=  TODAY(), &quot;Active&quot;, &quot;Inactive&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Active&quot; if applications for this term are currently open. &quot;Inactive&quot; otherwise.</inlineHelpText>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <inlineHelpText>Residency type this record applies to (applies to all if blank)</inlineHelpText>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this record applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this record applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <inlineHelpText>Start date for this term.</inlineHelpText>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship of the applicant.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident Alien</fullName>
                </value>
                <value>
                    <fullName>Not Citizen or Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Domestic</fullName>
                    <isActive>false</isActive>
                    <label>Domestic</label>
                </value>
                <value>
                    <fullName>International</fullName>
                    <isActive>false</isActive>
                    <label>International</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Type of delivery the student prefers.</description>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program_Code__c</fullName>
        <formula>Intended_Program__r.Program_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Intended Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Term_of_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Term of Entry</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <description>Application control for a specific school</description>
        <inlineHelpText>Application control for a specific school</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name_on_Application__c</fullName>
        <inlineHelpText>Name of the program to display on the application</inlineHelpText>
        <label>Program Name on Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <inlineHelpText>Residency type this program applies to (applies to all if blank)</inlineHelpText>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
        <isActive>false</isActive>
        <label>Seminary</label>
    </customValue>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
        <isActive>false</isActive>
        <label>Adult Undergraduate</label>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident Alien</fullName>
    </customValue>
    <customValue>
        <fullName>Not Citizen or Permanent Resident</fullName>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Delivery_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Face-to-Face</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Blended</fullName>
    </customValue>
    <customValue>
        <fullName>SemPM</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>On-Campus</fullName>
        <isActive>false</isActive>
        <label>On-Campus</label>
    </customValue>
    <customValue>
        <fullName>Evenings and Weekends</fullName>
        <isActive>false</isActive>
        <label>Evenings and Weekends</label>
    </customValue>
    <description>Types that a program can be delivered.</description>
    <masterLabel>Delivery Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Residency_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US-Resident</fullName>
    </customValue>
    <description>Residency types for admissions applications.</description>
    <masterLabel>Residency Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: Less than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: More than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
        <isActive>false</isActive>
        <label>Freshman</label>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
        <isActive>false</isActive>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
        <isActive>false</isActive>
        <label>PSEO</label>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/ApplicationQueryCache.cls
/*
 * 
 * 
 * test - ApplicationQueryCacheTest
 * 
 */ 
public with sharing class ApplicationQueryCache {

    public static Map<Id, User> userCache = new Map<Id, User>();
    public static Map<Id, Application__c> applicationCache = new Map<Id, Application__c>();

	public static User getUser(Id userId) {
        User u = userCache.get(userId);
        if (u == null) {
            u = [SELECT Id, ContactId FROM User WHERE Id = :userId];
            userCache.put(userId, u);
        }
        return u;
	}

    public static Id getContactId(Id userId) {
        Id theContactId = null;
        User u = getUser(userId);
        if (u != null) {
            theContactId = u.ContactId;
        }
        return theContactId;
    }

    public static Application__c getApplication(Id applicationId) {
        Application__c app = applicationCache.get(applicationId);
        if (app == null) {
            app = [
                SELECT 
                    Id, 
                    Contact__c,
                    Intended_Program__c, 
                    Intended_Program__r.Program_Name_on_Application__c, 
                    Intended_Program__r.Name, 
                    Intended_Program_Code__c, 
                    Intended_Term_of_Entry__c,
                    Intended_Term_of_Entry__r.Name, 
                    Intended_Term_of_Entry__r.Term_Start_Date__c, 
                    Applicant_Type__c, 
                    Citizenship__c, 
                    Delivery_Type__c, 
                    Student_Type__c, 
                    Residency__c, 
                    Application_Status__c, 
                    School_College__c, 
                    Application_Control__c 
                FROM 
                    Application__c 
                WHERE 
                    Id = :applicationId
            ];
            applicationCache.put(applicationId, app);
        }
        return app;
    }

    public static Application__c getApplication(Id applicationId, Id contactId) {
        Application__c app = getApplication(applicationId);
        if (app.Contact__c != contactId) {
            app = null;
        }
        return app;
    }

 
}