src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term open.</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term close.</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Admissions_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Admissions Document</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>AD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Cancel_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Cancel&quot; button shows-up for.</inlineHelpText>
        <label>Allow Cancel From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Submit_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Submit&quot; button shows-up for.</inlineHelpText>
        <label>Allow Submit From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Withdraw_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Withdraw&quot; button shows-up for.</inlineHelpText>
        <label>Allow Withdraw From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Start_Status__c</fullName>
        <inlineHelpText>Application status that new applications are set to.</inlineHelpText>
        <label>Application Start Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Cancel&quot; button sets an application to</inlineHelpText>
        <label>Cancel Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this is the default Application Control when no URL Parameter is specified</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Submit&quot; button sets an application to</inlineHelpText>
        <label>Submit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <inlineHelpText>Text to be included at the end of a link to reference this Application Control. Format is &quot;?at=[URL_PARAMETER]&quot;</inlineHelpText>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Withdraw_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Withdraw&quot; button sets an application to</inlineHelpText>
        <label>Withdraw Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Program)</relationshipLabel>
        <relationshipName>CaseProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intended_Program_Term__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <inlineHelpText>Academic Term that this record is associated with.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Intended Program Terms</relationshipLabel>
        <relationshipName>Academic_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to open</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date that this record causes the application to close</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <label>Intended Program Term</label>
    <nameField>
        <label>Intended Program Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intended Program Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The academic term a prospect is interested in.</description>
        <inlineHelpText>The academic term a prospect is interested in.</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/classes/OpportunityHelperTest.cls
/**
* Created by Luke Vang ( Contractor ) on 2019-02-28.
*/
@isTest
public class OpportunityHelperTest {

    @TestSetup
    static void testSetup(){

       //create trigger handler record
         hed__Trigger_Handler__c handler = new hed__Trigger_Handler__c();
         handler.Name = 'TDTM_Opportunity_Create_Case_On_Confirm';
         handler.hed__Class__c = 'TDTM_Opportunity_Create_Case_On_Confirm';
         handler.hed__Object__c = 'Opportunity';
         handler.hed__Trigger_Action__c = 'AfterUpdate';
         handler.hed__Active__c = true;
         handler.hed__Load_Order__c = 1;

         insert handler;

        handler = new hed__Trigger_Handler__c();
        handler.Name = 'TDTM_Documents_Missing_All';
        handler.hed__Class__c = 'TDTM_Documents_Missing_All';
        handler.hed__Object__c = 'Opportunity';
        handler.hed__Trigger_Action__c = 'BeforeUpdate';
        handler.hed__Active__c = true;
        handler.hed__Load_Order__c = 2;

        insert handler;

        handler = new hed__Trigger_Handler__c();
        handler.Name = 'TDTM_Documents_Missing_AD';
        handler.hed__Class__c = 'TDTM_Documents_Missing_AD';
        handler.hed__Object__c = 'Test_Score__c';
        handler.hed__Trigger_Action__c = 'AfterInsert;AfterUpdate;AfterDelete';
        handler.hed__Active__c = true;
        handler.hed__Load_Order__c = 1;

        insert handler;

        handler = new hed__Trigger_Handler__c();
        handler.Name = 'TDTM_Application_Internal_Requirements';
        handler.hed__Class__c = 'TDTM_Application_Internal_Requirements';
        handler.hed__Object__c = 'Application__c';
        handler.hed__Trigger_Action__c = 'AfterUpdate';
        handler.hed__Active__c = true;
        handler.hed__Load_Order__c = 2;

        insert handler;


        //create application data
         Application_Control__c appControl = new Application_Control__c(
            Application_Start_Status__c=Application_Control__c.Application_Start_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Active__c=true,
            Allow_Cancel_From__c=Application_Control__c.Allow_Cancel_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Withdraw_From__c=Application_Control__c.Allow_Withdraw_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Submit_From__c=Application_Control__c.Allow_Submit_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Cancel_Status__c=Application_Control__c.Cancel_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Default__c=true,
            URL_Parameter__c ='st',
            Submit_Status__c=Application_Control__c.Submit_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Withdraw_Status__c=Application_Control__c.Withdraw_Status__c.getDescribe().getPicklistValues()[0].getValue()
        );
        insert appControl;

        Academic_Term__c at = new Academic_Term__c(Name = 'test', Activate_Application_Date__c = Date.TODAY().addDays(-2), End_Application_Date__c = Date.TODAY().addDays(2));
        insert at;

        Program__c p1 = new Program__c(Name = 'test1', Number_of_Applications_Limit__c = 'One Application', Applicant_Type__c = Program__c.Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p2 = new Program__c(Name = 'test2', Number_of_Applications_Limit__c = 'One Application Per Term', Hide_Applicant_Type__c = Program__c.Hide_Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p3 = new Program__c(Name = 'test3', Number_of_Applications_Limit__c = 'One Application Per Program', Hide_Student_Type__c = Program__c.Hide_Student_Type__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p4 = new Program__c(Name = 'test4', Hide_Citizenship__c = Program__c.Hide_Citizenship__c.getDescribe().getPicklistValues()[0].getValue());
        Program__c p5 = new Program__c(Name = 'test5');
        insert new List<Program__c>{p1, p2, p3, p4, p5};

        Intended_Program_Term__c ipt = new Intended_Program_Term__c(Academic_Term__c = at.Id, Activate_Application_Date__c = Date.TODAY().addDays(-1), End_Application_Date__c = Date.TODAY().addDays(-1), Applicant_Type__c = Intended_Program_Term__c.Applicant_Type__c.getDescribe().getPicklistValues()[0].getValue());
        insert ipt;

        Account acc = new Account(Name='NewAcc');
        insert acc;

        Contact student = new Contact(LastName='TestLast', FirstName = 'TestFirst', Email = 'TestContact@example.bethel.com');
        insert student;

        Application__c app = new Application__c(
            Contact__c=student.Id,
            School_College__c = 'Graduate',
            Application_Status__c=Application__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Intended_Program__c =  p3.Id,
            Intended_Term_of_Entry__c = at.Id);
        insert app;

        Opportunity opp = new Opportunity(Name='Test Opp', Application__c = app.Id, Academic_Program__c = p3.Id, Academic_Term__c = at.Id, School_College__c = 'Graduate',
            Contact__c = app.Contact__c, StageName = 'Applied', Stage_Detail__c = 'App Submitted', CloseDate = Date.today());
        insert opp;

        Test_Score__c ts = new Test_Score__c(Test_Type__c='ACT', Contact__c=student.Id);
        insert ts;

        Admissions_Document__c ad = new Admissions_Document__c(Contact__c=student.Id);
        insert ad;

        Education_History__c eh = new Education_History__c(Contact__c=student.Id);
        insert eh;

    }

    static testMethod void testCreateCaseOnConfirmedPROVISIONALTYPE(){
        Opportunity opp = [SELECT id, StageName, School_College__c, Admission_Type__c  FROM Opportunity];
        System.assertEquals(0, [SELECT COUNT() FROM Case WHERE Subject LIKE 'Provisional Acceptance%']);
        opp.StageName = 'Applied';
        opp.Stage_Detail__c = 'App Completed';
        update opp;
        opp.StageName = 'Accepted';
        opp.Stage_Detail__c = 'Accepted';
        update opp;
        Test.startTest();
        opp.StageName = 'Confirmed';
        opp.Stage_Detail__c = 'Registered';
        opp.Admission_Type__c = 'Provisional';
        opp.School_College__c = 'Graduate';
        update opp;
        Test.stopTest();
        System.assertEquals(1, [SELECT COUNT() FROM Case WHERE Subject LIKE 'Provisional Acceptance%']);
    }

    static testMethod void testCreateCaseOnConfirmedCONDITIONALTYPE(){
        Opportunity opp = [SELECT id, StageName, School_College__c, Admission_Type__c  FROM Opportunity];
        System.assertEquals(0, [SELECT COUNT() FROM Case WHERE Subject LIKE 'Conditional Acceptance%']);
        opp.StageName = 'Applied';
        opp.Stage_Detail__c = 'App Completed';
        update opp;
        opp.StageName = 'Accepted';
        opp.Stage_Detail__c = 'Accepted';
        update opp;
        Test.startTest();
        opp.StageName = 'Confirmed';
        opp.Stage_Detail__c = 'Registered';
        opp.Admission_Type__c = 'Conditional';
        opp.School_College__c = 'Graduate';
        update opp;
        Test.stopTest();
        System.debug([SELECT COUNT() FROM Case]);
        System.assertEquals(1, [SELECT COUNT() FROM Case WHERE Subject LIKE 'Conditional Acceptance%']);
    }

    static testMethod void testCreateCaseOnConfirmedPROVISIONALANDCONDITIONALTYPE(){
        Opportunity opp = [SELECT id, StageName, School_College__c, Admission_Type__c  FROM Opportunity];
        System.assertEquals(0, [SELECT COUNT() FROM Case WHERE  (Subject LIKE 'Conditional Acceptance%' OR Subject LIKE 'Provisional Acceptance%')]);
        opp.StageName = 'Applied';
        opp.Stage_Detail__c = 'App Completed';
        update opp;
        opp.StageName = 'Accepted';
        opp.Stage_Detail__c = 'Accepted';
        update opp;
        Test.startTest();
        opp.StageName = 'Confirmed';
        opp.Stage_Detail__c = 'Registered';
        opp.Admission_Type__c = 'Conditional and Provisional';
        opp.School_College__c = 'Graduate';
        update opp;
        Test.stopTest();
        System.assertEquals(2, [SELECT COUNT() FROM Case WHERE (Subject LIKE 'Conditional Acceptance%' OR Subject LIKE 'Provisional Acceptance%')]);
    }

    static testMethod void getOpportunitiesForApplicationTest() {
        Application__c app = [SELECT Id FROM Application__c];

        List<Opportunity> opps = null;
        Test.startTest();
        opps = OpportunityHelper.getOpportunitiesForApplication(app.Id);
        Test.stopTest();

        System.assert(opps != null);
        System.assertEquals(1, opps.size());
    }

    static testMethod void getOpportunitiesWithCouselorForApplicationTest() {
        Application__c app = [SELECT Id FROM Application__c];

        List<Opportunity> opps = null;
        Test.startTest();
        opps = OpportunityHelper.getOpportunitiesWithCouselorForApplication(app.Id);
        Test.stopTest();

        System.assert(opps != null);
        System.assertEquals(1, opps.size());
    }

    static testMethod void getOpportunitiesForKeysTest() {
        Opportunity opp = [SELECT id, StageName, Stage_Detail__c, School_College__c, Admission_Type__c, Opportunity_Key__c  FROM Opportunity];

        Map<String, Opportunity> opps = null;
        Test.startTest();
        opps = OpportunityHelper.getOpportunitiesForKeys(new Set<String>{opp.Opportunity_Key__c});
        Test.stopTest();

        System.assert(opps != null);
        System.assertEquals(1, opps.size());
        System.assert(opps.get(opp.Opportunity_Key__c) != null);
    }

    static testMethod void updateOpportunityStatusAppCompletedTest(){
        Opportunity opp = [SELECT id, StageName, Stage_Detail__c, School_College__c, Admission_Type__c  FROM Opportunity];
        Application__c app = [SELECT Id FROM Application__c];

        Test.startTest();
        OpportunityHelper.updateOpportunityStatusAppCompleted(app.Id);
        Test.stopTest();

        Opportunity updatedOpp = [SELECT id, StageName, Stage_Detail__c, School_College__c, Admission_Type__c  FROM Opportunity];
        System.assert(updatedOpp != null);
        System.assertEquals('Applied', updatedOpp.StageName);
        System.assertEquals('App Completed', updatedOpp.Stage_Detail__c);

    }

    static testMethod void updateTestScore(){

        Test_Score__c ts = [Select Id, Contact__c from Test_Score__c];

        Test.startTest();
        Test_Score__c ts_conditional = new Test_Score__c(Test_Type__c='ACT', Contact__c=ts.Contact__c, Document_Status__c = 'Conditional');
        insert ts_conditional;

        System.debug('-------------------------------------');
        System.debug(ts);
        System.debug(ts.Contact__c);
        List<Opportunity> opportunities = [SELECT Id, Documents_Missing__c, StageName, Stage_Detail__c, Contact__c FROM Opportunity WHERE StageName = 'Applied' AND Contact__c = :ts.Contact__c];
        System.debug(opportunities);
        System.debug('-------------------------------------');

        ts.Document_Status__c = 'Conditional';

        update ts;

        delete ts;
    }

    static testMethod void updateAdmissionsDocument(){

        Admissions_Document__c ad = [Select Id, Contact__c from Admissions_Document__c];

        Test.startTest();
        Admissions_Document__c ad_conditional = new Admissions_Document__c(Contact__c=ad.Contact__c);
        insert ad_conditional;

        System.debug('-------------------------------------');
        System.debug(ad);
        System.debug(ad.Contact__c);
        List<Opportunity> opportunities = [SELECT Id, Documents_Missing__c, StageName, Stage_Detail__c, Contact__c FROM Opportunity WHERE StageName = 'Applied' AND Contact__c = :ad.Contact__c];
        System.debug(opportunities);
        System.debug('-------------------------------------');

        ad.Status__c = 'Conditional';

        update ad;

        delete ad;
    }

    static testMethod void updateEdHistory(){
        Education_History__c eh = [select Id, Contact__c from Education_History__c];
        Test.startTest();
        Education_History__c eh_conditional = new Education_History__c(Contact__c=eh.Contact__c);
        insert eh_conditional;
        List<Opportunity> opportunities = [SELECT Id, Documents_Missing__c, StageName, Stage_Detail__c, Contact__c FROM Opportunity WHERE StageName = 'Applied' AND Contact__c = :eh.Contact__c];

        eh.Document_Status__c = 'Conditional';

        update eh;

        delete eh;

    }


    static testMethod  void updateApplicationRequirements(){
        Application__c app = [Select Id, GPA_30_Prerequisite__c from Application__c];
        app.Application_Status__c = 'Submitted';
        app.GPA_30_Prerequisite__c = 'Conditional';
        update app;


    }



}