src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>Field from Banner to indicate the Program code; SMAPRLE and SOACURR</description>
        <externalId>true</externalId>
        <label>Program Code</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Program)</relationshipLabel>
        <relationshipName>CaseProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mogli_SMS__Mogli_Number__c</fullName>
        <description>This is the gateway formatted phone number</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the gateway formatted phone number</inlineHelpText>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Mogli_Number__c</fullName>
        <externalId>true</externalId>
        <label>Mogli Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>A checkbox to mark whether or not a Program is active.</description>
        <externalId>true</externalId>
        <inlineHelpText>External code for the program (e.g. SIS ID). This is used for integration with external systems.</inlineHelpText>
        <label>Program Code</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Flow_TransferOwnershipTest.cls
/**
 * Created by bej68982 on 2/26/20.
 */

@IsTest
private class Flow_TransferOwnershipTest {

    @IsTest
    static void testTransferOwnership() {
        //Get User Role
        List<UserRole> roleList = [SELECT Id,Name FROM UserRole WHERE Name LIKE '%CAS%'];
        UserRole r = roleList[0];
        System.debug('BENTEST'+r.Name);

        //Get Profile
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

        //Get Program Record Type
        RecordType recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND Name = 'Academic Program'];

        //Get Users
        List<User> usersList = [SELECT Id FROM User WHERE UserRole.Name LIKE '%CAS%'];
        User testOldUser = usersList[0];
        User testNewUser = usersList[1];

        // Create an Contact
        Contact testContact = new Contact(FirstName='First', LastName='Last', Email='test@test.com', Mogli_SMS__Mogli_Number__c = '+12222222222');
        insert testContact;

        //Create Academic Program Account
        Account testAccount = new Account(Program_Code__c = '123abc', Name = 'Test Program', RecordTypeId = recordType.Id);
        insert testAccount;

        //Create Program
        Program__c testProgram = new Program__c(Program_Code__c = '123abc', Active__c = true, Academic_Program__c = testAccount.Id);
        insert testProgram;

        // Create an Opportunity
        Opportunity testOpportunity = new Opportunity(Contact__c = testContact.Id, OwnerId=testOldUser.Id, StageName='Inquired', Stage_Detail__c = 'App Started', Name = 'Test Opp', CloseDate=System.today(), Academic_Program__c = testProgram.Id);
        insert testOpportunity;

        // Create a Task
        Task testTask = new Task(Status = 'Open', OwnerId=testOldUser.Id, WhatId = testOpportunity.Id);
        insert testTask;

        //Create a Case
        Case testCase = new Case(Status = 'New', OwnerId=testOldUser.Id, Program__c = testAccount.Id);
        insert testCase;

        List<Flow_TransferOwnership.TransferOwnershipRequest> listOfRequests = new List<Flow_TransferOwnership.TransferOwnershipRequest>();

        String oldUserId = String.valueOf(testOldUser.Id);
        String newUserId = String.valueOf(testNewUser.Id);

        //Test Getting Total Sum
        Flow_TransferOwnership.TransferOwnershipRequest request1 = new Flow_TransferOwnership.TransferOwnershipRequest();
        request1.requestType = 'total';
        request1.objectsTypes = 'opportunities;cases;tasks';
        request1.oldOwnerId = oldUserId;
        request1.newOwnerId = newUserId;
        request1.programCodes = '123abc,456def';
        listOfRequests.add(request1);

        //Test Transferring Records
        Flow_TransferOwnership.TransferOwnershipRequest request2 = new Flow_TransferOwnership.TransferOwnershipRequest();
        request2.requestType = 'transfer';
        request2.objectsTypes = 'opportunities;cases;tasks';
        request2.oldOwnerId = oldUserId;
        request2.newOwnerId = newUserId;
        request2.programCodes = '123abc,456def';
        listOfRequests.add(request2);

        Test.startTest();
        Flow_TransferOwnership.TransferOwnership(listOfRequests);
        Test.stopTest();
        List<Opportunity> opps = [SELECT Id FROM Opportunity WHERE OwnerId = :newUserId];
        List<Case> cases = [SELECT Id FROM Case WHERE OwnerId = :newUserId];
        List<Task> tasks = [SELECT Id FROM Task WHERE OwnerId = :newUserId];
        System.debug('BENTEST: Opportunities: '+opps.size()+' - Cases: '+cases.size()+' - Tasks: '+tasks.size());
        System.debug('BENTEST: Opps: '+opps);
        System.debug('BENTEST: Cases: '+cases);
        System.debug('BENTEST: Tasks: '+tasks);
        Integer NumberOfOwnedRecords = opps.size() + cases.size() + tasks.size();
        System.assert(NumberOfOwnedRecords > 3);
    }
}