src/objects/Admissions_Document__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Applicant on Application</description>
        <inlineHelpText>Applicant on Application</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Admissions Document</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>AD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education_History__c.object
<CustomObject>
    <description>Represents the education history for a person at an education institution</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for this education history record</description>
        <inlineHelpText>The person for this education history record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Histories</relationshipLabel>
        <relationshipName>Education_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                    <default>true</default>
                    <label>Mandatory</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
                <value>
                    <fullName>Not Received</fullName>
                </value>
                <value>
                    <fullName>Purged</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Education History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lock_Documents_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, apex will skip this Opportunity and not overwrite the Documents Missing field.</description>
        <label>Lock Documents Missing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature__c</fullName>
        <label>Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Documents_Missing_AD.cls
/**
 * Created by ejc84332 on 2019-05-18.
 */

// Test: OpportunityHelperTest

global class TDTM_Documents_Missing_AD extends TDTMVirtualTriggerHandler {


    global override void onAfterInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        List<Id> process_list = new List<Id>();

        for( SObject s : newList) {

            // don't process submitted. Hitting too many SOQL errors because the checklist also runs. It will

            String status = get_status_by_type(s);
            if(status == 'Conditional' || status == 'Provisional' || status == 'Received' || status == 'Mandatory'){
                process_list.add((Id) s.get('Contact__c'));
            }
        }
        if(process_list.size() > 0){
            if (System.isBatch() || System.isFuture()) {
                process_list(process_list);
            }else{
                process_list_future(process_list);
            }
        }
    }

    global override void onAfterDelete(List<SObject> oldList, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        List<Id> process_list = new List<Id>();
        for( SObject s : oldList) {
            String status = get_status_by_type(s);
            if(status == 'Conditional' || status == 'Provisional' || status == 'Received' || status == 'Mandatory'){
                process_list.add((Id) s.get('Contact__c'));
            }
        }
        if(process_list.size() > 0){
            if (System.isBatch() || System.isFuture()) {
                process_list(process_list);
            }else{
                process_list_future(process_list);
            }
        }
    }

    global override void onAfterUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        List<Id> process_list = new List<Id>();
        for( SObject s : newList) {

            String new_status = get_status_by_type(s);
            String old_status = get_status_by_type(oldMap.get(s.Id));


            // did status change?
            // ej: used to do a bunch of compliated logic to find exact change. Most of the time we need to recalculate anyway when it changes,
            // so I simplified. If this is running too often check GitHub history for what it was and then add in "Mandatory" status as well.

            if(new_status != old_status){
                process_list.add((Id) s.get('Contact__c'));
            }
        }
        if(process_list.size() > 0){
            if (System.isBatch() || System.isFuture()) {
                process_list(process_list);
            }else{
                process_list_future(process_list);
            }
        }

    }

    private String get_status_by_type(SObject s){

        if(s.getSObjectType() == Admissions_Document__c.SObjectType) {
            return (String) s.get('Status__c');
        }else if(s.getSObjectType() == Education_History__c.SObjectType || s.getSObjectType() == Test_Score__c.SObjectType) {
            return (String) s.get('Document_Status__c');
        }else if(s.getSObjectType() == Reference__c.SObjectType){
            return (String) s.get('Signature__c');
        }else{
            return '';
        }
    }

    private static void process_list(List<Id> contact_ids){
        List<Opportunity> opportunities = [SELECT Id, Stage_Detail__c FROM Opportunity
        WHERE StageName in ('Applied', 'Accepted', 'Confirmed') AND Lock_Documents_Missing__c = False AND Contact__c IN :contact_ids];
        // This wlll cause TDTM_Documents_Missing_All to run which will update the Documents Missing field.
        update opportunities;
    }


    @future
    private static void process_list_future(List<Id> contact_ids){

        List<Opportunity> opportunities = [SELECT Id, Stage_Detail__c FROM Opportunity
        WHERE StageName in ('Applied', 'Accepted', 'Confirmed') AND Lock_Documents_Missing__c = False AND Contact__c IN :contact_ids];
        // This wlll cause TDTM_Documents_Missing_All to run which will update the Documents Missing field.
        update opportunities;
    }

}