src/objects/Admissions_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Applicant on Application</description>
        <inlineHelpText>Applicant on Application</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Admissions_Document_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Admissions Document</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>AD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Education_History__c.object
<CustomObject>
    <description>Represents the education history for a person at an education institution</description>
    <fields>
        <fullName>Best_School_Name__c</fullName>
        <formula>IF( NOT(ISBLANK( Educational_Institution__c )), Educational_Institution__r.Name ,  School_Not_Found_Name__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Best School Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for this education history record</description>
        <inlineHelpText>The person for this education history record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Histories</relationshipLabel>
        <relationshipName>Education_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                    <default>true</default>
                    <label>Mandatory</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
                <value>
                    <fullName>Not Received</fullName>
                </value>
                <value>
                    <fullName>Purged</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of education institution or school for this education history</description>
        <inlineHelpText>The type of education institution or school for this education history</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>College</fullName>
                </value>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Church</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Education History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Documents_Missing__c</fullName>
        <inlineHelpText>Conditional items that are needed.</inlineHelpText>
        <label>Documents Missing</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lock_Documents_Missing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, apex will skip this Opportunity and not overwrite the Documents Missing field.</description>
        <label>Lock Documents Missing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Question for a requirement item.</description>
    <fields>
        <fullName>Label__c</fullName>
        <inlineHelpText>Label for this question that is displayed to the applicant</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Reference</fullName>
        <active>true</active>
        <label>Reference</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question_Response__c.object
<CustomObject>
    <description>Junction object between requirement response and question.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>Used for the table on Opportunity to edit the responses</description>
        <formula>Question__r.Label__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question that this response is for.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000000}</displayFormat>
        <label>Question Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Doctor of Ministry</fullName>
                </value>
                <value>
                    <fullName>Ministry</fullName>
                </value>
                <value>
                    <fullName>Pastoral</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Spiritual</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Vocational</fullName>
                </value>
                <value>
                    <fullName>Nursing Professional</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Church</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <recordTypes>
        <fullName>PSEO</fullName>
        <active>true</active>
        <label>PSEO</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Admissions_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Admissions Document associated with this requirement upload</description>
        <label>Admissions Document</label>
        <referenceTo>Admissions_Document__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application this response is for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Type__c</fullName>
        <description>The Test type name. This should match the record type.</description>
        <inlineHelpText>The test type</inlineHelpText>
        <label>Test Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Test_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Test_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>GRE</fullName>
    </customValue>
    <customValue>
        <fullName>MAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>TOEFL</fullName>
    </customValue>
    <customValue>
        <fullName>PSAT</fullName>
    </customValue>
    <customValue>
        <fullName>CLT</fullName>
    </customValue>
    <customValue>
        <fullName>IELTS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PTE</fullName>
    </customValue>
    <customValue>
        <fullName>Accuplacer</fullName>
    </customValue>
    <customValue>
        <fullName>ACT or SAT official score</fullName>
    </customValue>
    <customValue>
        <fullName>GMAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT2</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>LSAT</fullName>
    </customValue>
    <customValue>
        <fullName>MAT or GRE</fullName>
    </customValue>
    <customValue>
        <fullName>PreACT</fullName>
    </customValue>
    <description>This is the list of test types which is used when recording test scores</description>
    <masterLabel>Test Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TDTM_Documents_Missing_All.cls
/**
 * Created by ejc84332 on 2019-05-18.
 */


// Test: OpportunityHelperTest

global class TDTM_Documents_Missing_All extends TDTMVirtualTriggerHandler {



    global override void onBeforeUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        List<Opportunity> opps = (List<Opportunity>)newList;

        List<Id> contact_ids = new List<Id>();
        List<Id> app_ids = new List<Id>();
        List<Opportunity> process_opps = new List<Opportunity>();

        for( Opportunity o : opps){
            if( (o.StageName == 'Applied'|| o.StageName == 'Accepted' || o.StageName == 'Confirmed' ) && o.Lock_Documents_Missing__c == False){
                contact_ids.add(o.Contact__c);
                app_ids.add(o.Application__c);
                process_opps.add(o);

            }
        }

        // exit if there are no Opps that fit the Stage criteria.
        if(process_opps.size() == 0){
            return;
        }

        List<Test_Score__c> test_scores = [Select Id, Document_Status__c, Test_Type__c, Contact__c from Test_Score__c
                                            where Document_Status__c in ('Conditional', 'Provisional', 'Mandatory', '') and Contact__c in :contact_ids];

        List<Admissions_Document__c> admissions_documents = [Select Id, Status__c, Type__c, Contact__c from Admissions_Document__c
                                                                 where Status__c in ('Conditional', 'Provisional', 'Mandatory', '') and Contact__c in :contact_ids];

        List<Education_History__c> ed_histories = [Select Id, Document_Status__c, Best_School_Name__c, Contact__c from Education_History__c
                                                    where Document_Status__c in ('Conditional', 'Provisional', 'Mandatory', '') and Contact__c in :contact_ids];

        List<Question_Response__c> internal = [
                SELECT Id, Question__r.Name, Question_Label__c, ValueText__c, IsComplete__c, Requirement_Response__r.Application__c
                from Question_Response__c
                where IsShown__c = TRUE
                and ValueText__c in ('Conditional', 'Provisional')
                and Requirement_Response__c in (SELECT Id from Requirement_Response__c where Requirement_Item__r.Name like '%Prerequisites%')
                and (NOT Question__r.Name LIKE '%GPA%')
                AND (NOT Question__r.Name LIKE '%Degree%')
         ];

//        List<Reference__c> refs = [ SELECT Id, Type__c from Reference__c where Signature__c = 'Conditional' or Signature__c = 'conditional' and Req];


        // GET APP IDS AND FILTER BY THAT?
        List<Requirement_Response__c> rrs = [Select Id, Application__c, Requirement_Item__r.Label__c from Requirement_Response__c where Reference__r.Signature__c in ('Conditional', 'conditional', 'Provisional', 'provisional')
            and Requirement_Item__r.Name like '%Reference' and Application__c in :app_ids ];

        for( Opportunity o : process_opps){

            Boolean csg_opp = o.School_College__c != 'Undergraduate';
            Boolean undergrad_opp = !csg_opp;

            List<String> lines = new List<String>();

            for (Test_Score__c ts : test_scores){
                if(ts.Contact__c == o.Contact__c){

                    Boolean cond_or_prov = ts.Document_Status__c == 'Conditional' || ts.Document_Status__c == 'Provisional';
                    if(undergrad_opp){
                        lines.add('- ' + ts.Test_Type__c + ' test score');
                    }else if(csg_opp && cond_or_prov){
                        lines.add('- ' + ts.Test_Type__c + ' test score');
                    }
                }
            }

            for (Admissions_Document__c ad : admissions_documents){
                if(ad.Contact__c == o.Contact__c){

                    Boolean cond_or_prov = ad.Status__c == 'Conditional' || ad.Status__c == 'Provisional';
                    if(undergrad_opp && (o.Student_Type__c == 'PSEO' || o.Is_International__c)){
                        lines.add('- ' + ad.Type__c);
                    }else if(csg_opp && cond_or_prov){
                        lines.add('- ' + ad.Type__c);
                    }
                }
            }

            for (Education_History__c eh : ed_histories){
                if(eh.Contact__c == o.Contact__c){

                    Boolean cond_or_prov = eh.Document_Status__c == 'Conditional' || eh.Document_Status__c == 'Provisional';
                    if(undergrad_opp){
                        lines.add('- Transcript: ' + eh.Best_School_Name__c);
                    }else if(csg_opp && cond_or_prov){
                        lines.add('- Transcript: ' + eh.Best_School_Name__c);
                    }
                }
            }

            // only CSG gets references and internal requirements
            if(csg_opp){
                for (Requirement_Response__c rr : rrs){
                    if(rr.Application__c == o.Application__c){
                        lines.add('- ' + rr.Requirement_Item__r.Label__c);
                    }
                }
                for (Question_Response__c i : internal){
                    if( i.Requirement_Response__r.Application__c == o.Application__c ){
                        lines.add('- Prerequisite: ' + i.Question_Label__c);
                    }
                }
            }




            lines.sort();
            String new_documents_missng = String.join(lines, '\n');

            if(o.Documents_Missing__c != new_documents_missng){
                o.Documents_Missing__c = new_documents_missng;
            }

        }

    }

}