src/objects/Admissions_Document__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Applicant on Application</description>
        <inlineHelpText>Applicant on Application</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Admissions Document</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>AD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education_History__c.object
<CustomObject>
    <description>Represents the education history for a person at an education institution</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for this education history record</description>
        <inlineHelpText>The person for this education history record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education Histories</relationshipLabel>
        <relationshipName>Education_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                    <default>true</default>
                    <label>Mandatory</label>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
                <value>
                    <fullName>Not Received</fullName>
                </value>
                <value>
                    <fullName>Purged</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Education History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/hed__Trigger_Handler__c.object
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <fields>
        <fullName>hed__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>hed__Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hed__Object__c</fullName>
        <description>Name of the object this handler should be run for</description>
        <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hed__Trigger_Action__c</fullName>
        <description>Trigger Action in which this module should fire</description>
        <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
        <label>Trigger Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BeforeInsert</fullName>
                </value>
                <value>
                    <fullName>BeforeUpdate</fullName>
                </value>
                <value>
                    <fullName>BeforeDelete</fullName>
                </value>
                <value>
                    <fullName>AfterInsert</fullName>
                </value>
                <value>
                    <fullName>AfterUpdate</fullName>
                </value>
                <value>
                    <fullName>AfterDelete</fullName>
                </value>
                <value>
                    <fullName>AfterUndelete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <recordTypes>
        <fullName>ACT</fullName>
        <active>true</active>
        <description>Record type for an ACT test scores</description>
        <label>ACT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/TDTMOpportunityPreAppTriggerHandlerTest.cls
@isTest
public class TDTMOpportunityPreAppTriggerHandlerTest {
    @TestSetup
    static void testSetup() {
        //create trigger handler record
        hed__Trigger_Handler__c handler = new hed__Trigger_Handler__c();
        handler.Name = 'TDTMOpportunityPreAppliedTriggerHandler';
        handler.hed__Class__c = 'TDTMOpportunityPreAppliedTriggerHandler';
        handler.hed__Object__c = 'Opportunity';
        handler.hed__Trigger_Action__c = 'BeforeInsert';
        handler.hed__Active__c = true;
        handler.hed__Load_Order__c = 1;

        insert handler;

        Contact c = new Contact(LastName='TestLast', FirstName = 'TestFirst', Email = 'TestContact@example.bethel.com', MailingStateCode = 'MN');
        insert c;
    }
    
    static testMethod void onBeforeInsertAdmissionsDocumentTest() {
        Contact c = [Select Id FROM Contact];

        Admissions_Document__c doc = new Admissions_Document__c(Contact__c = c.Id, Status__c = 'Received');
        insert doc;

        Test.startTest();
        Opportunity opp = new Opportunity(Name='Test Opp', Contact__c = c.Id, StageName = 'Inquired', Stage_Detail__c = 'Inquired', CloseDate = Date.today());
        insert opp;
        Test.stopTest();

        Opportunity upOpp = [SELECT Id, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Inquired', upOpp.StageName);
        System.assertEquals('Pre-Applied', upOpp.Stage_Detail__c);

    }

    static testMethod void onBeforeInsertEducationHistoryTest() {
        Contact c = [Select Id FROM Contact];

        Education_History__c history = new Education_History__c(RecordTypeId = Schema.SObjectType.Education_History__c.getRecordTypeInfosByName().get('High School').getRecordTypeId(), Contact__c = c.Id, Document_Status__c = 'Received');
        insert history;

        Test.startTest();
        Opportunity opp = new Opportunity(Name='Test Opp', Contact__c = c.Id, StageName = 'Inquired', Stage_Detail__c = 'Inquired', CloseDate = Date.today());
        insert opp;
        Test.stopTest();

        Opportunity upOpp = [SELECT Id, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Inquired', upOpp.StageName);
        System.assertEquals('Pre-Applied', upOpp.Stage_Detail__c);
    }

    static testMethod void onBeforeInsertTestScoreTest() {
        Contact c = [Select Id FROM Contact];

       Test_Score__c testScore = new Test_Score__c(RecordTypeId = Schema.SObjectType.Test_Score__c.getRecordTypeInfosByName().get('ACT').getRecordTypeId(), Contact__c = c.Id, Document_Status__c = 'Received');
       insert testScore;

        Test.startTest();
        Opportunity opp = new Opportunity(Name='Test Opp', Contact__c = c.Id, StageName = 'Inquired', Stage_Detail__c = 'Inquired', CloseDate = Date.today());
        insert opp;
        Test.stopTest();

        Opportunity upOpp = [SELECT Id, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Inquired', upOpp.StageName);
        System.assertEquals('Pre-Applied', upOpp.Stage_Detail__c);
    }

    static testMethod void onBeforeInsertNoChangeTest() {
        Contact c = [Select Id FROM Contact];

        Test.startTest();
        Opportunity opp = new Opportunity(Name='Test Opp', Contact__c = c.Id, StageName = 'Inquired', Stage_Detail__c = 'Inquired', CloseDate = Date.today());
        insert opp;
        Test.stopTest();

        Opportunity upOpp = [SELECT Id, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Inquired', upOpp.StageName);
        System.assertEquals('Inquired', upOpp.Stage_Detail__c);
    }

    static testMethod void onBeforeInsertNoChange2Test() {
        Contact c = [Select Id FROM Contact];

        Test.startTest();
        Opportunity opp = new Opportunity(Name='Test Opp', Contact__c = c.Id, StageName = 'Inquired', Stage_Detail__c = 'App Started', CloseDate = Date.today());
        insert opp;
        Test.stopTest();

        Opportunity upOpp = [SELECT Id, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('Inquired', upOpp.StageName);
        System.assertEquals('App Started', upOpp.Stage_Detail__c);
    }

}