src/objects/Admissions_Document__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Applicant on Application</description>
        <inlineHelpText>Applicant on Application</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Admissions Documents</relationshipLabel>
        <relationshipName>Admissions_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Admissions_Document_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Admissions Document</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>AD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Admissions_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Admissions Document associated with this requirement upload</description>
        <label>Admissions Document</label>
        <referenceTo>Admissions_Document__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdmissionsDocumentHelper.cls
public with sharing class AdmissionsDocumentHelper {
    public static List<Admissions_Document__c> findAdmissionsDocument(Id contactId, String typeName) {
        List<Admissions_Document__c> docs = [
            Select 
                Id, 
                Type__c, 
                Contact__c, 
                (SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.Title FROM ContentDocumentLinks) 
            FROM 
                Admissions_Document__c 
            WHERE 
                Contact__c = :contactId AND Type__c = :typeName
            ORDER BY 
                LastModifiedDate
        ];
        return  docs;
    }

    public static Admissions_Document__c getAdmissionsDocument(Contact con, Requirement_Response__c response, String typeName) {
        Admissions_Document__c doc = null;
        List<Admissions_Document__c> docs = findAdmissionsDocument(con.Id, typeName);
        if (!docs.isEmpty()) {
            doc = docs[0];
        }
        return doc;
    }

}