src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdrawal_Reason__c</fullName>
        <description>Reason for not coming to Bethel; Data goes into Banner</description>
        <inlineHelpText>Reason for not coming to Bethel</inlineHelpText>
        <label>Withdrawal Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AN - Academic Fit</fullName>
                </value>
                <value>
                    <fullName>RA - Readmit</fullName>
                </value>
                <value>
                    <fullName>AT - Athletics</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Contact Info</fullName>
                </value>
                <value>
                    <fullName>BV - Bad Experience</fullName>
                </value>
                <value>
                    <fullName>CO - Community Fit</fullName>
                </value>
                <value>
                    <fullName>DR - Do Not Recruit</fullName>
                </value>
                <value>
                    <fullName>FA - Financial Aid</fullName>
                </value>
                <value>
                    <fullName>NA - App Not Complete</fullName>
                </value>
                <value>
                    <fullName>NR - No Response</fullName>
                </value>
                <value>
                    <fullName>PR - Personal</fullName>
                </value>
                <value>
                    <fullName>QD - Not Qualified</fullName>
                </value>
                <value>
                    <fullName>SC - STAR contact:not interested</fullName>
                </value>
                <value>
                    <fullName>ST - Switching Term/Prog</fullName>
                </value>
                <value>
                    <fullName>TC - Too close to home</fullName>
                </value>
                <value>
                    <fullName>TF - Too far from home</fullName>
                </value>
                <value>
                    <fullName>TU - High Tuition</fullName>
                </value>
                <value>
                    <fullName>UN - Unknown</fullName>
                </value>
                <value>
                    <fullName>WA - Wrong School/Catalog</fullName>
                </value>
                <value>
                    <fullName>WB - Wrong Bethel</fullName>
                </value>
                <value>
                    <fullName>WL - Waitlist/Not Selected</fullName>
                </value>
                <value>
                    <fullName>TL - Will transfer in later</fullName>
                </value>
                <value>
                    <fullName>SF - Switching to Future Term</fullName>
                </value>
                <value>
                    <fullName>BF - Better fit elsewhere</fullName>
                </value>
                <value>
                    <fullName>CH - Change of Plans</fullName>
                </value>
                <value>
                    <fullName>DF - Deferred to new term</fullName>
                </value>
                <value>
                    <fullName>WY - Wrong grad year</fullName>
                </value>
                <value>
                    <fullName>AC - Acad Dept Contact:not interest</fullName>
                </value>
                <value>
                    <fullName>AR - Admit record created</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Test_TDTM_Opportunity_Stage_Back.cls
/**
 * Created by ejc84332 on 2019-05-04.
 */

@IsTest
private class Test_TDTM_Opportunity_Stage_Back {


    @IsTest
    static void test_opportunity_stages() {

        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Opportunity_Stage_Back', 'Opportunity', 'AfterUpdate', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        Contact c_one = new Contact(FirstName='First', LastName='Last', Email='test@test.com');
        insert c_one;

        Application__c app = new Application__c(Contact__c=c_one.Id, Application_Status__c='Submitted');
        insert app;

        Opportunity opp = new Opportunity(Name='First Last Opp', CloseDate=Date.today(),
                Contact__c=c_one.Id, StageName='Applied', Stage_Detail__c='App Submitted',
                Application__c= app.Id);

        insert opp;
        Test.startTest();
        opp.StageName = 'File Closed';
        opp.Withdrawal_Reason__c = 'PR - Personal';

        update opp;

        app = [SELECT Id, Application_Status__c FROM Application__c WHERE Id=:app.Id];
        System.assert(app.Application_Status__c=='Cancelled');

        opp.StageName = 'Applied';
        opp.Stage_Detail__c = 'App Submitted';
        update opp;

        app = [SELECT Id, Application_Status__c FROM Application__c WHERE Id=:app.Id];
        System.assert(app.Application_Status__c=='Submitted');

        opp.StageName = 'Inquired';
        opp.Stage_Detail__c = 'App Started';
        update opp;

        app = [SELECT Id, Application_Status__c FROM Application__c WHERE Id=:app.Id];
        System.assert(app.Application_Status__c=='Started');

        opp.StageName = 'File Closed';
        opp.Stage_Detail__c = 'Inquired - File Closed';
        opp.Withdrawal_Reason__c = 'PR - Personal';
        update opp;

        app = [SELECT Id, Application_Status__c FROM Application__c WHERE Id=:app.Id];
        System.assert(app.Application_Status__c=='Cancelled');

        opp.StageName = 'Applied';
        opp.Stage_Detail__c = 'App Completed';
        update opp;

        app = [SELECT Id, Application_Status__c FROM Application__c WHERE Id=:app.Id];
        System.assert(app.Application_Status__c=='Completed');


    }

}