src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Type__c</fullName>
        <description>The Test type name. This should match the record type.</description>
        <inlineHelpText>The test type</inlineHelpText>
        <label>Test Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Test_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Test_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>GRE</fullName>
    </customValue>
    <customValue>
        <fullName>MAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>TOEFL</fullName>
    </customValue>
    <customValue>
        <fullName>PSAT</fullName>
    </customValue>
    <customValue>
        <fullName>CLT</fullName>
    </customValue>
    <customValue>
        <fullName>IELTS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PTE</fullName>
    </customValue>
    <customValue>
        <fullName>Accuplacer</fullName>
    </customValue>
    <customValue>
        <fullName>ACT or SAT official score</fullName>
    </customValue>
    <customValue>
        <fullName>GMAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT2</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>LSAT</fullName>
    </customValue>
    <customValue>
        <fullName>MAT or GRE</fullName>
    </customValue>
    <customValue>
        <fullName>PreACT</fullName>
    </customValue>
    <description>This is the list of test types which is used when recording test scores</description>
    <masterLabel>Test Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TDTMTestScoreTriggerHandler.cls
global class TDTMTestScoreTriggerHandler extends TDTMVirtualTriggerHandler {

    global override void onBeforeUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        Map<ID, Schema.RecordTypeInfo> infoMap = Schema.SObjectType.Test_Score__c.getRecordTypeInfosById();
        for (SObject o : newList) {
            Test_Score__c score = (Test_Score__c) o;
            Test_Score__c oldScore = (Test_Score__c) oldMap.get(o.Id);
            String name = infoMap.get(score.RecordTypeId).getName();
            if (score.RecordTypeId != oldScore.RecordTypeId && name != score.Test_Type__c) {
                score.Test_Type__c = name;
            }
            else if (score.Test_Type__c != oldScore.Test_Type__c && name != score.Test_Type__c) {
                if (score.Test_Type__c == null) {
                    score.Test_Type__c = name;
                }
                else {
                    Schema.RecordTypeInfo info = Schema.SObjectType.Test_Score__c.getRecordTypeInfosByName().get(score.Test_Type__c);
                    if (info != null) {
                        score.RecordTypeId = info.getRecordTypeId();
                    }
                }
            }
        }
    }

    global override void onBeforeInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        Map<ID, Schema.RecordTypeInfo> infoMap = Schema.SObjectType.Test_Score__c.getRecordTypeInfosById();
        for (SObject o : newList) {
            Test_Score__c score = (Test_Score__c) o;
            String name = infoMap.get(score.RecordTypeId).getName();
            if (score.Test_Type__c == null) {
                score.Test_Type__c = name;
            }
            else if (score.Test_Type__c != name) {
                Schema.RecordTypeInfo info = Schema.SObjectType.Test_Score__c.getRecordTypeInfosByName().get(score.Test_Type__c);
                if (info != null) {
                    score.RecordTypeId = info.getRecordTypeId();
                }
            }
        }
    }

    global override void onAfterUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        try {
            Set<Id> contactIds = new Set<Id>();
            for (SObject o : newList) {
                Test_Score__c score = (Test_Score__c) o;
                Test_Score__c oldScore = (Test_Score__c) oldMap.get(o.Id);
                if (score.Document_Status__c != null && score.Document_Status__c != 'Mandatory' && score.Document_Status__c != oldScore.Document_Status__c && score.Contact__c != null) {
                    contactIds.add(score.Contact__c);
                }
            }
            if (!contactIds.isEmpty()) {

                List<Application__c> apps = ApplicationHelper.getApplicationsForContacts(contactIds);
                if (!apps.isEmpty()) {
                    ApplicationHelper.checkCompletion(apps);
                }
            }
        }
        catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    global override void onAfterInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        try {
            Set<Id> contactIds = new Set<Id>();
            for (SObject o : newList) {
                Test_Score__c score = (Test_Score__c) o;
                if (score.Document_Status__c != null && score.Document_Status__c != 'Mandatory' && score.Contact__c != null) {
                    contactIds.add(score.Contact__c);
                }
            }
            if (!contactIds.isEmpty()) {

                List<Application__c> apps = ApplicationHelper.getApplicationsForContacts(contactIds);
                if (!apps.isEmpty()) {
                    ApplicationHelper.checkCompletion(apps);
                }
            }
        }
        catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

}