src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>College_Credits_Transferred__c</fullName>
        <description>Applicants response to how many college credits will be transferring</description>
        <inlineHelpText>Applicants response to how many college credits will be transferring</inlineHelpText>
        <label>College Credits Transferred</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No transfer credits</fullName>
                </value>
                <value>
                    <fullName>1-30 transfer credits</fullName>
                </value>
                <value>
                    <fullName>More than 30 transfer credits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Applying_For_PSEO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies if the applicant is applying for Bethel&apos;s PSEO program</description>
        <inlineHelpText>Specifies if the applicant is applying for Bethel&apos;s PSEO program</inlineHelpText>
        <label>Is Applying For PSEO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Transfer_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies if the applicant is a transfer student</description>
        <inlineHelpText>Specifies if the applicant is a transfer student</inlineHelpText>
        <label>Is Transfer Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>When_College_Credits_Earned__c</fullName>
        <description>Specifies when the applicant earned college credits</description>
        <inlineHelpText>Specifies when the applicant earned college credits</inlineHelpText>
        <label>When College Credits Earned</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>During High School (PSEO, AP, CLEP, IB, other)</fullName>
                </value>
                <value>
                    <fullName>After High School graduation</fullName>
                </value>
                <value>
                    <fullName>Both during and after High School</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>Student Type is a based on several values from the application to determine the type of student. BUILD by program, transfer by if they are transfering data, PSEO by the PSEO question on the application, New is default and New Student Previous PSEO will be done manually</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BUILD</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>New Student Previous PSEO</fullName>
                </value>
                <value>
                    <fullName>PSEO</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Pull in the Application Status so the &quot;Send Reminder Email&quot; flow can filter by status.</description>
        <formula>TEXT(Application__r.Application_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application this response is for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Email__c</fullName>
        <label>External Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hashcode__c</fullName>
        <label>Hashcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Reference__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Reference</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
        <isActive>false</isActive>
        <label>Seminary</label>
    </customValue>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
        <isActive>false</isActive>
        <label>Adult Undergraduate</label>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Staged</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Residency_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-US-Resident</fullName>
    </customValue>
    <description>Residency types for admissions applications.</description>
    <masterLabel>Residency Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: Less than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Transfer: More than 30 Credits</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Freshman</fullName>
        <isActive>false</isActive>
        <label>Freshman</label>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
        <isActive>false</isActive>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>PSEO</fullName>
        <isActive>false</isActive>
        <label>PSEO</label>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/ApplicationHelper.cls
/*
 * 
 * Test class - TDTMApplicationTriggerHandlerTest, ApplicationHelperTest
 * 
 * 
 */ 
public inherited sharing class ApplicationHelper {
    
    public final static String ADULT_UNDERGRADUATE_SCHOOL = 'Adult Undergraduate';
    public final static String UNDERGRADUATE_SCHOOL = 'Undergraduate';
    public final static String GRADUATE_SCHOOL = 'Graduate';
    public final static String SEMINARY_SCHOOL = 'Seminary';
    
    public final static String FRESHMAN_TYPE = 'Freshman';
    public final static String GRADUATE_TYPE = 'Graduate';
    public final static String TRANSFER_TYPE = 'Transfer';
    public final static String PSEO_TYPE = 'PSEO';
    public final static String ADULT_TYPE = 'Adult';
    public final static String ADULT_LESS_TYPE = 'Adult Transfer: Less than 30 Credits';
    public final static String ADULT_MORE_TYPE = 'Adult Transfer: More than 30 Credits';
    public final static String UNDERGRADUATE_TRANSFER_TYPE = 'Undergraduate Transfer';
    public final static String DURING_HIGH_SCHOOL = 'During High School (PSEO, AP, CLEP, IB, other)';
    
    public static void updateFilters(List<Application__c> newList) {
        Set<Id> contactIds = new Set<Id>();
        for (Application__c app : newList) {
            contactIds.add(app.Contact__c);
        }
        Map<Id, Contact> contactMap = ContactHelper.getContactMap(contactIds);
        for (Application__c app : newList) {
            Contact c = contactMap.get(app.Contact__c);
            updateApplicantType(app);
            updateResidency(app, c);
        }
    }
    
    public static void updateApplicantType(Application__c app) {
        if (app.School_College__c == UNDERGRADUATE_SCHOOL) {
            if (app.Is_Applying_For_PSEO__c == 'Yes') {
                app.Applicant_Type__c = PSEO_TYPE;
                if (app.Is_Transfer_Student__c == 'Yes' && app.When_College_Credits_Earned__c != DURING_HIGH_SCHOOL) {
                    app.Student_Type__c = UNDERGRADUATE_TRANSFER_TYPE;
                }
                else {
                    app.Student_Type__c = null;
                }
            }
            else if (app.Is_Transfer_Student__c == 'Yes') {
                app.Applicant_Type__c = TRANSFER_TYPE;
                if (app.When_College_Credits_Earned__c != DURING_HIGH_SCHOOL) {
                    app.Student_Type__c = UNDERGRADUATE_TRANSFER_TYPE;
                }
                else {
                    app.Student_Type__c = null;
                }
            }
            else {
                app.Applicant_Type__c = FRESHMAN_TYPE;
                app.Student_Type__c = null;
            }
        }
        else if (app.School_College__c == ADULT_UNDERGRADUATE_SCHOOL) {
            if (app.College_Credits_Transferred__c != null) {
                if (app.College_Credits_Transferred__c == '1-30 transfer credits') {
                    app.Applicant_Type__c = TRANSFER_TYPE;
                    app.Student_Type__c = ADULT_LESS_TYPE;
                }
                else if (app.College_Credits_Transferred__c == 'More than 30 transfer credits') {
                    app.Applicant_Type__c = TRANSFER_TYPE;
                    app.Student_Type__c = ADULT_MORE_TYPE;
                }
                else {
                    app.Applicant_Type__c = FRESHMAN_TYPE;
                    app.Student_Type__c = ADULT_TYPE;
                }
            }
        }
        else if (app.School_College__c == GRADUATE_SCHOOL) {
            app.Applicant_Type__c = GRADUATE_TYPE;
        }
    }
    
  
    public static void updateResidency(Application__c app, Contact c) {
        if (c.MailingStateCode != null && app != null && c != null) {
            if (c.MailingStateCode == 'MN') {
                app.Residency__c = 'Resident';
            }
            else {
                app.Residency__c = 'Non-Resident';
            }
        }
    }
    
    //on submit send reference email will be set to true, which will start process builder flow - Luke Vang
    public static void sendReferenceRemail(Id appId){
        List<Requirement_Response__c> requirementResponses = new List<Requirement_Response__c>();
        for(Requirement_Response__c rr : [SELECT id, External_Email__c, Hashcode__c
                                          FROM Requirement_Response__c 
                                          WHERE Application__c =: appId])
        {
            if(!String.isBlank(rr.External_Email__c)){
                rr.Send_Reference__c = true;
                requirementResponses.add(rr);
            }
        }
        
        update requirementResponses;
    }

    public static void checkCompletion(Id appId) {
        ApplicationChecklist controller = new ApplicationChecklist(new Application__c(Id = appId));
        controller.init();
    }

    public static List<Application__c> getApplicationsForContacts(Set<Id> theIds) {
        List<Application__c> apps = [
            SELECT 
                Id, 
                Contact__c,
                Application_Status__c
            FROM 
                Application__c 
            WHERE 
                Contact__c IN :theIds
        ];
        return apps;
    }

    public static void checkCompletion(List<Application__c> apps) {
        for (Application__c app : apps) {
            if (app.Application_Status__c == 'Submitted') {
                checkCompletion(app.Id);
                break;
            }
        }
    }

/*
    public static void checkCompletionBatch(List<Application__c> apps) {
        List<Application_Queue__c> items = new List<Application_Queue__c>();
        Boolean hasRun = false;
        for (Application__c app : apps) {
            if (app.Application_Status__c == 'Submitted') {
                if (hasRun) {
                    items.add(new Application_Queue__c(Application__c = app.Id, Process_Type = 'Completion Check'))
                }
                else {
                    checkCompletion(app.Id);
                    hasRun = true;
                }
            }
        }
        if (!items.isEmpty()) {
            insert items;
            AsyncApexJob job = [SELECT Id, ApexClassId, Id, JobItemsProcessed, JobType, LastProcessed, LastProcessedOffset, MethodName, NumberOfErrors, ParentJobId, Status, TotalJobItems from AsyncApexJob where ApexClassId IN (Select Id from ApexClass where Name = 'ClassName1', 'ClassName2', 'Etc')
        }
    }
    */

    public static String getMessageForDuplicateApplicationForTerm(Application__c currentApp, Application__c duplicateApp) {
        String message = 'You already have an application for this term. If it has been closed and you would like it opened, please contact Admissions.';
        if (currentApp.School_College__c == 'Undergraduate') {
            message = Label.Duplicate_Application_For_Term_Error_CAS;
        }
        else if (currentApp.School_College__c == 'Graduate') {
            message = Label.Duplicate_Application_For_Term_Error_GS;
        }
        else if (currentApp.School_College__c == 'Seminary') {
            message = Label.Duplicate_Application_For_Term_Error_SEM;
        }
        else if (currentApp.School_College__c == 'Adult Undergraduate') {
            message = Label.Duplicate_Application_For_Term_Error_Adult_Undergrad;
        }
        if (duplicateApp != null) {
            List<Opportunity> opps = OpportunityHelper.getOpportunitiesWithCouselorForApplication(duplicateApp.Id);
            if (!opps.isEmpty()) {
                String profileName = opps[0].Owner.Profile.Name;
                if (profileName != null && profileName.startsWith('Admissions')) {
                    String substring = String.format(Label.Duplicate_Application_For_Term_Error_Couselor_Substring, new List<String>{opps[0].Owner.Name, opps[0].Owner.Email});
                    message = String.format(message, new List<String>{substring});
                }
            }
        }
        return message;
    }

}