src/objects/Application_Settings__mdt.object
<CustomObject>
    <description>This custom meta data type holds configurable settings around the applications created by Endeveran.</description>
    <fields>
        <fullName>AuraId__c</fullName>
        <description>unique aura id for each application</description>
        <label>AuraId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Avatar_Abr__c</fullName>
        <description>2 text abbr for lighting component/application</description>
        <label>Avatar Abr</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <description>name of component related to application, enter just the main container component</description>
        <inlineHelpText>c:name_of_component</inlineHelpText>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of lightning component/application</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Icon_Name__c</fullName>
        <description>Salesforce lightning design system icon name associated with application. Look at the custom icons here https://www.lightningdesignsystem.com/icons/#site-main-content, 
example custom27</description>
        <inlineHelpText>enter custom icon as custom-# ( custom-27 )</inlineHelpText>
        <label>Icon Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Setting</label>
    <pluralLabel>Application Settings</pluralLabel>
</CustomObject>

src/classes/ApplicationSelectionController.cls
public class ApplicationSelectionController {
    
    /*
* 
* getApps
* 
* returns a list of available applications
* to the app selection component
* 
*/ 
    @AuraEnabled
    public static List<Application_Settings__mdt> getApps(){
        return [SELECT  MasterLabel, Avatar_Abr__c, Description__c, Icon_Name__c, Component_Name__c, AuraId__c
                FROM Application_Settings__mdt 
                WHERE DeveloperName != 'General_Settings' ORDER BY MasterLabel ASC];
    }
}