src/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Response__c.object
<CustomObject>
    <description>Junction object between requirement response and question.</description>
    <fields>
        <fullName>IsComplete__c</fullName>
        <formula>IsPopulated__c == true || IsShown__c == false || IsRequired__c == false</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsComplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsShown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsShown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>Used for the table on Opportunity to edit the responses</description>
        <formula>Question__r.Label__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement_Response__c</fullName>
        <description>Requirement response this question response is for.</description>
        <label>Requirement Response</label>
        <referenceTo>Requirement_Response__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValueText__c</fullName>
        <description>Text value for this response.</description>
        <label>Value Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000000}</displayFormat>
        <label>Question Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application this response is for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requirement_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item this response is for.</description>
        <label>Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InternalChecklistRequirements.cls
/**
 * Created by ejc84332 on 2019-05-07.
 * Test is: OpportunityHelperTest.lightningWebComponentsTest
 */

public with sharing class InternalChecklistRequirements {
    @AuraEnabled(Cacheable=true)
    public static List<Question_Response__c> getInternalQuestions(String applicationID){
        return [

                SELECT Id, Question_Label__c, ValueText__c, IsComplete__c from Question_Response__c where IsShown__c = TRUE and Requirement_Response__c in (

                        SELECT Id from Requirement_Response__c where Application__c=:applicationID and Requirement_Item__r.Name like '%Prerequisites%'

                )

        ];
    }
}