src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Program)</relationshipLabel>
        <relationshipName>CaseProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected value is not a valid Program.</errorMessage>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities (Academic Program)</relationshipLabel>
        <relationshipName>Opportunities_Academic_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Admission_Type__c</fullName>
        <label>Admission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Regular</fullName>
                    <default>true</default>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
                <value>
                    <fullName>Conditional and Provisional</fullName>
                </value>
                <value>
                    <fullName>Special</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Application associated with this Opportunity</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EDA_Program_Account_Id__c</fullName>
        <description>Used in some Automations to help tie the Opportunity to EDA fields.</description>
        <formula>Academic_Program__r.Academic_Program__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EDA Program Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Key__c</fullName>
        <description>A unique external ID text field which determines whether an Interaction will create a new Opportunity or edit an existing Opportunity. Built using the Contact’s 18-digit ID, Career, Term’s 15-digit ID, and Recruitment/Academic Program’s 15-digit ID (if applicable) to ensure uniqueness and support of both a central and decentral recruitment process. Set by the Interactions Processor.</description>
        <externalId>true</externalId>
        <label>Opportunity Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <description>School / College in which the student is interested</description>
        <inlineHelpText>School / College in which the student is interested</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage_Value__c</fullName>
        <description>Calculates a numerical value to more easily compare status</description>
        <formula>CASE( TEXT(Stage_Detail__c),
&apos;Prospect&apos;, 5,
&apos;Inquired&apos;, 10,
&apos;Pre-Applied&apos;, 15,
&apos;App Started&apos;, 20,
&apos;App Submitted&apos;, 25,
&apos;App Completed&apos;, 30,
&apos;Wait Listed&apos;, 35,
&apos;Accepted&apos;, 40,
&apos;Fee Paid&apos;, 45,
&apos;Fee Waived&apos;, 45,
&apos;Registered&apos;, 50,
&apos;Enrolled&apos;, 55,
-1
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College this program is a part of</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/OpportunityHelper.cls
/**
* Created by Luke Vang ( Contractor ) on 2019-02-28.
*
* Logic taken from ApplicationHelper in previous full sandbox
*
* Test class - OpportunityHelperTest
*
*/
public class OpportunityHelper {

    public static Id SSR_ADVISING_QUEUE_ID = [SELECT id FROM Group WHERE Name =: 'SSR - Advising'].Id;
    
    public final static String CONFIRMED_STATUS = 'Confirmed';
    public final static String PROVISIONAL_TYPE = 'Provisional';
    public final static String CONDITIONAL_TYPE = 'Conditional';
    public final static String CONDITIONAL_AND_PROVISIONAL_TYPE = 'Conditional and Provisional';
    static Id studentSuccessCaseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSR - Student Success Case').getRecordTypeId();
    
    public static Boolean createdCases = false;
    
    public static void createCaseOnConfirmed(List<Opportunity> newList, Map<Id, Opportunity> oldMap) {
        List<Case> newCases = new List<Case>();
        Set<Id> contactIds = new Set<Id>();
        for (Opportunity opp : newList) {
            Opportunity oldOpp = oldMap.get(opp.Id);
            if (oldOpp != null && opp.StageName == CONFIRMED_STATUS && oldOpp.StageName != CONFIRMED_STATUS && opp.School_College__c != 'Undergraduate') {
                if (opp.Admission_Type__c == PROVISIONAL_TYPE) {
                    newCases.add(createProvisionalCase(opp));
                    contactIds.add(opp.Contact__c);
                }
                else if (opp.Admission_Type__c == CONDITIONAL_TYPE) {
                    newCases.add(createConditionalCase(opp));
                    contactIds.add(opp.Contact__c);
                }
                else if (opp.Admission_Type__c == CONDITIONAL_AND_PROVISIONAL_TYPE) {
                    newCases.add(createProvisionalCase(opp));
                    newCases.add(createConditionalCase(opp));
                    contactIds.add(opp.Contact__c);
                }
            }
        }
        if (!newCases.isEmpty() && !createdCases) {
            createdCases = true;
            Map<Id, Contact> contactMap = getContactMap(contactIds);
            for (Case c : newCases) {
                Contact theContact = contactMap.get(c.ContactId);
                if (c.Type == 'Provisional Acceptance') {
                    if (theContact != null) {
                        c.Subject = 'Provisional Acceptance - ' + theContact.Name;
                        c.Description = 'Provisional Acceptance - ' + theContact.Name;
                    }
                }
                if (c.Type == 'Conditional Acceptance') {
                    if (theContact != null) {
                        c.Subject = 'Conditional Acceptance - ' + theContact.Name;
                        c.Description = 'Conditional Acceptance - ' + theContact.Name;
                    }
                }
            }
          
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = false;
            dmo.optAllOrNone = true;
            Database.insert(newCases, dmo);
            
        } 
    }
    
    public static Map<Id, Contact> getContactMap(Set<Id> contactIds) {
        return new Map<Id, Contact>([SELECT Id, Name FROM Contact WHERE Id IN :contactIds]);
    }
    
    private static Case createProvisionalCase(Opportunity opp) {
        Case c = new Case(
            RecordTypeId = studentSuccessCaseRecTypeId,
            ContactId = opp.Contact__c,
            /*HEDA_Program__c = opp.HEDA_Program__c, - no matching field - Luke*/
            Status = 'New',
            Priority = 'High',
            Type = 'Provisional Acceptance',
            Origin = 'Admission Process',
            Subject = 'Provisional Acceptance',
            Description = 'Provisional Acceptance',
            Program__c = opp.EDA_Program_Account_Id__c,
            School__c = opp.School_College__c,
            OwnerId = SSR_ADVISING_QUEUE_ID
        );
        return c;
    }
    
    private static Case createConditionalCase(Opportunity opp) {
        Case c = new Case(
             RecordTypeId = studentSuccessCaseRecTypeId,
            ContactId = opp.Contact__c,
            /*HEDA_Program__c = opp.HEDA_Program__c,  - no matching field - Luke*/
            /*Case_Manager__c = opp.OwnerId,  - no matching field - Luke*/
            Status = 'New',
            Priority = 'High',
            Type = 'Conditional Acceptance',
            Origin = 'Admission Process',
            Subject = 'Conditional Acceptance',
            Description = 'Conditional Acceptance',
            Program__c = opp.EDA_Program_Account_Id__c,
            School__c = opp.School_College__c,
            OwnerId = opp.OwnerId
        );
        return c;
    }

    public static List<Opportunity> getOpportunitiesForApplication(Id appId) {
        List<Opportunity> opps = [
            SELECT 
                Id,
                Application__c,
                StageName,
                Stage_Detail__c
            FROM 
                Opportunity
            WHERE 
                Application__c = :appId 
        ];
        return opps;
    }

    public static List<Opportunity> getOpportunitiesWithCouselorForApplication(Id appId) {
        List<Opportunity> opps = [
            SELECT 
                Id,
                Application__c,
                StageName,
                Stage_Detail__c,
                OwnerId,
                Owner.Name,
                Owner.Email,
                Owner.Profile.Name
            FROM 
                Opportunity
            WHERE 
                Application__c = :appId 
        ];
        return opps;
    }

    public static void updateOpportunityStatusAppCompleted(Id appId) {
        List<Opportunity> opps = getOpportunitiesForApplication(appId);
        List<Opportunity> updateList = new List<Opportunity>();
        for (Opportunity o : opps) {
            if (o.StageName == 'Applied' && o.Stage_Detail__c == 'App Submitted') {
                o.Stage_Detail__c = 'App Completed';
                updateList.add(o);
            }
        }
        if (!updateList.isEmpty()) {
            update updateList;
        }
    }

    public static Map<String, Opportunity> getOpportunitiesForKeys(Set<String> keys) {
        Map<String, Opportunity> oppMap = new Map<String, Opportunity>();
        List<Opportunity> opps = [
            SELECT 
                Id,
                CloseDate,
                StageName,
                Academic_Program__c,
                Opportunity_Key__c,
                Stage_Detail__c,
                Stage_Value__c,
                AccountId
            FROM 
                Opportunity
            WHERE 
                Opportunity_Key__c IN :keys 
        ];
        if (!opps.isEmpty()) {
            for (Opportunity o : opps) {
                oppMap.put(o.Opportunity_Key__c, o);
            }
        }
        return oppMap;
    }

    public static List<Opportunity> getInquiredOpportunitiesForContact(Set<Id> contactIds) {
        List<Opportunity> opps = [
            SELECT 
                Id,
                CloseDate,
                StageName,
                Academic_Program__c,
                Contact__c,
                Opportunity_Key__c,
                Stage_Detail__c,
                Stage_Value__c,
                AccountId
            FROM 
                Opportunity
            WHERE 
                Contact__c IN :contactIds AND StageName = 'Inquired' AND Stage_Detail__c = 'Inquired' 
        ];
        return opps;
    }

}