src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application this response is for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HasDocument__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasDocument</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requirement_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item this response is for.</description>
        <label>Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/classes/TDTM_Requirement_Item_Alert.cls
/**
 * Created by ejc84332 on 2019-03-15.
 */


// THIS IS A PROTOTYPE ONLY

global class TDTM_Requirement_Item_Alert extends TDTMVirtualTriggerHandler {

    global override void onAfterUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        Requirement_Response__c[] has_attatchment = new List<Requirement_Response__c>();


        for(SObject o : newList){
            Requirement_Response__c r = (Requirement_Response__c) o;

            if( r.HasDocument__c == true && r.Requirement_Item__r.School_College__c != 'Undergraduate'){
                has_attatchment.add(r);
            }
        }

        insert create_tasks(has_attatchment);
    }

    private Task[] create_tasks(Requirement_Response__c[] response_list){

        Task[] create_tasks = new List<Task>();

        for(Requirement_Response__c r : response_list){
            create_tasks.add(new Task(
                Subject='New atatchment added to application.',
                WhatId=r.Application__c,
                OwnerId='0055A000008O1JqQAK'
            ));
        }

        return create_tasks;

    }

}