src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Run_Criteria__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Run Criteria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Assignment_Rule_Entry_Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule Entry Criteria</label>
        <referenceTo>Assignment_Rule_Entry__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>DATE</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>INTERGER</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>STRING</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>REFERENCE</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>ANYASSIGN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>The label for filtered field</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Entry__c.object
<CustomObject>
    <description>Add rule entries that specify the criteria used to route records. Rules can be reorder.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Entries</relationshipLabel>
        <relationshipName>Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Rule Entry</label>
    <nameField>
        <displayFormat>ARE-{0000}</displayFormat>
        <label>Assignment Rule Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Field_Map__c.object
<CustomObject>
    <fields>
        <fullName>Map_Name__c</fullName>
        <label>Map Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The value of the picklist option</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Field Map</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>Field Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field_Map_Value__c.object
<CustomObject>
    <fields>
        <fullName>Field_Map__c</fullName>
        <label>Field Map</label>
        <referenceTo>Field_Map__c</referenceTo>
        <relationshipLabel>Field Map Values</relationshipLabel>
        <relationshipName>Field_Map_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Field_Map_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Map Value</label>
    <nameField>
        <displayFormat>FMV-{00000}</displayFormat>
        <label>Field Map Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Map Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Geographic_Territory__c.object
<CustomObject>
    <description>This object defines geographic territories by zip code.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of the territory</description>
        <inlineHelpText>Enter the city for the territory</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Code__c</fullName>
        <description>The three digit county code identified by the Federal Information Processing Standard (FIPS)</description>
        <inlineHelpText>Enter the three digit FIPS county code</inlineHelpText>
        <label>County Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>The county for the territory</description>
        <inlineHelpText>Enter the county for the territory</inlineHelpText>
        <label>County</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>The postal code for the territory</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the postal code for the territory</inlineHelpText>
        <label>Postal Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <description>The two digit state code identified by the Federal Information Processing Standard (FIPS)</description>
        <inlineHelpText>Enter the two digit FIPS state code</inlineHelpText>
        <label>State Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>A picklist of abbreviated states for the US only</description>
        <inlineHelpText>Select the state for the territory</inlineHelpText>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <label>Geographic Territory</label>
    <nameField>
        <label>Geographic Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographic Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Geographic_Territory_Assignment__c.object
<CustomObject>
    <description>This object defines geographic territory assignment by user and object type.</description>
    <fields>
        <fullName>Geographic_Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Geographic Territory</label>
        <referenceTo>Geographic_Territory__c</referenceTo>
        <relationshipLabel>Geographic Territory Assignments</relationshipLabel>
        <relationshipName>Geographic_Territory_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Geographic_Territory_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographic Territory Assignment</label>
    <nameField>
        <displayFormat>GTA-{0000000}</displayFormat>
        <label>Geographic Territory Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geographic Territory Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/US_States.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
        <default>true</default>
        <label>MN</label>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <description>List of abbreviated state for the US</description>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/TestUtility.cls
@isTest
public class TestUtility {
    
    static Id assignmentCritRecTypeId = Schema.SObjectType.Assignment_Rule_Criteria_Based_Rule__c.getRecordTypeInfosByName().get('Assignment Rule - Criteria').getRecordTypeId();
    
    public static void setupTestData(){
        setupAssignmentRuleTestData();
        setupFieldValueMapTestData();
        createGeoTerritories();
    }
    
    public static void setupTestDataCriteriaBasedRule(){
        setupCriteriaBasedAssignmentRuleTestData();
    }
    
    
    static void setupCriteriaBasedAssignmentRuleTestData(){
        
        //create assignment rule for account sobject
        Assignment_Rule__c  assignmentRule = new Assignment_Rule__c(Name = 'For Test Class 2', sObject__c = 'Account', Active__c = true, Has_Run_Criteria__c = true);
        insert assignmentRule;
        
        Assignment_Rule_Criteria_Based_Rule__c assignmentRuleCriteria = new Assignment_Rule_Criteria_Based_Rule__c(RecordTypeId = assignmentCritRecTypeId, Assignment_Rule__c = assignmentRule.Id, Field__c = 'Name', Value__c ='Test Account 1', FieldType__c = 'STRING', Operator__c = 'equals', SObject_Type__c = 'Account');
        insert assignmentRuleCriteria;
        
        //create 2 rule entries
        List<Assignment_Rule_Entry__c> ruleEntries = new List<Assignment_Rule_Entry__c>();
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Filter_Logic__c = '1', Order__c = 1, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 2, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 3, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 4, Send_Email__c = true));
        
        
        
        insert ruleEntries;
        
        List<Assignment_Rule_Criteria_Based_Rule__c> ruleCriterias = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        // equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 1, Value__c = 'Test Account 1', FieldType__c = 'STRING', Operator__c = 'equals', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //not equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 2, Value__c = 'Test Account Not 1', FieldType__c = 'STRING', Operator__c = 'not equal to', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        
        
        //less than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 3, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));        
        //greater than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 4, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //less or equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 5, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //greater or equal 
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 6, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //starts with
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 7, Value__c = 'Test', FieldType__c = 'STRING', Operator__c = 'starts with', Field_Label__c = 'Account Name', SObject_Type__c = 'Account')); 

        
        // equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 1, Value__c = 'Test Account 2', FieldType__c = 'STRING', Operator__c = 'equals', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //not equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 2, Value__c = 'Test Account Not 2', FieldType__c = 'STRING', Operator__c = 'not equal to', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //starts with
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 3, Value__c = 'Test', FieldType__c = 'STRING', Operator__c = 'starts with', Field_Label__c = 'Account Name', SObject_Type__c = 'Account')); 
        
        //less than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 4, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));        
        //greater than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 5, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //less or equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 6, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //greater or equal 
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 7, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));

        insert ruleCriterias;
        
    }
    
    //creates all test data for assignment rule application
    static void setupAssignmentRuleTestData(){
        
        //create assignment rule for account sobject
        Assignment_Rule__c  assignmentRule = new Assignment_Rule__c(Name = 'For Test Class', sObject__c = 'Account', Active__c = true);
        insert assignmentRule;
        
        //create 2 rule entries
        List<Assignment_Rule_Entry__c> ruleEntries = new List<Assignment_Rule_Entry__c>();
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Filter_Logic__c = '1', Order__c = 1, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 2, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 3, Send_Email__c = true));
        
        ruleEntries.add(new Assignment_Rule_Entry__c(Assignment_Rule__c = assignmentRule.Id, Assigned_To__c = UserInfo.getUserId(), Order__c = 4, Send_Email__c = true));
        
        
        
        insert ruleEntries;
        
        List<Assignment_Rule_Criteria_Based_Rule__c> ruleCriterias = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        // equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 1, Value__c = 'Test Account 1', FieldType__c = 'STRING', Operator__c = 'equals', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //not equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 2, Value__c = 'Test Account Not 1', FieldType__c = 'STRING', Operator__c = 'not equal to', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        
        
        //less than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 3, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));        
        //greater than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 4, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //less or equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 5, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //greater or equal 
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 6, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //starts with
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(0).Id, Field__c = 'Name', Position__c = 7, Value__c = 'Test', FieldType__c = 'STRING', Operator__c = 'starts with', Field_Label__c = 'Account Name', SObject_Type__c = 'Account')); 
        
        // value map and criteria with no filters
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(1).Id, Field__c = 'Field_Value_Map', Position__c = 1, Value__c = 'Type', FieldType__c = 'ANYASSIGN', Operator__c = 'equals', Field_Label__c = 'Field Value Map'));
        
        
        // equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 1, Value__c = 'Test Account 2', FieldType__c = 'STRING', Operator__c = 'equals', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //not equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 2, Value__c = 'Test Account Not 2', FieldType__c = 'STRING', Operator__c = 'not equal to', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //starts with
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 3, Value__c = 'Test', FieldType__c = 'STRING', Operator__c = 'starts with', Field_Label__c = 'Account Name', SObject_Type__c = 'Account')); 
        
        //less than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 4, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));        
        //greater than
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 5, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater than', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //less or equal
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 6, Value__c = 'Test Account 99999', FieldType__c = 'STRING', Operator__c = 'less or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        //greater or equal 
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(2).Id, Field__c = 'Name', Position__c = 7, Value__c = 'Test Account', FieldType__c = 'STRING', Operator__c = 'greater or equal', Field_Label__c = 'Account Name', SObject_Type__c = 'Account'));
        
        // geo territory and criteria with no filters
        ruleCriterias.add(new Assignment_Rule_Criteria_Based_Rule__c(
            Assignment_Rule_Entry_Criteria__c = ruleEntries.get(1).Id, Field__c = 'Geo_Location', Position__c = 1, Value__c = 'BillingPostalCode', FieldType__c = 'ANYASSIGN', Operator__c = 'equals', Field_Label__c = 'Geo Location'));
        
        insert ruleCriterias;
        
        
    }
    
    //creates all test data for field value map
    static void setupFieldValueMapTestData(){
        Schema.DescribeFieldResult fieldResult = Account.Type.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<Field_Map__c> fieldMaps = new List<Field_Map__c>();
        
        for( Schema.PicklistEntry f : ple){
            fieldMaps.add(new Field_Map__c(Value__c = f.getValue(), Map_Name__c = 'Account Types'));
        }       
        
        insert fieldMaps;
        
        List<Field_Map_Value__c> fmvList = new List<Field_Map_Value__c>();
        for(Field_Map__c fm : fieldMaps){
            fmvList.add(new Field_Map_Value__c( User__c = UserInfo.getUserId(), Field_Map__c = fm.Id, SObject_Type__c = 'Account'));
        }
        insert fmvList;
    }
    
    static void createGeoTerritories(){
        Geographic_Territory__c geographicTerritory = new Geographic_Territory__c();
        geographicTerritory.name = 'AK--Wasilla';
        geographicTerritory.City__c  = 'Wasilla';    
        geographicTerritory.County__c = 'Matanuska-Susitna Borough';    
        geographicTerritory.County_Code__c = '170';    
        geographicTerritory.Postal_Code__c = '99623';    
        geographicTerritory.State__c = 'Alaska';  
        geographicTerritory.State_Code__c = '02';  
        insert geographicTerritory; 
        
        Geographic_Territory_Assignment__c assignment = new Geographic_Territory_Assignment__c();
        assignment.Geographic_Territory__c = geographicTerritory.id;
        assignment.SObject_Type__c = 'Account';
        assignment.User__c = UserInfo.getUserId();
        insert assignment;
    }
    
    
    
}