src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssignmentRuleHandler.cls
@isTest
public class TestAssignmentRuleHandler {
    
    @testSetup
    static void testSetup(){
        TestUtility.setupTestData();
        TestUtility.setupTestDataCriteriaBasedRule();
    }
    
    static testMethod void testTriggerHandler(){
        
        List<Account> accounts = new List<Account>();
        Schema.DescribeFieldResult fieldResult = Account.Type.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        accounts.add(new Account(Name = 'Test Account 1', Website = 'www.google.com'));
        accounts.add(new Account(Name = 'Value Map', Type = ple.get(0).getValue()));
        accounts.add(new Account(Name = 'Test Account 2'));
        accounts.add(new Account(Name = 'Geo Territory', BillingPostalCode = '99623'));
        insert accounts;
        
        test.startTest();
        //ownership probably won't change, as I've assigned the owners to the same people
        //but emails should have been sent out
        AssignmentRuleHandler.execute(accounts);
        
        //emails should have been sent out this transaction
        System.assertEquals(1, System.Limits.getEmailInvocations());
        test.stopTest();
    }
    
    static testMethod void testCheckCriteriaStrings(){
        Schema.SObjectType accountType = Schema.getGlobalDescribe().get('Account');

        AssignmentRuleHandler.fieldMap = Account.getSObjectType().getDescribe().fields.getMap();
        List<SObject> sobjects = new List<SObject>();
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'equals', Value__c = 'Test'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'not equal to', Value__c = 'Test 2'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'starts with', Value__c = 'T'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'contains', Value__c = 'Test'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'does not contain', Value__c = '99'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'less than', Value__c = 'Test99'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'greater than', Value__c = 'Te'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'less or equal', Value__c = 'Test'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'Name', Operator__c = 'greater or equal', Value__c = 'Test'));

        SObject acct = accountType.newSObject();
        acct.put('Name', 'Test');

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(acct, criteria[i]));
        }

    }

    static testMethod void testCheckCriteriaBooleans(){
        Schema.SObjectType oppType = Schema.getGlobalDescribe().get('Opportunity');
        AssignmentRuleHandler.fieldMap = Opportunity.getSObjectType().getDescribe().fields.getMap();
     
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'IsPrivate', Operator__c = 'equals', Value__c = 'True'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'IsPrivate', Operator__c = 'not equal to', Value__c = 'False'));

        SObject opp = oppType.newSObject();
        opp.put('IsPrivate', true);

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(opp, criteria[i]));
        }

    }

    static testMethod void testCheckCriteriaDates(){
        Schema.SObjectType oppType = Schema.getGlobalDescribe().get('Opportunity');
        AssignmentRuleHandler.fieldMap = Opportunity.getSObjectType().getDescribe().fields.getMap();
     
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'equals', Value__c = Date.today().format()));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'not equal to', Value__c = Date.today().addDays(-1).format()));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'less than', Value__c = Date.today().addDays(1).format()));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'greater than', Value__c = Date.today().addDays(-1).format()));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'less or equal', Value__c = Date.today().format()));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'CloseDate', Operator__c = 'greater or equal', Value__c = Date.today().format()));

        SObject opp = oppType.newSObject();
        opp.put('CloseDate', Date.today());

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(opp, criteria[i]));
        }
    }

     static testMethod void testCheckCriteriaDateTime(){
        Schema.SObjectType eventType = Schema.getGlobalDescribe().get('Event');
        AssignmentRuleHandler.fieldMap = Event.getSObjectType().getDescribe().fields.getMap();
        Datetime date_time = DateTime.newInstanceGMT(1996, 3, 22);
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'equals', Value__c = String.valueOf(date_time)));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'not equal to', Value__c = String.valueOf(date_time.addDays(1))));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'less than', Value__c = String.valueOf(date_time.addDays(1))));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'greater than', Value__c = String.valueOf(date_time.addDays(-1))));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'less or equal', Value__c = String.valueOf(date_time)));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'EndDateTime', Operator__c = 'greater or equal', Value__c = String.valueOf(date_time)));

        SObject event = eventType.newSObject();
        event.put('EndDateTime', date_time);

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(event, criteria[i]));
        }
    }


    static testMethod void testCheckCriteriaDoubles(){
        Schema.SObjectType accountType = Schema.getGlobalDescribe().get('Account');

        AssignmentRuleHandler.fieldMap = Account.getSObjectType().getDescribe().fields.getMap();
        List<SObject> sobjects = new List<SObject>();
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'equals', Value__c = '1'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'not equal to', Value__c = '2'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'less than', Value__c = '3'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'greater than', Value__c = '0'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'less or equal', Value__c = '1'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'AnnualRevenue', Operator__c = 'greater or equal', Value__c = '1'));

        SObject acct = accountType.newSObject();
        acct.put('AnnualRevenue', 1);

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(acct, criteria[i]));
        }

    }


    static testMethod void testCheckCriteriaIntegers(){
        Schema.SObjectType accountType = Schema.getGlobalDescribe().get('Account');

        AssignmentRuleHandler.fieldMap = Account.getSObjectType().getDescribe().fields.getMap();
        List<SObject> sobjects = new List<SObject>();
        List<Assignment_Rule_Criteria_Based_Rule__c> criteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();

        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'equals', Value__c = '1'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'not equal to', Value__c = '2'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'less than', Value__c = '3'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'greater than', Value__c = '0'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'less or equal', Value__c = '1'));
        criteria.add(new Assignment_Rule_Criteria_Based_Rule__c(Field__c = 'NumberOfEmployees', Operator__c = 'greater or equal', Value__c = '1'));

        SObject acct = accountType.newSObject();
        acct.put('NumberOfEmployees', 1);

        // all should return true
        for(Integer i = 0; i < criteria.size() ; i++){
            System.assert(AssignmentRuleHandler.checkCriteria(acct, criteria[i]));
        }

    }
}