src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <fields>
        <fullName>sObject__c</fullName>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Assignment_Rule_Entry_Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule Entry Criteria</label>
        <referenceTo>Assignment_Rule_Entry__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>DATE</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>INTERGER</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>STRING</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>REFERENCE</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>ANYASSIGN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>The label for filtered field</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Entry__c.object
<CustomObject>
    <description>Add rule entries that specify the criteria used to route records. Rules can be reorder.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Entries</relationshipLabel>
        <relationshipName>Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Rule Entry</label>
    <nameField>
        <displayFormat>ARE-{0000}</displayFormat>
        <label>Assignment Rule Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Entries</pluralLabel>
    <recordTypes>
        <fullName>Criteria_Based_Rule</fullName>
        <active>true</active>
        <description>Record type for criteria based assignment rules</description>
        <label>Criteria Based Rule</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssignRulesEntryCriteriaNewController.cls
/*
*
* controller for assignment rules entry criteria new lightning component
*
*
*
*/
public with sharing class AssignRulesEntryCriteriaNewController {
    
    static Id assignmentCritRecTypeId = Schema.SObjectType.Assignment_Rule_Criteria_Based_Rule__c.getRecordTypeInfosByName().get('Assignment Rule Entry Criteria - Criteria').getRecordTypeId();
    static Id critBasedRuleRecTypeId = Schema.SObjectType.Assignment_Rule_Entry__c.getRecordTypeInfosByDeveloperName().get('Criteria_Based_Rule').getRecordTypeId();
    
    //map of all active users
    public static Map<Id, User> userMap { 
        get { 
            if( userMap == null) {
                userMap = new Map<Id, User> ([SELECT id, Name, Email FROM User WHERE IsActive =: true]); 
            }
            return userMap;
        }
        private set;
    }
    //map of all active queues
    public static Map<Id, Group> groupMap { 
        get{ 
            if(groupMap == null) {
                groupMap = new Map<Id, Group> ([SELECT id, Name, Email FROM Group WHERE Type =: 'Queue']); 
            }
            return groupMap;
        }
        private set;
    }
    
    //build operators manually
    @AuraEnabled(cacheable=true)
    public static String getOperators(){
        Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>> operatorMap = new Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>>();
        operatorMap.put('STRINGS', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('starts with', 'starts with'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('contains', 'contains'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('does not contains', 'does not contains'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less than', 'less than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater than','greater than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less or equal', 'less or equal'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater or equal', 'greater or equal')});
        
        
        
        operatorMap.put('BOOLEAN', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to')
                                });
        
        
        operatorMap.put('GENERAL', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{ 
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less than', 'less than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater than','greater than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less or equal', 'less or equal'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater or equal', 'greater or equal')
                                });
        
        operatorMap.put('MULTIPICKLIST', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('includes', 'includes'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('excludes', 'excludes')
                                });
        
        
        operatorMap.put('ANYASSIGN', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals')
                                });
        
        
        
        return JSON.serialize(operatorMap);
    }
    
    
    /*
* 
* this function retrieves an existing rule entry
* and is used when edit button is called for a rule entry
* 
* if any exceptions occur, just allow them to stop the app
* 
* @param id - is of rule entry
* @return string - json of wrapper object
* 
*/ 
     @AuraEnabled(cacheable=true)
    public static string retrieveRuleEntry(String id){
        
        
        Assignment_Rule_Entry__c entry = [SELECT id, 
                                          Order__c, 
                                          Assignment_Rule__c, 
                                          Assignment_Rule__r.sObject__c, 
                                          Filter_Logic__c, 
                                          Assigned_To__c, 
                                          Send_Email__c,
                                          (SELECT id, 
                                           Field__c, 
                                           Field_Label__c,
                                           FieldType__c,
                                           Operator__c,
                                           Position__c, 
                                           SObject_Type__c,
                                           Value__c FROM Assignment_Rule_Criteria_Based_Rules__r ORDER BY Position__c ASC) 
                                          FROM Assignment_Rule_Entry__c WHERE Id =: id];
        
        AssignmentRuleWrapperObjects.EntryWrapper entryWrapper = new AssignmentRuleWrapperObjects.EntryWrapper();
        entryWrapper.order = Integer.valueOf(entry.Order__c);
        entryWrapper.id = entry.Id;
        entryWrapper.filterLogic = entry.Filter_Logic__c;
        entryWrapper.assignmenRuleId = entry.Assignment_Rule__c;
        entryWrapper.assignedTo = entry.Assigned_To__c;
        entryWrapper.assignedToName = userMap.get(entry.Assigned_To__c) != null ? userMap.get(entry.Assigned_To__c).Name 
            : groupMap.get(entry.Assigned_To__c) != null ? groupMap.get(entry.Assigned_To__c).Name : null;
        entryWrapper.sendEmail = entry.Send_Email__c;
        
        SObjectType s_object = Schema.getGlobalDescribe().get(entry.Assignment_Rule__r.sObject__c);
        Map<String,Schema.SObjectField> mfields = s_object.getDescribe().fields.getMap();
        
        //loop through the entry criteria 
        //add them to the wrapper
        for( Assignment_Rule_Criteria_Based_Rule__c crit : entry.Assignment_Rule_Criteria_Based_Rules__r){
            AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper = new AssignmentRuleWrapperObjects.EntryCriteriaWrapper();
            
            critWrapper.id = crit.Id;
            critWrapper.position = Integer.valueOf(crit.Position__c);
            critWrapper.field = crit.Field__c;
            critWrapper.operator = crit.Operator__c;
            critWrapper.fieldLabel = crit.Field_Label__c;
            critWrapper.dataType = crit.FieldType__c;
            critWrapper.value = crit.Value__c;
            critWrapper.sobjectType = crit.SObject_Type__c;
            
            if(entryWrapper.criteria == null){
                entryWrapper.criteria = new List<AssignmentRuleWrapperObjects.EntryCriteriaWrapper>();
            }
            
            entryWrapper.criteria.add(critWrapper);
        }
        
        //recreates the 5 empty rows on initial start
        if(entryWrapper.criteria[0].dataType != 'ANYASSIGN' && entryWrapper.criteria.size() < 5){
            while(entryWrapper.criteria.size() < 5){
                entryWrapper.criteria.add(new AssignmentRuleWrapperObjects.EntryCriteriaWrapper());
            }
        }
        
        return JSON.serialize(entryWrapper);
    }
    
    /*
* 
* this function deserializes passed in json object
* and creates the rule entry and rule entry criteria records
* with the data passed in
* 
* if any exceptions occur, just allow them to stop the app
* 
* @param entryJSON - json of entry passed in from lightning component
* 
*/ 
    @AuraEnabled
    public static void handleUpsertEntry(String entryJSON){
        AssignmentRuleWrapperObjects.EntryWrapper entryWrapper = (AssignmentRuleWrapperObjects.EntryWrapper) JSON.deserialize(entryJSON, AssignmentRuleWrapperObjects.EntryWrapper.class);
        Assignment_Rule_Entry__c entry = new Assignment_Rule_Entry__c();
        List<Assignment_Rule_Criteria_Based_Rule__c> critRules = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        
        //only set the assignment rule id if this is a new record
        if(!String.isEmpty(entryWrapper.id) && entryWrapper.id != null){
            entry.Id = entryWrapper.id;
        }else{
            entry.Assignment_Rule__c = entryWrapper.assignmenRuleId;
        }
        entry.Order__c =  entryWrapper.order;
        entry.Filter_Logic__c = entryWrapper.filterLogic;
        entry.Assigned_To__c =  entryWrapper.assignedTo;
        entry.Send_Email__c = entryWrapper.sendEmail != null ? entryWrapper.sendEmail : false;
        entry.RecordTypeId = critBasedRuleRecTypeId;
        
        //create / upsert the rule entry first
        upsert entry;
        
        for(AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper :  entryWrapper.criteria){
            Assignment_Rule_Criteria_Based_Rule__c critRule = new Assignment_Rule_Criteria_Based_Rule__c();
            critRule.Field__c = critWrapper.field;
            critRule.Value__c = critWrapper.value;
            critRule.Operator__c = critWrapper.operator;
            critRule.Position__c = critWrapper.position;
            critRule.FieldType__c = critWrapper.dataType;
            critRule.Field_Label__c = critWrapper.fieldLabel;
            critRule.SObject_Type__c = critWrapper.sobjectType;
            critRule.RecordTypeId = assignmentCritRecTypeId;
            if(!String.isEmpty(critWrapper.id)){
                critRule.Id = critWrapper.Id;
            }else{
                critRule.Assignment_Rule_Entry_Criteria__c = entry.Id;
            }
            critRules.add(critRule);
        }
        
        //create / upsert the rule entry criteria after
        upsert critRules;
        
        //if there are any to delete, then delete them
        if(entryWrapper.deleteCriteria != null && !entryWrapper.deleteCriteria.isEmpty()){
            List<Id> recordsToDelete = new List<Id>();
            for(String s : entryWrapper.deleteCriteria){
                recordsToDelete.add(Id.valueOf(s));
            }
            Database.delete(recordsToDelete);
        }
        
    }
    
}