src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Assignment_Rule_Entry_Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule Entry Criteria</label>
        <referenceTo>Assignment_Rule_Entry__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>DATE</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>INTERGER</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>STRING</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>REFERENCE</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>ANYASSIGN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>The label for filtered field</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Entry__c.object
<CustomObject>
    <description>Add rule entries that specify the criteria used to route records. Rules can be reorder.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Entries</relationshipLabel>
        <relationshipName>Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Rule Entry</label>
    <nameField>
        <displayFormat>ARE-{0000}</displayFormat>
        <label>Assignment Rule Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssignRulesEntryCritNewCntrler.cls
@isTest
public class TestAssignRulesEntryCritNewCntrler {
    
    @testSetup
    static void testSetup(){
        TestUtility.setupTestData();
    }
    
    static testMethod void testGetOperators(){
        test.startTest();
        String operators = AssignRulesEntryCriteriaNewController.getOperators();
        test.stopTest();
        Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>> wrapper  = (Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>>) JSON.deserialize(operators, Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>>.class);
        System.assert(!wrapper.isEmpty());
    }
    
    static testMethod void testRetrieveRuleEntry(){
        List<Assignment_Rule_Entry__c> ruleEntries = [SELECT id,
                                                      Order__c, 
                                                      Assignment_Rule__c, 
                                                      Filter_Logic__c, 
                                                      Assigned_To__c, 
                                                      Send_Email__c, (SELECT id, 
                                                                      Field__c, 
                                                                      Field_Label__c,
                                                                      FieldType__c,
                                                                      Operator__c,
                                                                      Position__c, 
                                                                      SObject_Type__c,
                                                                      Value__c FROM Assignment_Rule_Criteria_Based_Rules__r ORDER BY Position__c ASC)
                                                      FROM Assignment_Rule_Entry__c  LIMIT 1];
        test.startTest();
        String ruleEntry = AssignRulesEntryCriteriaNewController.retrieveRuleEntry(ruleEntries.get(0).Id);
        test.stopTest();
        AssignmentRuleWrapperObjects.EntryWrapper entryWrapper = (AssignmentRuleWrapperObjects.EntryWrapper) JSON.deserialize(ruleEntry, AssignmentRuleWrapperObjects.EntryWrapper.class);
        
        System.assertEquals(ruleEntries.get(0).Id, entryWrapper.id);
        System.assertEquals(ruleEntries.get(0).Send_Email__c, entryWrapper.sendEmail);
        System.assertEquals(ruleEntries.get(0).Filter_Logic__c, entryWrapper.filterLogic);
        System.assertEquals(ruleEntries.get(0).Order__c, entryWrapper.order);
        System.assertEquals(ruleEntries.get(0).Assignment_Rule__c, entryWrapper.assignmenRuleId);
    }
    
    static testMethod void testHandleUpsertEntry(){
          List<Assignment_Rule_Entry__c> ruleEntries = [SELECT id,
                                                      Order__c, 
                                                      Assignment_Rule__c, 
                                                      Filter_Logic__c, 
                                                      Assigned_To__c, 
                                                      Send_Email__c, (SELECT id, 
                                                                      Field__c, 
                                                                      Field_Label__c,
                                                                      FieldType__c,
                                                                      Operator__c,
                                                                      Position__c, 
                                                                      SObject_Type__c,
                                                                      Value__c FROM Assignment_Rule_Criteria_Based_Rules__r ORDER BY Position__c ASC)
                                                        FROM Assignment_Rule_Entry__c  LIMIT 1];
        
        String ruleEntry = AssignRulesEntryCriteriaNewController.retrieveRuleEntry(ruleEntries.get(0).Id);
        AssignmentRuleWrapperObjects.EntryWrapper entryWrapper = (AssignmentRuleWrapperObjects.EntryWrapper) JSON.deserialize(ruleEntry, AssignmentRuleWrapperObjects.EntryWrapper.class);
        entryWrapper.order = 99;
        entryWrapper.sendEmail = true;
        entryWrapper.filterLogic = 'GIBERISH';
        entryWrapper.deleteCriteria = new List<String>();
        entryWrapper.deleteCriteria.add(ruleEntries.get(0).Assignment_Rule_Criteria_Based_Rules__r.get(0).id);
        String entryJSON = JSON.serialize(entryWrapper);
        
        test.startTest();
        AssignRulesEntryCriteriaNewController.handleUpsertEntry(entryJSON);
        test.stopTest();
        
        List<Assignment_Rule_Entry__c> updatedRuleEntries = [SELECT id,
                                                             Order__c, 
                                                             Assignment_Rule__c, 
                                                             Filter_Logic__c, 
                                                             Send_Email__c FROM Assignment_Rule_Entry__c WHERE id =: ruleEntries.get(0).Id ];
        
        //rule entry has been updated with new values
        System.assertEquals(99, updatedRuleEntries.get(0).Order__c);
        System.assertEquals(true, updatedRuleEntries.get(0).Send_Email__c);
        System.assertEquals('GIBERISH', updatedRuleEntries.get(0).Filter_Logic__c);
        System.assertEquals(0, [SELECT COUNT() FROM Assignment_Rule_Criteria_Based_Rule__c WHERE id =: ruleEntries.get(0).Assignment_Rule_Criteria_Based_Rules__r.get(0).id]);
        
    }
}