src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sObject__c</fullName>
        <label>sObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignRulesRuleEntriesController.cls
public with sharing class AssignRulesRuleEntriesController {
    
    /*
* 
* this method retrieves the assignment rule
* for a specified sobject type
* 
* @param sobjectType - string of object type
* @return collection of wrapper objects
* 
*/ 
    @AuraEnabled(cacheable=true)
    public static List<Assignment_Rule__c> retrieveAssignmentRules(String sobjectType){
        List<Assignment_Rule__c> rules = [SELECT id, Name, Active__c FROM Assignment_Rule__c WHERE sObject__c =: sobjectType Order by Name ASC];
        return rules;
    }

}