src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Assignment_Rule_Entry_Criteria__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule Entry Criteria</label>
        <referenceTo>Assignment_Rule_Entry__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>The label for filtered field</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Entry__c.object
<CustomObject>
    <description>Add rule entries that specify the criteria used to route records. Rules can be reorder.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Entries</relationshipLabel>
        <relationshipName>Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Filter_Logic__c</fullName>
        <label>Filter Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Rule Entry</label>
    <nameField>
        <displayFormat>ARE-{0000}</displayFormat>
        <label>Assignment Rule Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssignRulesRuleEntryCriteriaController.cls
public with sharing class AssignRulesRuleEntryCriteriaController {
    
    /*
* 
* this method retrieves the assignment rule entries 
* for a specified assignment rule id
* 
* @param ruleId - assignment rule id
* @return collection of wrapper objects
* 
*/ 
    @AuraEnabled(cacheable=true)
    public static String retrieveAssignmentRuleEntries(String ruleId){
        List< AssignmentRuleWrapperObjects.AssignmentRuleEntryWrapper> entries = new List< AssignmentRuleWrapperObjects.AssignmentRuleEntryWrapper>();
        
        for(Assignment_Rule_Entry__c entry : [SELECT id, Order__c, Assigned_To__c, Send_Email__c, Filter_Logic__c,
                                              (SELECT Field__c, Field_Label__c, Operator__c, Value__c, Position__c, SObject_Type__c FROM Assignment_Rule_Criteria_Based_Rules__r ORDER BY Position__c ASC)
                                              FROM Assignment_Rule_Entry__c WHERE Assignment_Rule__c =: ruleId ORDER BY Order__c ])
        {
            AssignmentRuleWrapperObjects.AssignmentRuleEntryWrapper wrapper = new  AssignmentRuleWrapperObjects.AssignmentRuleEntryWrapper();
            wrapper.order = Integer.valueOf(entry.Order__c);
            wrapper.Id = entry.Id;
            wrapper.assignedToId = entry.Assigned_To__c;
            wrapper.AssignedToName = AssignRulesEntryCriteriaNewController.userMap.get(entry.Assigned_To__c) != null 
                ? AssignRulesEntryCriteriaNewController.userMap.get(entry.Assigned_To__c).Name : AssignRulesEntryCriteriaNewController.groupMap.get(entry.Assigned_To__c) != null 
                    ? AssignRulesEntryCriteriaNewController.groupMap.get(entry.Assigned_To__c).Name : '';
            wrapper.sendEmail = entry.Send_Email__c;
            if(!entry.Assignment_Rule_Criteria_Based_Rules__r.isEmpty()){
                wrapper.criteria = '';
                
                if(entry.Filter_Logic__c != null){
                    String filter = '';
                    Integer size = entry.Filter_Logic__c.length();
                    
                    for(Integer i = 0; i < size; i++){                      
                        if(entry.Filter_Logic__c.subString(i, i + 1).isNumeric()){
                            filter += '(' + entry.Filter_Logic__c.subString(i, i + 1) + ')';
                        }else{
                            filter += entry.Filter_Logic__c.subString(i, i + 1);
                        }
                    }
                    for(Assignment_Rule_Criteria_Based_Rule__c cr : entry.Assignment_Rule_Criteria_Based_Rules__r){
                        String criteria = cr.SObject_Type__c != null ? '(' + cr.Field_Label__c + ' ' + cr.Operator__c + ' ' + cr.Value__c + ')' 
                            :  '(' + cr.Field_Label__c + ' ' + cr.Operator__c + ' ' + cr.Value__c + ')';
                        filter = filter.replace('(' + String.valueOf(cr.Position__c) + ')', criteria);
                    }
                    
                    wrapper.criteria = filter;
                    
                }else{
                    for(Assignment_Rule_Criteria_Based_Rule__c cr : entry.Assignment_Rule_Criteria_Based_Rules__r){
                        wrapper.criteria += cr.SObject_Type__c != null ? '(' + cr.Field_Label__c + ' ' + cr.Operator__c + ' ' + cr.Value__c + ') AND ' 
                            : '(' + cr.Field_Label__c + ' ' + cr.Operator__c + ' ' + cr.Value__c + ') AND ';
                    }
                    if( wrapper.criteria.endsWith(' AND ')){
                        wrapper.criteria = wrapper.criteria.removeEnd(' AND ');
                    }
                }
            }
            entries.add(wrapper);
        }
        
        return JSON.serialize(entries);
    }
    
}