src/objects/Assignment_Rule__c.object
<CustomObject>
    <description>This object holds data for custom assignment rules, such as which object and if is active or not. Only 1 rule can be active per sObject.</description>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Criteria_Based_Rule__c.object
<CustomObject>
    <description>This object holds data related to criteria based assignment rules</description>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Criteria Based Rules</relationshipLabel>
        <relationshipName>Assignment_Rule_Criteria_Based_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOOLEAN</fullName>
                </value>
                <value>
                    <fullName>CURRENCY</fullName>
                </value>
                <value>
                    <fullName>DATE</fullName>
                </value>
                <value>
                    <fullName>DATETIME</fullName>
                </value>
                <value>
                    <fullName>TIME</fullName>
                </value>
                <value>
                    <fullName>DOUBLE</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>INTERGER</fullName>
                </value>
                <value>
                    <fullName>PERCENT</fullName>
                </value>
                <value>
                    <fullName>PICKLIST</fullName>
                </value>
                <value>
                    <fullName>MULTIPICKLIST</fullName>
                </value>
                <value>
                    <fullName>STRING</fullName>
                </value>
                <value>
                    <fullName>TEXTAREA</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>REFERENCE</fullName>
                </value>
                <value>
                    <fullName>PHONE</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>ANYASSIGN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>The label for filtered field</description>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
                <value>
                    <fullName>within</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule Criteria Based Rule</label>
    <nameField>
        <displayFormat>AREC-{0000}</displayFormat>
        <label>Assignment Rule Criteria Based Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Rule Criteria Based Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignmentRulesRuleEntryController.cls
/*
 * 
 * @Author - Luke Vang
 * @Description - controller to handle creating run criteria for assignment rules
 *  
 * 
 */ 
public with sharing class AssignmentRulesRuleEntryController {
    
    static Id assignmentCritRecTypeId = Schema.SObjectType.Assignment_Rule_Criteria_Based_Rule__c.getRecordTypeInfosByName().get('Assignment Rule - Criteria').getRecordTypeId();

    //build operators manually
    @AuraEnabled(cacheable=true)
    public static String getOperators(){
        Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>> operatorMap = new Map<String, List<AssignmentRuleWrapperObjects.ComboboxWrapper>>();
        operatorMap.put('STRINGS', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('starts with', 'starts with'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('contains', 'contains'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('does not contains', 'does not contains'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less than', 'less than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater than','greater than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less or equal', 'less or equal'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater or equal', 'greater or equal')});
        
        
        
        operatorMap.put('BOOLEAN', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to')
                                });
        
        
        operatorMap.put('GENERAL', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{ 
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),  
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'), 
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less than', 'less than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater than','greater than'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('less or equal', 'less or equal'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('greater or equal', 'greater or equal')
                                });
        
        operatorMap.put('MULTIPICKLIST', 
                        new List<AssignmentRuleWrapperObjects.ComboboxWrapper>{
                            new AssignmentRuleWrapperObjects.ComboboxWrapper('-- none --', ''),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('equals', 'equals'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('not equal to', 'not equal to'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('includes', 'includes'),
                                new AssignmentRuleWrapperObjects.ComboboxWrapper('excludes', 'excludes')
                                });
        
        
        
        return JSON.serialize(operatorMap);
    }
    
    /*
     * 
     * retrieveRuleCriteria
     * 
     * this method takes in a assignment rule id
     * and retrieves all it's related rule entries
     * 
     * @param String ruleId - assignment rule Id
     * @return String json object of rule entries
     */ 
    @AuraEnabled
    public static String retrieveRuleCriteria(String ruleId){
        AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper = new AssignmentRuleWrapperObjects.EntryCriteriaWrapper();
        List<Assignment_Rule_Criteria_Based_Rule__c> ruleCriteria = new List<Assignment_Rule_Criteria_Based_Rule__c>();
        ruleCriteria = [SELECT id, Field__c, Operator__c, Field_Label__c, FieldType__c, Value__c, SObject_Type__c, Assignment_Rule__c, RecordTypeId 
                        FROM Assignment_Rule_Criteria_Based_Rule__c
                        WHERE Assignment_Rule__c =: ruleId];
        
        if(!ruleCriteria.isEmpty()){
            critWrapper.field = ruleCriteria[0].Field__c;
            critWrapper.operator = ruleCriteria[0].Operator__c;
            critWrapper.fieldLabel = ruleCriteria[0].Field_Label__c;
            critWrapper.dataType = ruleCriteria[0].FieldType__c;
            critWrapper.value = ruleCriteria[0].Value__c;
            critWrapper.sobjectType = ruleCriteria[0].SObject_Type__c;
            critWrapper.id = ruleCriteria[0].Id;
        }
        
        return JSON.serialize(critWrapper);
    }
    
    
     /*
     * 
     * createRuleEntry
     * 
     * this method takes in a json object and rule Id
     * to create an assignment rule entry
     * used when create a new rule entry
     * 
     * @param String entryJSON - json object with entries to delete
     * @param String ruleId - assignment rule Id
     * 
     */ 
    @AuraEnabled
    public static void createRuleEntry(String entryJSON, String ruleId){
        AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper = (AssignmentRuleWrapperObjects.EntryCriteriaWrapper) JSON.deserialize(entryJSON, AssignmentRuleWrapperObjects.EntryCriteriaWrapper.class);
        Assignment_Rule_Criteria_Based_Rule__c ruleCriteria = new Assignment_Rule_Criteria_Based_Rule__c();
        
        ruleCriteria.Field__c = critWrapper.field;
        ruleCriteria.Operator__c = critWrapper.operator;
        ruleCriteria.Field_Label__c = critWrapper.fieldLabel;
        ruleCriteria.FieldType__c = critWrapper.dataType;
        ruleCriteria.Value__c = critWrapper.value;
        ruleCriteria.SObject_Type__c = critWrapper.sobjectType;
        ruleCriteria.Assignment_Rule__c = ruleId;
        ruleCriteria.RecordTypeId = assignmentCritRecTypeId;
        
        insert ruleCriteria;
    }
    
     /*
     * 
     * upsertRuleEntry
     * 
     * this method takes in a json object and rule Id
     * to create / update an assignment rule entry
     * used when editing rule entry
     * 
     * @param String entryJSON - json object with entries to delete
     * @param String ruleId - assignment rule Id
     * 
     */ 
    @AuraEnabled
    public static void upsertRuleEntry(String entryJSON, String ruleId){
        AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper = (AssignmentRuleWrapperObjects.EntryCriteriaWrapper) JSON.deserialize(entryJSON, AssignmentRuleWrapperObjects.EntryCriteriaWrapper.class);
        Assignment_Rule_Criteria_Based_Rule__c ruleCriteria = new Assignment_Rule_Criteria_Based_Rule__c();
        
        if(critWrapper.id != null){
            ruleCriteria.Id = critWrapper.id;
        }
        
        ruleCriteria.Field__c = critWrapper.field;
        ruleCriteria.Operator__c = critWrapper.operator;
        ruleCriteria.Field_Label__c = critWrapper.fieldLabel;
        ruleCriteria.FieldType__c = critWrapper.dataType;
        ruleCriteria.Value__c = critWrapper.value;
        ruleCriteria.Assignment_Rule__c = ruleId;
        ruleCriteria.SObject_Type__c = critWrapper.sobjectType;
        ruleCriteria.RecordTypeId = assignmentCritRecTypeId;
        
        if(critWrapper.id != null){
            ruleCriteria.Id = critWrapper.id;
            update ruleCriteria;
        }else{
            insert ruleCriteria;
        } 
    }
    
    /*
     * 
     * deleteRuleEntry
     * 
     * this method takes in a json object that contains all the
     * rules entries to be deleted, and deletes them
     * 
     * @param String entryJSON - json object with entries to delete
     * 
     */ 
    @AuraEnabled
    public static void deleteRuleEntry(String entryJSON){
        AssignmentRuleWrapperObjects.EntryCriteriaWrapper critWrapper = (AssignmentRuleWrapperObjects.EntryCriteriaWrapper) JSON.deserialize(entryJSON, AssignmentRuleWrapperObjects.EntryCriteriaWrapper.class);
        Assignment_Rule_Criteria_Based_Rule__c ruleCriteria = new Assignment_Rule_Criteria_Based_Rule__c();
        if(critWrapper.id != null){
            ruleCriteria.Id = critWrapper.id;
        }
        delete ruleCriteria;
    }
}