src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>RFI_Attributes__c</fullName>
        <label>RFI Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Athletics</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Military / Veteran</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFI_Version__c</fullName>
        <label>RFI Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Post-Trad</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>University level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAS</fullName>
                </value>
                <value>
                    <fullName>Post-Trad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Detail__c</fullName>
        <label>Source Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Source_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>State Fair</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>ACT - Purchased</fullName>
                </value>
                <value>
                    <fullName>ACT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>ActSix</fullName>
                </value>
                <value>
                    <fullName>Admitted Student Overnight</fullName>
                </value>
                <value>
                    <fullName>All State Music</fullName>
                </value>
                <value>
                    <fullName>Alumni</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Boys Basketball</fullName>
                </value>
                <value>
                    <fullName>Boys Soccer</fullName>
                </value>
                <value>
                    <fullName>Business Academy</fullName>
                </value>
                <value>
                    <fullName>Cappex</fullName>
                </value>
                <value>
                    <fullName>CASPA</fullName>
                </value>
                <value>
                    <fullName>CBSS</fullName>
                </value>
                <value>
                    <fullName>CCCU</fullName>
                </value>
                <value>
                    <fullName>Chegg/Zinch</fullName>
                </value>
                <value>
                    <fullName>Christian Connector</fullName>
                </value>
                <value>
                    <fullName>CLT - Purchased</fullName>
                </value>
                <value>
                    <fullName>CLT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>Coach</fullName>
                </value>
                <value>
                    <fullName>College Board</fullName>
                </value>
                <value>
                    <fullName>College in the Schools</fullName>
                </value>
                <value>
                    <fullName>College Raptor</fullName>
                </value>
                <value>
                    <fullName>College Transcripts</fullName>
                </value>
                <value>
                    <fullName>Community College</fullName>
                </value>
                <value>
                    <fullName>Consortium</fullName>
                </value>
                <value>
                    <fullName>Converge</fullName>
                </value>
                <value>
                    <fullName>Cross Country</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Conferences &amp; Fairs</fullName>
                </value>
                <value>
                    <fullName>Event &amp; Visits</fullName>
                </value>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Camps</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>List &amp; Vendor</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Registrar</fullName>
                </value>
                <value>
                    <fullName>Transcripts</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Office Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Events_and_Conferences</fullName>
        <active>true</active>
        <description>Counselor Events and Conference Visits</description>
        <label>Events and Conferences</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/classes/CampaignRFIFormControllerTest.cls
/**
 * Created by ejc84332 on 2019-08-15.
 */

@isTest
public with sharing class CampaignRFIFormControllerTest {

    static Id recTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Events_and_Conferences').getRecordTypeId();

    static testMethod void testController(){

        Campaign rfi_campaign = new Campaign(RecordTypeId = recTypeId, Name='RFI Campaign Name', RFI_Version__c='Post-Trad', Source_Type__c='Event & Visits', Source_Detail__c='Other', School__c='CAS', RFI_Attributes__c='Legacy');

        insert rfi_campaign;
        //create the controller to pass into apex class
        ApexPages.currentPage().getParameters().put('CampaignId', rfi_campaign.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(rfi_campaign);
        CampaignRFIFormController controller = new CampaignRFIFormController(sc);

        // not sure if this is the right thing to do, but call all the functions.CampaignRFIFormControllerTest
        controller.getSchoolOptions();
        controller.getGrad_years();
        controller.getPrograms();

        controller.save();

        //after save the page should be redirected to a new landing page.
//        System.debug(ref.getUrl());

    }


}