src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Term__c</fullName>
        <description>Term new program should start to be used</description>
        <inlineHelpText>Term new program should start to be used</inlineHelpText>
        <label>New Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Program)</relationshipLabel>
        <relationshipName>CaseProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>SSR_Readmission</fullName>
        <active>true</active>
        <businessProcess>SSR</businessProcess>
        <label>SSR - Readmission</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cohort__c.object
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Alien_Registration_Number_Date__c</fullName>
        <description>The Alien Registration Number Date if person is a Permanent Resident Alien</description>
        <inlineHelpText>The Alien Registration Number Date if person is a Permanent Resident Alien</inlineHelpText>
        <label>Alien Registration Number Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Alien_Registration_Number__c</fullName>
        <description>The Alien Registration Number if person is a Permanent Resident Alien</description>
        <inlineHelpText>The Alien Registration Number if person is a Permanent Resident Alien</inlineHelpText>
        <label>Alien Registration Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner_Id__c</fullName>
        <description>Banner identifier for this person</description>
        <externalId>true</externalId>
        <inlineHelpText>Banner identifier for this person</inlineHelpText>
        <label>Banner ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Specifies the U.S. Citizenship status</description>
        <inlineHelpText>Specifies the U.S. Citizenship status</inlineHelpText>
        <label>U. S. Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident Alien</fullName>
                </value>
                <value>
                    <fullName>Not Citizen or Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Foreign Citizen</fullName>
                    <isActive>false</isActive>
                    <label>Foreign Citizen</label>
                </value>
                <value>
                    <fullName>Non Resident</fullName>
                    <isActive>false</isActive>
                    <label>Non Resident</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Permanent U.S. Resident</fullName>
                    <isActive>false</isActive>
                    <label>Permanent U.S. Resident</label>
                </value>
                <value>
                    <fullName>Temporary U.S. Resident</fullName>
                    <isActive>false</isActive>
                    <label>Temporary U.S. Resident</label>
                </value>
                <value>
                    <fullName>U.S. Citizen</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Citizen</label>
                </value>
                <value>
                    <fullName>U.S. Dual Citizen</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Dual Citizen</label>
                </value>
                <value>
                    <fullName>U.S. Permanent</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Permanent</label>
                </value>
                <value>
                    <fullName>U.S. Permanent Resident</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Permanent Resident</label>
                </value>
                <value>
                    <fullName>Y</fullName>
                    <isActive>false</isActive>
                    <label>Y</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conviction_Description__c</fullName>
        <label>Description of Conviction</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Hispanic__c</fullName>
        <description>Specifies if the person considers themselves to be Hispanic or Latino</description>
        <inlineHelpText>Specifies if the person considers themselves to be Hispanic or Latino</inlineHelpText>
        <label>Is Hispanic or Latino</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Veteran__c</fullName>
        <description>Specifies if the person is a Veteran or is eligible for military benefits</description>
        <inlineHelpText>Specifies if the person is a Veteran or is eligible for military benefits</inlineHelpText>
        <label>Is Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pled_Guilty__c</fullName>
        <label>Has Pled Guilty to a Crime</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visa_Type_Code__c</fullName>
        <description>The Intended Visa status if person is not a Not Citizen or Permanent Resident</description>
        <inlineHelpText>The Intended Visa status if person is not a Not Citizen or Permanent Resident</inlineHelpText>
        <label>Visa Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AS - Aslyum granted</fullName>
                </value>
                <value>
                    <fullName>AS - Asylum granted</fullName>
                </value>
                <value>
                    <fullName>AS - Asylum granted; B2 - Tourist</fullName>
                    <isActive>false</isActive>
                    <label>AS - Asylum granted; B2 - Tourist</label>
                </value>
                <value>
                    <fullName>B-2</fullName>
                </value>
                <value>
                    <fullName>B2 - Tourist</fullName>
                </value>
                <value>
                    <fullName>F1 - Student</fullName>
                </value>
                <value>
                    <fullName>F-1 Student</fullName>
                </value>
                <value>
                    <fullName>F-2</fullName>
                </value>
                <value>
                    <fullName>H1 - Special employee</fullName>
                </value>
                <value>
                    <fullName>H4 - Spouse of employee</fullName>
                </value>
                <value>
                    <fullName>I-94 Refugee</fullName>
                </value>
                <value>
                    <fullName>J1 - Exchange scholar</fullName>
                </value>
                <value>
                    <fullName>J2 - Dependent of exchange scholar</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>R-2</fullName>
                </value>
                <value>
                    <fullName>Refugee</fullName>
                </value>
                <value>
                    <fullName>TP - Temporary protection status</fullName>
                </value>
                <value>
                    <fullName>Undocumented</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Race__c</fullName>
        <label>Race</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian or Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>White</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Social_Security_Number__c</fullName>
        <label>Social Security Number</label>
        <length>12</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>hed__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <inlineHelpText>See &apos;Preferred Phone&apos; field.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employment_History__c.object
<CustomObject>
    <description>This represents an employment history for a contact. The employer may be an Business Organization Account if found.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Contact for which this employment history belongs</description>
        <inlineHelpText>The Contact for which this employment history belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employment Histories</relationshipLabel>
        <relationshipName>Employment_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer_Address__c</fullName>
        <description>Employer Address information for re-enrollment</description>
        <label>Employer Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <description>The Employer Name</description>
        <label>Employer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <description>Your title/primary responsibilities question for re-enrollment</description>
        <label>Responsibilities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Employment History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Employment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Term_Start_Date__c</fullName>
        <description>Used for Conga reports</description>
        <formula>Academic_Term__r.Term_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Academic Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Choose_Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <isActive>false</isActive>
        <label>Y</label>
    </customValue>
    <description>Picklist with a choice between yes or no</description>
    <masterLabel>Choose Yes/No</masterLabel>
</GlobalValueSet>

src/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>Permanent Resident Alien</fullName>
    </customValue>
    <customValue>
        <fullName>Not Citizen or Permanent Resident</fullName>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adult Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>Seminary</fullName>
    </customValue>
    <customValue>
        <fullName>Undergraduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
        <isActive>false</isActive>
        <label>School of Education</label>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
        <isActive>false</isActive>
        <label>School of Business</label>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
        <isActive>false</isActive>
        <label>College of Health Professions</label>
    </customValue>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
        <isActive>false</isActive>
        <label>College of Arts and Sciences</label>
    </customValue>
    <customValue>
        <fullName>College of Adult and Professional Studies</fullName>
        <isActive>false</isActive>
        <label>College of Adult and Professional Studies</label>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/classes/ReAdmissionHelper.cls
public without sharing class ReAdmissionHelper {
    public static void updateContact(Contact sourceContact, Contact targetContact) {
        if (String.isNotBlank(sourceContact.FirstName)) targetContact.FirstName = sourceContact.FirstName;
        if (String.isNotBlank(sourceContact.MiddleName)) targetContact.MiddleName = sourceContact.MiddleName;
        if (String.isNotBlank(sourceContact.LastName)) targetContact.LastName = sourceContact.LastName;
        if (String.isNotBlank(sourceContact.Email)) targetContact.Email = sourceContact.Email;
        if (String.isNotBlank(sourceContact.MailingStreet)) targetContact.MailingStreet = sourceContact.MailingStreet;
        if (String.isNotBlank(sourceContact.MailingCity)) targetContact.MailingCity = sourceContact.MailingCity;
        if (String.isNotBlank(sourceContact.MailingStateCode)) targetContact.MailingStateCode = sourceContact.MailingStateCode;
        if (String.isNotBlank(sourceContact.MailingCountryCode)) targetContact.MailingCountryCode = sourceContact.MailingCountryCode;
        if (String.isNotBlank(sourceContact.MailingPostalCode)) targetContact.MailingPostalCode = sourceContact.MailingPostalCode;
        if (String.isNotBlank(sourceContact.HomePhone)) targetContact.HomePhone = sourceContact.HomePhone;
        if (String.isNotBlank(sourceContact.MobilePhone)) targetContact.MobilePhone = sourceContact.MobilePhone;
        if (String.isNotBlank(sourceContact.hed__Gender__c)) targetContact.hed__Gender__c = sourceContact.hed__Gender__c;
        if (String.isNotBlank(sourceContact.hed__Race__c)) targetContact.hed__Race__c = sourceContact.hed__Race__c;
        if (String.isNotBlank(sourceContact.hed__Social_Security_Number__c)) targetContact.hed__Social_Security_Number__c = sourceContact.hed__Social_Security_Number__c;
        if (String.isNotBlank(sourceContact.hed__WorkPhone__c)) targetContact.hed__WorkPhone__c = sourceContact.hed__WorkPhone__c;
        if (String.isNotBlank(sourceContact.Alien_Registration_Number__c)) targetContact.Alien_Registration_Number__c = sourceContact.Alien_Registration_Number__c;
        if (sourceContact.Alien_Registration_Number_Date__c != null) targetContact.Alien_Registration_Number_Date__c = sourceContact.Alien_Registration_Number_Date__c;
        if (String.isNotBlank(sourceContact.Banner_Id__c)) targetContact.Banner_Id__c = sourceContact.Banner_Id__c;
        if (String.isNotBlank(sourceContact.Citizenship__c)) targetContact.Citizenship__c = sourceContact.Citizenship__c;
        if (String.isNotBlank(sourceContact.Conviction_Description__c)) targetContact.Conviction_Description__c = sourceContact.Conviction_Description__c;
        if (String.isNotBlank(sourceContact.Is_Hispanic__c)) targetContact.Is_Hispanic__c = sourceContact.Is_Hispanic__c;
        if (String.isNotBlank(sourceContact.Is_Veteran__c)) targetContact.Is_Veteran__c = sourceContact.Is_Veteran__c;
        if (String.isNotBlank(sourceContact.Pled_Guilty__c)) targetContact.Pled_Guilty__c = sourceContact.Pled_Guilty__c;
        if (String.isNotBlank(sourceContact.Visa_Type_Code__c)) targetContact.Visa_Type_Code__c = sourceContact.Visa_Type_Code__c;
    }

    public static Case createCase(Contact theContact, ReAdmissionController.ReAdmissionRequest request, Id theCohortId) {
        Case c = new Case(
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SSR_Readmission').getRecordTypeId(),
            ContactId = theContact.Id,
            Cohort__c = theCohortId,
            Type = 'Readmission',
            Status = 'New',
            Priority = 'High',
            Origin = 'Online Form',
            Subject = ' Re-enrollment Application - ' + theContact.Name,
            Description = 'Re-enrollment application webform submission',
            School__c = request.school,
            Program__c = request.program,
            New_Term__c = request.term,
            Will_Apply_For_Financial_Aid__c = (request.financialAid == 'Yes'),
            Collection_Holds__c = (request.hasBusinessOffice == 'Yes'),
            Has_Information_Changed__c = (request.hasChanged == 'Yes'),
            Why_Left_Essay__c = request.whyLeftEssay,
            Why_Returning_Essay__c = request.whyBackEssay
        );
        return c;

    }

    public static void assignCase(Case c) {

		List<QueueSObject> queues = [SELECT Id, Queue.Id, Queue.Name, Queue.Type, Queue.DeveloperName FROM QueueSObject WHERE Queue.Type ='Queue' AND Queue.DeveloperName = 'SSR_Advising'];
        if (queues != null && !queues.isEmpty()){
            c.OwnerId = queues[0].Queue.Id;
	    }
    }

    public static ContentVersion attachDocument(Case c, Blob body, String name) {

        ContentVersion theContentVersion = new ContentVersion();
        theContentVersion.ContentLocation = 'S'; // S = Stored in Salesforce
        theContentVersion.PathOnClient = name;
        theContentVersion.Title = name;
        theContentVersion.VersionData = body;
        theContentVersion.FirstPublishLocationId = c.Id;
        insert theContentVersion;
        return theContentVersion;
    }

    public static Employment_History__c createEmploymentHistory(Contact c, String name, String address, String responsibilities) {
        Employment_History__c history = new Employment_History__c(
            Contact__c = c.Id,
            Employer_Name__c = name,
            Employer_Address__c = address, 
            Responsibilities__c = responsibilities
        );
        insert history;
        return history;
    }

    public static Id findCohort(Id contactId) {
        Id theCohort = null;
        List<Opportunity> opps = [
            SELECT 
                Id, Name, StageName, Cohort__c, Contact__c 
            FROM 
                Opportunity 
            WHERE 
                Contact__c = :contactId AND Cohort__c != null AND StageName = 'Enrolled'
            ORDER BY 
                Academic_Term_Start_Date__c DESC
        ];
        if (!opps.isEmpty()) {
            theCohort = opps[0].Cohort__c;
        }
        return theCohort;
    }
}