src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assign_SSR_Advising__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used in a workflow to assign Cases to a queue when generated with a button</description>
        <label>Assign: SSR Advising</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Program_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Academic_Interests__c</fullName>
        <description>A coma separated list of Academic Interests, from RFI Forms, Tell Me More cards, etc.</description>
        <label>All Academic Interests</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Interactions (Secondary Academic Program)</relationshipLabel>
        <relationshipName>InteractionsSecondary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Academic Program Account that maps to this Program</description>
        <inlineHelpText>The Academic Program Account that maps to this Program</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs (Academic Program)</relationshipLabel>
        <relationshipName>Academic_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TDTM_Create_Case_Tasks.cls
/**
 * Created by ejc84332 on 2019-03-30.
 */

@IsTest
private class Test_TDTM_Create_Case_Tasks {

//private static Interaction__c select_int(String int_id){
//return [SELECT Id, All_Academic_Interests__c, Academic_Program__r.Id, Secondary_Academic_Program__c FROM Interaction__c WHERE Id = :int_id];
//}

    @IsTest
    static void test_create_case_tasks() {

        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Create_Case_Tasks', 'Case', 'AfterInsert;AfterUpdate', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        // have to do this to ssr_record_type to get the assignment rules working?
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.assignmentRuleHeader.useDefaultRule = false;

        Id petition_record_type = Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSR - Academic Petition').getRecordTypeId();
        Id commencement_record_type = Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSR - Commencement').getRecordTypeId();
        Id ssr_record_type = Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSR - Student Success Case').getRecordTypeId();
        Id its_program_record_type = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ITS - Create/Edit Program').getRecordTypeId();

        User test_user = BethelTestDataFactory.createTestUser(BethelTestDataFactory.getStandardProfile().Id, 'test', 'test');
        insert test_user;

        Case[] case_list = new List<Case>();
        case_list.add(new Case(recordTypeId = petition_record_type));
        case_list.add(new Case(recordTypeId = commencement_record_type));
        case_list.add(new Case(recordTypeId = its_program_record_type));
        case_list.add(new Case(recordTypeId = ssr_record_type, Type = 'Provisional Acceptance'));
        case_list.add(new Case(recordTypeId = ssr_record_type, Type = 'Retention', Assign_SSR_Advising__c=true));
        case_list.add(new Case(recordTypeId = ssr_record_type, Type = 'Schedule - Admissions', Assign_SSR_Advising__c=true));
        case_list.add(new Case(recordTypeId = ssr_record_type, Type = 'Conditional Acceptance', OwnerId=test_user.Id));
        case_list.add(new Case(recordTypeId = ssr_record_type, Type = 'Success Coaching'));
        for (Case c : case_list) {
            c.setOptions(dmo);
        }
        insert case_list;

        Test.startTest();
        for (Case c : case_list) {
            c.OwnerId = test_user.Id;
        }
        update case_list;
        for (Case c : case_list) {
            Task[] tasks = [SELECT Id FROM Task WHERE WhatId = :c.Id];
            if(tasks.isEmpty()){
                System.debug(c.Subject);
                System.debug('---------------------------------------------------');
                System.debug(its_program_record_type);
                System.debug(Schema.SObjectType.Case.getRecordTypeInfosByName().get('ITS - Create/Edit Program').getRecordTypeId());
                System.debug(c);
                System.debug(tasks);
                System.debug('---------------------------------------------------');

            }
            System.assert(!tasks.isEmpty());
        }
        Test.stopTest();
    }
}