src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Academic_History__c</fullName>
        <description>For Academic Appeals cases.</description>
        <inlineHelpText>Brief summary of relevant features of the student’s academic performance: credits attempted and earned, G.P.A., failed courses, etc. Synthesis of what the committee needs to know to evaluate the case</inlineHelpText>
        <label>Academic History</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Description__c</fullName>
        <label>Approval Description</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Petition_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No refund</fullName>
                </value>
                <value>
                    <fullName>Issue grace grant for full tuition</fullName>
                </value>
                <value>
                    <fullName>Issue grace grant for partial tuition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date_Formatted__c</fullName>
        <description>A better representation of CreatedDate, need a formula to easily show on the VisualForce page for Appeals cases.</description>
        <formula>LPAD(TEXT(MONTH(DATEVALUE(CreatedDate))), 2, &quot;0&quot;)   + &quot;-&quot; +
LPAD(TEXT(DAY(DATEVALUE(CreatedDate))), 2, &quot;0&quot;)     + &quot;-&quot; +
TEXT(YEAR(DATEVALUE(CreatedDate)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created Date Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decision_Maker_Name__c</fullName>
        <label>Decision Maker Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decision_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Decision Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Denial_Description__c</fullName>
        <description>Details on why an appeal was denied.</description>
        <inlineHelpText>Details on why an appeal was denied.</inlineHelpText>
        <label>Denial Description</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Petition_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Student was granted a prior extension and did not complete the degree requirements</fullName>
                </value>
                <value>
                    <fullName>Substitute course has different objectives than the course in our catalog</fullName>
                </value>
                <value>
                    <fullName>Substitute course was at a lower level than course in our catalog</fullName>
                </value>
                <value>
                    <fullName>Substitute course did not include important content provided in course that we provide</fullName>
                </value>
                <value>
                    <fullName>No room in class</fullName>
                </value>
                <value>
                    <fullName>Pace of class too intense to allow reasonable time to get work done</fullName>
                </value>
                <value>
                    <fullName>Other sections available</fullName>
                </value>
                <value>
                    <fullName>Student not yet qualified to be in class</fullName>
                </value>
                <value>
                    <fullName>Student participated in the class fully and no drop or withdrawal is justified</fullName>
                </value>
                <value>
                    <fullName>The changes to the curriculum are significant enough that the student would not be well served by completing old requirements</fullName>
                </value>
                <value>
                    <fullName>The courses are not available and suitable replacements cannot be identified</fullName>
                </value>
                <value>
                    <fullName>Student did not provide evidence or report circumstances sufficient to justify an exception to the policy</fullName>
                </value>
                <value>
                    <fullName>Student was granted a prior extension and did not complete the class</fullName>
                </value>
                <value>
                    <fullName>Student did not provide enough information about the course to justify a favorable decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Details_of_circumstances__c</fullName>
        <label>Details of circumstances</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>I_am_appealing_the_following__c</fullName>
        <description>Populated from a field on the Appeals Wufoo form.</description>
        <label>I am appealing the following:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>I_am_requesting_the_following__c</fullName>
        <description>Populated from Academic Appeals Wufoo form.</description>
        <label>I am requesting the following</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>If_yes_how_many_terms__c</fullName>
        <description>Populated from a field on the Appeals Wufoo form.</description>
        <label>If yes, how many terms?</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inputs_perspective__c</fullName>
        <description>Field for Academic Petitions.</description>
        <inlineHelpText>Briefly summarize feedback received from input providers listed above</inlineHelpText>
        <label>Input Provider&apos;s Perspective</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Instructor__c</fullName>
        <description>Populated from a field on the Appeals Wufoo form.</description>
        <label>Instructor</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Petition_Program__c</fullName>
        <description>The Program selected on the Academic Petition form.</description>
        <inlineHelpText>The Program the student selected on the Academic Petition wufoo form.</inlineHelpText>
        <label>Petition Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Petition_Type__c</fullName>
        <description>Populated from a field on the Academic Petition Wufoo form.</description>
        <label>Petition Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appeal - Academic Dismissal</fullName>
                </value>
                <value>
                    <fullName>Exception - Complete degree requirements from prior catalog year</fullName>
                </value>
                <value>
                    <fullName>Exception - Extension of time on credit expiration</fullName>
                </value>
                <value>
                    <fullName>Exception - Extension of time to complete degree</fullName>
                </value>
                <value>
                    <fullName>Exception - Grade Change</fullName>
                </value>
                <value>
                    <fullName>Exception - Late Add</fullName>
                </value>
                <value>
                    <fullName>Exception - Late drop without refund request</fullName>
                </value>
                <value>
                    <fullName>Exception - Late drop with refund request</fullName>
                </value>
                <value>
                    <fullName>Exception - Other academic policy</fullName>
                </value>
                <value>
                    <fullName>Exception - Required course or independent study substitution</fullName>
                </value>
                <value>
                    <fullName>Exception - Withdrawal past deadline without refund request</fullName>
                </value>
                <value>
                    <fullName>Exception - Withdrawal past deadline with refund request</fullName>
                </value>
                <value>
                    <fullName>Exception - Residency requirement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Academic_Dismissal__c</fullName>
        <description>Populated by an advisor to give context to the Case.</description>
        <label>Prior Academic Dismissal?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Academic_Probation__c</fullName>
        <description>Populated by an advisor to give context to the Case.</description>
        <label>Prior Academic Probation?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Registrar_Summary__c</fullName>
        <description>Populated by the Registrar to give context to the Case</description>
        <label>Registrar Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Used for Academic Petitions to state Decision Maker&apos;s role</description>
        <inlineHelpText>Decision Maker&apos;s Role at Bethel</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Program Director</fullName>
                </value>
                <value>
                    <fullName>Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supporting_Documentation2__c</fullName>
        <label>Supporting Documentation2</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Supporting_Documentation3__c</fullName>
        <label>Supporting Documentation3</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Supporting_Documentation4__c</fullName>
        <label>Supporting Documentation4</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Supporting_Documentation5__c</fullName>
        <label>Supporting Documentation5</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Supporting_Documentation__c</fullName>
        <label>Supporting Documentation</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Term_of_registration__c</fullName>
        <label>Term of registration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>approval_academic_year__c</fullName>
        <description>Academic year catalog the student may use to complete course requirements</description>
        <inlineHelpText>Student may complete requirements listed in the catalog for academic year:</inlineHelpText>
        <label>Approval - Academic Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>approval_course_substitution__c</fullName>
        <description>Approve substitution of requested course for course requirement (list)</description>
        <inlineHelpText>Approve substitution of requested course for course requirement (list)</inlineHelpText>
        <label>Approval - Course Substitution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>approval_extension_date__c</fullName>
        <description>Date an appealed extension is approved until</description>
        <inlineHelpText>Date an appealed extension is approved until</inlineHelpText>
        <label>Approval - Extension Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>approval_new_grade__c</fullName>
        <description>New grade for appeal</description>
        <inlineHelpText>Change grade to</inlineHelpText>
        <label>Approval - New Grade</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>approval_old_grade__c</fullName>
        <description>Current grade being appealed</description>
        <inlineHelpText>Change grade from</inlineHelpText>
        <label>Approval - Old Grade</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>grace_grant_amount__c</fullName>
        <description>Partial tuition being issued for a grace grant</description>
        <inlineHelpText>Issue grace grant for partial tuition in the amount of</inlineHelpText>
        <label>Approval - Grace Grant Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>grade_change_factors__c</fullName>
        <description>Factors justifying a grade change</description>
        <inlineHelpText>Factors justifying a grade change</inlineHelpText>
        <label>Approval - Grade Change Factors</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Late work accepted by professor</fullName>
                </value>
                <value>
                    <fullName>Late withdrawal allowed - grade changed to “W”</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Banner_Id__c</fullName>
        <description>Banner identifier for this person</description>
        <externalId>true</externalId>
        <inlineHelpText>Banner identifier for this person</inlineHelpText>
        <label>Banner ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Choose_Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <isActive>false</isActive>
        <label>Y</label>
    </customValue>
    <description>Picklist with a choice between yes or no</description>
    <masterLabel>Choose Yes/No</masterLabel>
</GlobalValueSet>

src/classes/AcademicPetitionDecisionForm.cls
/**
 * Created by phg49389 on 2019-04-29.
 */

public class AcademicPetitionDecisionForm {

    private Case editCase {get; set;}

    public AcademicPetitionDecisionForm(){
        String caseId = ApexPages.currentPage().getParameters().get('id');
        Case[] c = [
                SELECT Id, ContactId, Petition_Type__c, CaseNumber, Created_Date_Formatted__c,
                        Petition_Program__c, Course_Number__c, Instructor__c, Term_of_registration__c, I_am_appealing_the_following__c,
                        I_am_requesting_the_following__c, Details_of_circumstances__c, Academic_History__c,
                        Prior_Academic_Probation__c, If_yes_how_many_terms__c, Prior_Academic_Dismissal__c,
                        Inputs_perspective__c, Registrar_Summary__c, Decision_Maker_Name__c, Role__c, Decision__c,
                        Approval_Description__c, grace_grant_amount__c, approval_old_grade__c, approval_new_grade__c,
                        grade_change_factors__c, approval_academic_year__c, approval_extension_date__c,
                        approval_course_substitution__c, Denial_Description__c, Decision_Submitted__c,
                        Supporting_Documentation__c, Supporting_Documentation2__c, Supporting_Documentation3__c,
                        Supporting_Documentation4__c, Supporting_Documentation5__c
                FROM Case WHERE Id = :caseId
        ];
        editCase = c[0];
    }

    /*
        Setters and Getters
    */
    // Read-only fields that are read by the Decision Maker
    public String petitionType{
        get{
            return editCase.Petition_Type__c;
        }
        // Although it's read-only, petitionType needs a setter so that it can be used as a hidden input field
        set;
    }
    public String caseNumber{
        get{
            return editCase.CaseNumber;
        }
    }
    public String studentInfo{
        get{
            Contact student = [SELECT Id, FirstName, LastName, Banner_Id__c FROM Contact WHERE Id = :editCase.ContactId];
            return String.format('{0} {1}, {2}',
                    new List<Object> {student.FirstName, student.LastName, student.Banner_Id__c});
        }
    }
    public String createdDate{
        get{
            return editCase.Created_Date_Formatted__c;
        }
    }
    public String program{
        get{
            String pp = editCase.Petition_Program__c;
            return pp;
        }
    }
    public String courseNumber{
        get{
            String cn = editCase.Course_Number__c;
            return cn;
        }
    }
    public String instructor{
        get{
            String instructor = editCase.Instructor__c;
            return instructor;
        }
    }
    public String term{
        get{
            String term = editCase.Term_of_registration__c;
            return term;
        }
    }
    public String appealingTheFollowing{
        get{
            return editCase.I_am_appealing_the_following__c;
        }
    }
    public String requestingTheFollowing{
        get{
            return editCase.I_am_requesting_the_following__c;
        }
    }
    public String detailsCircumstances{
        get{
            return editCase.Details_of_circumstances__c;
        }
    }
    public String academicHistory{
        get{
            return editCase.Academic_History__c;
        }
    }
    public String priorAcademicProbation{
        get{
            return editCase.Prior_Academic_Probation__c;
        }
    }
    public String howManyTermsProbation{
        get{
            return editCase.If_yes_how_many_terms__c;
        }
    }
    public String priorAcademicDismissal{
        get{
            return editCase.Prior_Academic_Dismissal__c;
        }
    }
    public String inputsPerspective{
        get{
            return editCase.Inputs_perspective__c;
        }
    }
    public String registrarSummary{
        get{
            return editCase.Registrar_Summary__c;
        }
    }

    public String supportingDocumentation{
        get{
            return editCase.Supporting_Documentation__c;
        }
    }

    public String supportingDocumentation2{
        get{
            return editCase.Supporting_Documentation2__c;
        }
    }

    public String supportingDocumentation3{
        get{
            return editCase.Supporting_Documentation3__c;
        }
    }

    public String supportingDocumentation4{
        get{
            return editCase.Supporting_Documentation4__c;
        }
    }

    public String supportingDocumentation5{
        get{
            return editCase.Supporting_Documentation5__c;
        }
    }

    // Read/write fields that are used in the form submitted by the Decision Maker
    public String decisionMakerName{
        get{
            return editCase.Decision_Maker_Name__c;
        }
        set{
            editCase.Decision_Maker_Name__c = value;
        }
    }
    public String role{
        get{
            // This trick lets the selectList make the disabled "--None--" option the default
            if (editCase.Role__c == null){
                return 'None';
            }
            else {
                return editCase.Role__c;
            }
        }
        set{
            editCase.Role__c = value;
        }
    }
    public String decision{
        get{
            // This trick lets the selectList make the disabled "--None--" option the default
            if (editCase.Decision__c == null){
                return 'None';
            }
            else {
                return editCase.Decision__c;
            }
        }
        set{
            editCase.Decision__c = value;
        }
    }
    public String approvalDescription{
        get{
            // This trick lets the selectList make the disabled "--None--" option the default
            if (editCase.Approval_Description__c == null){
                return 'None';
            }
            else {
                return editCase.Approval_Description__c;
            }
        }
        set{
            editCase.Approval_Description__c = value;
        }
    }
    public String graceGrantAmount{
        get{
            return editCase.grace_grant_amount__c;
        }
        set{
            editCase.grace_grant_amount__c = value;
        }
    }
    public String approvalOldGrade{
        get{
            return editCase.approval_old_grade__c;
        }
        set{
            editCase.approval_old_grade__c = value;
        }
    }
    public String approvalNewGrade{
        get{
            return editCase.approval_new_grade__c;
        }
        set{
            editCase.approval_new_grade__c = value;
        }
    }
    public List<String> gradeChangeFactors{
        // This field gets stored internally as a String of semicolon-separated Strings.
        // In order to interface with the "apex:selectList multiple=true", it has to be
        // converted to and from an Array of Strings
        get {
            if (editCase.grade_change_factors__c == null){
                return new List<String>();
            }
            else{
                return editCase.grade_change_factors__c.split(';');
            }
        }
        set {
            Integer valueSize = value.size();
            if (valueSize > 0){
                String newValue = '';
                for(Integer i = 0; i < valueSize; i++){
                    newValue += value[i];
                    if (i < valueSize - 1){
                        newValue += ';';
                    }
                }
                editCase.grade_change_factors__c = newValue;
            }
            else {
                editCase.grade_change_factors__c = null;
            }
        }
    }
    public String approvalAcademicYear{
        get{
            return editCase.approval_academic_year__c;
        }
        set{
            editCase.approval_academic_year__c = value;
        }
    }
    public Date approvalExtensionDate{
        get{
            return editCase.approval_extension_date__c;
        }
        set{
            editCase.approval_extension_date__c = value;
        }
    }
    public String approvalCourseSubstitution{
        get{
            return editCase.approval_course_substitution__c;
        }
        set{
            editCase.approval_course_substitution__c = value;
        }
    }
    public String denialDescription{
        get{
            // This trick lets the selectList make the disabled "--None--" option the default
            if (editCase.Denial_Description__c == null){
                return 'None';
            }
            else {
                return editCase.Denial_Description__c;
            }
        }
        set{
            editCase.Denial_Description__c = value;
        }
    }
    public String comments{
        get{
            return '';
        }
//        set{
//            editCase.Comments__c = '';
//        }
    }

    /*
        Methods that get SelectOption Lists from picklist fields
        Sourced from https://salesforce.stackexchange.com/a/190969
    */
    public List<SelectOption> getroleOptions() {
        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Case.Role__c.getDescribe();

        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();

        if (editCase.Role__c == null){
            // Make the default first option "--None--" but make it disabled so that it can't be submitted
            optionsToReturn.add(new SelectOption('None', '--None--', true));
        }

        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive()) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsToReturn;
    }
    public List<SelectOption> getdecisionOptions() {
        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Case.Decision__c.getDescribe();

        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();

        if (editCase.Decision__c == null){
            // Make the default first option "--None--" but make it disabled so that it can't be submitted
            optionsToReturn.add(new SelectOption('None', '--None--', true));
        }

        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive()) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsToReturn;
    }
    public List<SelectOption> getgradeChangeFactorsOptions() {
        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Case.grade_change_factors__c.getDescribe();

        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();

        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive()) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsToReturn;
    }

    public List<SelectOption> getapprovalDescriptionDependentPicklistOptions(){
        Map<Object, List<String>> dependencies = getDependentPicklistValues(Case.Approval_Description__c);

        // Return an empty list if no values are valid for the current value of the controlling field
        if (!dependencies.keySet().contains(editCase.Petition_Type__c)){
            return new List<SelectOption>();
        }

        List<String> validOptionLabels = dependencies.get(editCase.Petition_Type__c);

        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Case.Approval_Description__c.getDescribe();

        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();

        if (editCase.Approval_Description__c == null){
            // Make the default first option "--None--" but make it disabled so that it can't be submitted
            optionsToReturn.add(new SelectOption('None', '--None--', true));
        }

        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive() && validOptionLabels.contains(pEntry.getLabel())) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsToReturn;
    }
    public List<SelectOption> getdenialDescriptionDependentPicklistOptions(){
        Map<Object, List<String>> dependencies = getDependentPicklistValues(Case.Denial_Description__c);

        // Return an empty list if no values are valid for the current value of the controlling field
        if (!dependencies.keySet().contains(editCase.Petition_Type__c)){
            return new List<SelectOption>();
        }

        List<String> validOptionLabels = dependencies.get(editCase.Petition_Type__c);

        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Case.Denial_Description__c.getDescribe();

        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();

        if (editCase.Denial_Description__c == null){
            // Make the default first option "--None--" but make it disabled so that it can't be submitted
            optionsToReturn.add(new SelectOption('None', '--None--', true));
        }

        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive() && validOptionLabels.contains(pEntry.getLabel())) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsToReturn;
    }

    /*
        Proper methods
     */
    // Sourced from: https://developer.salesforce.com/forums/?id=906F00000008y8HIAQ
    private void sleep(Integer milliseconds){
        // Num milliseconds since Jan 1 1970
        Long startingTime = System.now().getTime();
        while (System.now().getTime() - startingTime < milliseconds)  {
            // Do nothing until desired delay has passed
        }
    }

    // Update the Case object in the backend and redirect to view the decision submitted
    public PageReference save() {
        editCase.Decision_Submitted__c = true;
        update editCase;

        PageReference redirectURL = new PageReference('/appeals/AcademicPetitionDecisionForm?id=' + editCase.Id);
        redirectURL.setRedirect(true);

        // Sleep for one second to make sure that the Case has time to update before re-rendering the page
        sleep(1000);

        return redirectURL;
    }

    /*
        Sourced from https://glyntalkssalesforce.blogspot.com/2018/08/dependent-picklist-values-in-apex.html

        Takes in one dependent field reference as argument, finds the field that controls its dependencies,
        and returns a list of what values the dependent field can have based on the controlling field's value.
        Sadly, does not return what the controlling field is. You have to either know it or figure it out.
     */
    private static Map<Object, List<String>> getDependentPicklistValues( Schema.SObjectField dependentField ){
        Schema.DescribeFieldResult depend = dependentField.getDescribe();
        Schema.SObjectField controllingField = depend.getController();
        if ( controllingField == null ) {
            return null;
        }
        Schema.DescribeFieldResult control = controllingField.getDescribe();
        List<Schema.PicklistEntry> controlEntries =
                (   control.getType() == Schema.DisplayType.BOOLEAN
                        ?   null
                        :   control.getPicklistValues()
                );

        String base64map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
        Map<Object, List<String>> dependentPicklistValues = new Map<Object, List<String>>();
        for ( Schema.PicklistEntry entry : depend.getPicklistValues() ) {
            if ( entry.isActive() ) {
                List<String> base64chars = String.valueOf(
                        ((Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(entry))).get('validFor')
                ).split('');
                if (base64chars.size() < 2){
                    // If size == 1, then this value does not have a controlling field value associated with it
                    continue;
                }
                for (Integer index = 0; index < (controlEntries != null ? controlEntries.size() : 2); index++) {
                    Object controlValue =
                            (   controlEntries == null
                                    ?   (Object) (index == 1)                              // Originally ".getLabel()"
                                    :   (Object) (controlEntries[index].isActive() ? controlEntries[index].getLabel() : null)
                            );
                    Integer bitIndex = index / 6;
                    Integer bitShift = 5 - Math.mod(index, 6);
                    if (controlValue == null || (base64map.indexOf(base64chars[bitIndex]) & (1 << bitShift)) == 0 ){
                        continue;
                    }
                    if (!dependentPicklistValues.containsKey(controlValue)) {
                        dependentPicklistValues.put(controlValue, new List<String>());
                    }                                   // Originally ".getLabel()"
                    dependentPicklistValues.get(controlValue).add(entry.getLabel());
                }
            }
        }
        return dependentPicklistValues;
    }
}