src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Alien_Registration_Number_Date__c</fullName>
        <description>The Alien Registration Number Date if person is a Permanent Resident Alien</description>
        <inlineHelpText>The Alien Registration Number Date if person is a Permanent Resident Alien</inlineHelpText>
        <label>Alien Registration Number Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Alien_Registration_Number__c</fullName>
        <description>The Alien Registration Number if person is a Permanent Resident Alien</description>
        <inlineHelpText>The Alien Registration Number if person is a Permanent Resident Alien</inlineHelpText>
        <label>Alien Registration Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Banner_Id__c</fullName>
        <description>Banner identifier for this person</description>
        <externalId>true</externalId>
        <inlineHelpText>Banner identifier for this person</inlineHelpText>
        <label>Banner ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Specifies the U.S. Citizenship status</description>
        <inlineHelpText>Specifies the U.S. Citizenship status</inlineHelpText>
        <label>U. S. Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident Alien</fullName>
                </value>
                <value>
                    <fullName>Not Citizen or Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Foreign Citizen</fullName>
                    <isActive>false</isActive>
                    <label>Foreign Citizen</label>
                </value>
                <value>
                    <fullName>Non Resident</fullName>
                    <isActive>false</isActive>
                    <label>Non Resident</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Permanent U.S. Resident</fullName>
                    <isActive>false</isActive>
                    <label>Permanent U.S. Resident</label>
                </value>
                <value>
                    <fullName>Temporary U.S. Resident</fullName>
                    <isActive>false</isActive>
                    <label>Temporary U.S. Resident</label>
                </value>
                <value>
                    <fullName>U.S. Citizen</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Citizen</label>
                </value>
                <value>
                    <fullName>U.S. Dual Citizen</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Dual Citizen</label>
                </value>
                <value>
                    <fullName>U.S. Permanent</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Permanent</label>
                </value>
                <value>
                    <fullName>U.S. Permanent Resident</fullName>
                    <isActive>false</isActive>
                    <label>U.S. Permanent Resident</label>
                </value>
                <value>
                    <fullName>Y</fullName>
                    <isActive>false</isActive>
                    <label>Y</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conviction_Description__c</fullName>
        <label>Description of Conviction</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Hispanic__c</fullName>
        <description>Specifies if the person considers themselves to be Hispanic or Latino</description>
        <inlineHelpText>Specifies if the person considers themselves to be Hispanic or Latino</inlineHelpText>
        <label>Is Hispanic or Latino</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Veteran__c</fullName>
        <description>Specifies if the person is a Veteran or is eligible for military benefits</description>
        <inlineHelpText>Specifies if the person is a Veteran or is eligible for military benefits</inlineHelpText>
        <label>Is Veteran</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pled_Guilty__c</fullName>
        <label>Has Pled Guilty to a Crime</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Choose_Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visa_Type_Code__c</fullName>
        <description>The Intended Visa status if person is not a Not Citizen or Permanent Resident</description>
        <inlineHelpText>The Intended Visa status if person is not a Not Citizen or Permanent Resident</inlineHelpText>
        <label>Visa Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AS - Aslyum granted</fullName>
                </value>
                <value>
                    <fullName>AS - Asylum granted</fullName>
                </value>
                <value>
                    <fullName>AS - Asylum granted; B2 - Tourist</fullName>
                    <isActive>false</isActive>
                    <label>AS - Asylum granted; B2 - Tourist</label>
                </value>
                <value>
                    <fullName>B-2</fullName>
                </value>
                <value>
                    <fullName>B2 - Tourist</fullName>
                </value>
                <value>
                    <fullName>F1 - Student</fullName>
                </value>
                <value>
                    <fullName>F-1 Student</fullName>
                </value>
                <value>
                    <fullName>F-2</fullName>
                </value>
                <value>
                    <fullName>H1 - Special employee</fullName>
                </value>
                <value>
                    <fullName>H4 - Spouse of employee</fullName>
                </value>
                <value>
                    <fullName>I-94 Refugee</fullName>
                </value>
                <value>
                    <fullName>J1 - Exchange scholar</fullName>
                </value>
                <value>
                    <fullName>J2 - Dependent of exchange scholar</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>R-2</fullName>
                </value>
                <value>
                    <fullName>Refugee</fullName>
                </value>
                <value>
                    <fullName>TP - Temporary protection status</fullName>
                </value>
                <value>
                    <fullName>Undocumented</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Race__c</fullName>
        <label>Race</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaska Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian or Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>White</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hed__Social_Security_Number__c</fullName>
        <label>Social Security Number</label>
        <length>12</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>hed__WorkPhone__c</fullName>
        <description>See &apos;Preferred Phone&apos; field.</description>
        <inlineHelpText>See &apos;Preferred Phone&apos; field.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Choose_Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <isActive>false</isActive>
        <label>Y</label>
    </customValue>
    <description>Picklist with a choice between yes or no</description>
    <masterLabel>Choose Yes/No</masterLabel>
</GlobalValueSet>

src/classes/ContactHelper.cls
public class ContactHelper {
    public static Contact getContact(Id theId) {
        Contact c = null;
        List<Contact> contacts = [
            Select 
                Id, Name, 
                FirstName, 
                MiddleName,
                LastName,
                Email,
                MailingStreet,
                MailingCity,
                MailingState,
                MailingStateCode,
                MailingCountry,
                MailingCountryCode,
                MailingPostalCode,
                HomePhone,
                MobilePhone,
                hed__Gender__c,
                hed__Race__c,
                hed__Social_Security_Number__c,
                hed__WorkPhone__c,
                Alien_Registration_Number__c,
                Alien_Registration_Number_Date__c,
                Banner_Id__c,
                Citizenship__c,
                Conviction_Description__c,
                Is_Hispanic__c,
                Is_Veteran__c,
                Pled_Guilty__c,
                Visa_Type_Code__c
            FROM 
                Contact
            WHERE
                Id = :theId
        ];
        if (contacts != null && !contacts.isEmpty()) {
            c = contacts[0];
        }
        return c;
    }

    public static Map<Id, Contact> getContactMap(Set<Id> theIds) {
        Map<Id, Contact> contacts = new Map<Id, Contact>([
            Select 
                Id, 
                FirstName, 
                LastName,
                Email,
                MailingState,
                MailingStateCode,
                MailingCountry,
                MailingCountryCode,
                Citizenship__c
            FROM 
                Contact
            WHERE
                Id IN :theIds
        ]);
        return contacts;
    }

    public static Contact getContactFromBethelId(String theId) {
        Contact c = null;
        List<Contact> contacts = [
            SELECT 
                Id, Name, 
                FirstName, 
                MiddleName,
                LastName,
                Email,
                MailingStreet,
                MailingCity,
                MailingState,
                MailingStateCode,
                MailingCountry,
                MailingCountryCode,
                MailingPostalCode,
                HomePhone,
                MobilePhone,
                hed__Gender__c,
                hed__Race__c,
                hed__Social_Security_Number__c,
                hed__WorkPhone__c,
                Alien_Registration_Number__c,
                Alien_Registration_Number_Date__c,
                Banner_Id__c,
                Citizenship__c,
                Conviction_Description__c,
                Is_Hispanic__c,
                Is_Veteran__c,
                Pled_Guilty__c,
                Visa_Type_Code__c
            FROM 
                Contact
            WHERE
                Banner_Id__c = :theId
        ];
        if (contacts != null && !contacts.isEmpty()) {
            c = contacts[0];
        }
        return c;
    }
}