src/objects/Event_Log__c.object
<CustomObject>
    <description>Generic object used to log events</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mogli_SMS__SMS__c.object
<CustomObject>
    <fields>
        <fullName>Event_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Log</label>
        <referenceTo>Event_Log__c</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCreateSMS.cls
/**
 * Created by bej68982 on 3/19/20.
 */

public class BatchCreateSMS implements Database.Batchable<sObject>, Database.Stateful {

    public List <Mogli_SMS__SMS__c> smsRecordsToCreate = new List<Mogli_SMS__SMS__c>();
    public Event_Log__c eventLog;
    public String apexlog = '';

    public BatchCreateSMS(List<Mogli_SMS__SMS__c> smsRecords, Event_Log__c log){
        smsRecordsToCreate = smsRecords;
        eventLog = log;
    }

    public List<Mogli_SMS__SMS__c> start(Database.BatchableContext bc) {
        return smsRecordsToCreate;
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope){
        Database.SaveResult[] srList = Database.insert(scope, false);

        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                apexlog += 'Successfully created SMS record: ' + sr.getId() + '\R';
            }
            else {
                for(Database.Error err : sr.getErrors()) {
                    apexlog += 'SMS ID: ' + sr.getId() + ': ' + err.getStatusCode() + ': ' + err.getMessage() + '\R';
                }
            }
        }
    }

    public void finish(Database.BatchableContext bc){
        eventLog.Status__c = 'Completed';
        update eventLog;

        If(apexlog != ''){
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S';
            conVer.PathOnClient = 'ApexLog.txt';
            conVer.Title = 'Apex Log';
            conVer.VersionData = Blob.valueOf(apexlog);
            insert conVer;

            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;

            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = eventLog.Id;
            conDocLink.ContentDocumentId = conDoc;
            conDocLink.shareType = 'V';
            insert conDocLink;
        }
    }

}