src/objects/Family_Member__c.object
<CustomObject>
    <description>This object represents a family member for a person</description>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person to which the this person is related to</description>
        <inlineHelpText>The person to which the this person is related to</inlineHelpText>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Families1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Family Member</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/hed__Relationship__c.object
<CustomObject>
    <description>Connection between two Contacts.</description>
    <fields>
        <fullName>hed__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Contact is this Contact&apos;s ______.</description>
        <inlineHelpText>Related Contact is this Contact&apos;s ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TDTM_Create_Relationship.cls
/**
 * Created by joj28267 on 3/9/20.
 */

global class TDTM_Create_Relationship extends TDTMVirtualTriggerHandler {

    global override void onAfterInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        System.debug('starting onAfterInsert TDTM_Create_Relationship');

        // Get family member(s) from newList
        Family_Member__c family_member = (Family_Member__c)newList[0];

        // List of Relationship objects to add
        List<hed__Relationship__c> new_relationships = new List<hed__Relationship__c>();

        // Add relationship
        new_relationships.add(new hed__Relationship__c(
                hed__Contact__c = family_member.Related_Contact__c,  // Id of contact
                hed__Contact__r = family_member.Related_Contact__r  // Contact
        ));

        if(new_relationships.size() > 0){
            insert new_relationships;
        }
    }

}