src/objects/Field_Map__c.object
<CustomObject>
    <label>Field Map</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>Field Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field_Map_Value__c.object
<CustomObject>
    <fields>
        <fullName>Field_Map__c</fullName>
        <label>Field Map</label>
        <referenceTo>Field_Map__c</referenceTo>
        <relationshipLabel>Field Map Values</relationshipLabel>
        <relationshipName>Field_Map_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <label>SObject Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Field_Map_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Map Value</label>
    <nameField>
        <displayFormat>FMV-{00000}</displayFormat>
        <label>Field Map Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Map Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FieldValueMapEditUserCmpController.cls
public class FieldValueMapEditUserCmpController {
    
    /*
     * 
     * getUserInfo
     * 
     * retrieves the user from a field value map based on id passed in
     * 
     * @param string recordId - id of field value map record
     * @return String json of field value map
     * 
     */ 
    @AuraEnabled(cacheable=true)
    public static string getUserInfo(String recordId){
        Field_Map_Value__c fmv = [SELECT User__c, User__r.Name FROM Field_Map_Value__c WHERE id =: recordId];
        return JSON.serialize(fmv);
    }	
    
    
     /*
     * 
     * updateValueMap
     * 
     * retrieves the user from a field value map based on id passed in
     * 
     * @param string recordId - id of field value map record
     * @param string userId - user id to assign to field value map
     * @param string fieldMapId - id of parent field map
     * @param sobjectType - sobject type for field value map
     * 
     */ 
    @AuraEnabled
    public static void updateValueMap(String recordId, String userId, String fieldMapId, String sobjectType){
        if(String.isEmpty(recordId)){
            Field_Map_Value__c fmv = new Field_Map_Value__c(Field_Map__c = fieldMapId, User__c = userId, SObject_Type__c = sobjectType);
            insert fmv;
        }else{
            Field_Map_Value__c fmv = new Field_Map_Value__c(Id = recordId, User__c = userId);
            update fmv;
        }
    }
    
}