src/objects/Field_Map__c.object
<CustomObject>
    <label>Field Map</label>
    <nameField>
        <displayFormat>FM-{00000}</displayFormat>
        <label>Field Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field_Map_Value__c.object
<CustomObject>
    <fields>
        <fullName>Field_Map__c</fullName>
        <label>Field Map</label>
        <referenceTo>Field_Map__c</referenceTo>
        <relationshipLabel>Field Map Values</relationshipLabel>
        <relationshipName>Field_Map_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Field_Map_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Map Value</label>
    <nameField>
        <displayFormat>FMV-{00000}</displayFormat>
        <label>Field Map Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Map Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestFieldValueMapEditUserCmpCntrler.cls
@isTest
public class TestFieldValueMapEditUserCmpCntrler {
    
    @testSetup
    static void testSetup(){
        TestUtility.setupTestData();
    }
    
    static testMethod void testGetUserInfo(){
        Field_Map_Value__c fmv = [SELECT id, User__c FROM Field_Map_Value__c Limit 1];
       	test.startTest();
        String userInfo = FieldValueMapEditUserCmpController.getUserInfo(fmv.Id);
        test.stopTest();
        fmv = (Field_Map_Value__c) JSON.deserialize(userInfo, Field_Map_Value__c.class);
        System.assert(fmv != null);
        System.assert(fmv.User__c != null);
    }
    
    static testMethod void testUpdateValueMap(){
        Field_Map_Value__c fmv = [SELECT id, User__c, Field_Map__c FROM Field_Map_Value__c Limit 1];
        Integer count = [SELECT COUNT() FROM Field_Map_Value__c];
        test.startTest();
        FieldValueMapEditUserCmpController.updateValueMap(null, UserInfo.getUserId(), fmv.Field_Map__c, 'Account'); // creates a new field value map record
        FieldValueMapEditUserCmpController.updateValueMap(fmv.Id, UserInfo.getUserId(), fmv.Field_Map__c, 'Account'); // updates an existing field value map recod
        test.stopTest();
        //we should have create 1 new field value map, so count  + 1
        System.assertEquals(count + 1, [SELECT COUNT() FROM Field_Map_Value__c]);
        
    }

}