src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>ACT_Test_Results__c</fullName>
        <defaultValue>&quot;none&quot;</defaultValue>
        <description>Data from ACT. Should be loaded from the &quot;ACT Summary&quot; of the ACT Parser Excel document.</description>
        <label>ACT Test Results</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Status__c</fullName>
        <description>When set to &quot;New,&quot; the Interaction Processor runs, then updates the Status based on the result to &quot;Imported&quot; or &quot;Audit Needed.&quot;</description>
        <inlineHelpText>Set the Status to &quot;New&quot; and save to kick off the Interaction process.</inlineHelpText>
        <label>Interaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Audit Required</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>The way in which the Lead or Contact&apos;s information was first received. Value &quot;Office Visit&quot; is required by the Interactions package tests.</description>
        <inlineHelpText>Indicate the initial source of this data.</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Camps</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Conferences &amp; Fairs</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event &amp; Visits</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>List &amp; Vendor</fullName>
                </value>
                <value>
                    <fullName>Office Visit</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Registrar</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Transcripts</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Detail__c</fullName>
        <description>Sub-field of Source Type.</description>
        <label>Source Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_Source__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACT - Purchased</fullName>
                </value>
                <value>
                    <fullName>ACT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>ActSix</fullName>
                </value>
                <value>
                    <fullName>Admitted Student Overnight</fullName>
                </value>
                <value>
                    <fullName>All State Music</fullName>
                </value>
                <value>
                    <fullName>Alumni</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Boys Basketball</fullName>
                </value>
                <value>
                    <fullName>Boys Soccer</fullName>
                </value>
                <value>
                    <fullName>Business Academy</fullName>
                </value>
                <value>
                    <fullName>Cappex</fullName>
                </value>
                <value>
                    <fullName>CASPA</fullName>
                </value>
                <value>
                    <fullName>CBSS</fullName>
                </value>
                <value>
                    <fullName>CCCU</fullName>
                </value>
                <value>
                    <fullName>Chegg/Zinch</fullName>
                </value>
                <value>
                    <fullName>Christian Connector</fullName>
                </value>
                <value>
                    <fullName>CLT - Purchased</fullName>
                </value>
                <value>
                    <fullName>CLT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>Coach</fullName>
                </value>
                <value>
                    <fullName>College Board</fullName>
                </value>
                <value>
                    <fullName>College in the Schools</fullName>
                </value>
                <value>
                    <fullName>College Raptor</fullName>
                </value>
                <value>
                    <fullName>College Transcripts</fullName>
                </value>
                <value>
                    <fullName>Community College</fullName>
                </value>
                <value>
                    <fullName>Consortium</fullName>
                </value>
                <value>
                    <fullName>Converge</fullName>
                </value>
                <value>
                    <fullName>Cross Country</fullName>
                </value>
                <value>
                    <fullName>Cru</fullName>
                </value>
                <value>
                    <fullName>DACAC</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>ACT_Composite_Score__c</fullName>
        <description>ACT Composite Score</description>
        <inlineHelpText>ACT Composite Score</inlineHelpText>
        <label>ACT Composite Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_English_Score__c</fullName>
        <description>ACT English Score</description>
        <inlineHelpText>ACT English Score</inlineHelpText>
        <label>ACT English Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Mathematics_Score__c</fullName>
        <description>ACT Mathematics Score</description>
        <inlineHelpText>ACT Mathematics Score</inlineHelpText>
        <label>ACT Mathematics Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Reading_Score__c</fullName>
        <description>ACT Reading Score</description>
        <inlineHelpText>ACT Reading Score</inlineHelpText>
        <label>ACT Reading Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Science_Score__c</fullName>
        <description>ACT Science Score</description>
        <inlineHelpText>ACT Science Score</inlineHelpText>
        <label>ACT Science Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Writing_Score__c</fullName>
        <description>ACT Writing Score</description>
        <inlineHelpText>ACT Writing Score</inlineHelpText>
        <label>ACT Writing Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <recordTypes>
        <fullName>ACT</fullName>
        <active>true</active>
        <description>Record type for an ACT test scores</description>
        <label>ACT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TDTMTestScoreHandler.cls
/**
 * Created by ejc84332 on 2019-02-07.
 */

@IsTest
private class Test_TDTMTestScoreHandler {
    @IsTest
    static void testBehavior() {

        Test.startTest();
        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Test_Score_Handler', 'Interaction__c', 'AfterInsert;AfterUpdate;', 1.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        Contact c_one = new Contact(FirstName='First', LastName='Last', Email='test@test.com');
        insert c_one;

        String act = '"ACT_Reading_Score__c:31\n' +
                'ACT_Mathematics_Score__c:32 \n' +
                'ACT_English_Score__c:30\n' +
                'ACT_Science_Score__c:32\n' +
                'ACT_Composite_Score__c:31\n' +
                'ACT_Test_Date__c:06/01/2015\n' +
                'ACT_Writing_Score__c:30\n' +
                'Lead_Date__c:43503\n' +
                'Stauts_Description__c:Official"';

        Interaction__c int_one = new Interaction__c(First_Name__c='First', Last_Name__c='Last', Email__c='test@test.com', Lead_Source__c='Email', Source_Detail__c='Email', ACT_Test_Results__c=act, Contact__c=c_one.Id, Interaction_Status__c='Imported');
        insert int_one;

        Test_Score__c[] ts = [SELECT Id, Contact__c, ACT_Composite_Score__c FROM Test_Score__c WHERE Contact__c = :c_one.Id];

        update int_one;


//        System.assert(ts.Contact__c==c_one.Id);
//        System.assert(ts.ACT_Composite_Score__c==31);

        System.debug('Found Created Test Score');
        System.debug(ts);

        update int_one;

    }
}