src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>ACT_Test_Results__c</fullName>
        <defaultValue>&quot;none&quot;</defaultValue>
        <description>Data from ACT. Should be loaded from the &quot;ACT Summary&quot; of the ACT Parser Excel document.</description>
        <label>ACT Test Results</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_ACT_Test_Received__c</fullName>
        <description>The date Bethel received the ACT test score.</description>
        <label>Date ACT Test Received</label>
        <type>Date</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Score__c.object
<CustomObject>
    <description>This object is used to store official test score results.</description>
    <fields>
        <fullName>ACT_Composite_Score__c</fullName>
        <description>ACT Composite Score</description>
        <inlineHelpText>ACT Composite Score</inlineHelpText>
        <label>ACT Composite Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_English_Score__c</fullName>
        <description>ACT English Score</description>
        <inlineHelpText>ACT English Score</inlineHelpText>
        <label>ACT English Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Mathematics_Score__c</fullName>
        <description>ACT Mathematics Score</description>
        <inlineHelpText>ACT Mathematics Score</inlineHelpText>
        <label>ACT Mathematics Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Reading_Score__c</fullName>
        <description>ACT Reading Score</description>
        <inlineHelpText>ACT Reading Score</inlineHelpText>
        <label>ACT Reading Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Science_Score__c</fullName>
        <description>ACT Science Score</description>
        <inlineHelpText>ACT Science Score</inlineHelpText>
        <label>ACT Science Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACT_Writing_Score__c</fullName>
        <description>ACT Writing Score</description>
        <inlineHelpText>ACT Writing Score</inlineHelpText>
        <label>ACT Writing Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The person for which this test score belongs</description>
        <inlineHelpText>The person for which this test score belongs</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Test Scores</relationshipLabel>
        <relationshipName>Test_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Test_Received__c</fullName>
        <label>Date Test Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_to_Applicant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display to Applicant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Waived</fullName>
                </value>
                <value>
                    <fullName>Conditional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Description__c</fullName>
        <label>Status Description</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Official</fullName>
                </value>
                <value>
                    <fullName>Official, not final</fullName>
                </value>
                <value>
                    <fullName>Unofficial, received by email</fullName>
                </value>
                <value>
                    <fullName>Unofficial, open envelope</fullName>
                </value>
                <value>
                    <fullName>Unofficial, score on transcript</fullName>
                </value>
                <value>
                    <fullName>Unofficial, see notes</fullName>
                </value>
                <value>
                    <fullName>Not Yet Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Date__c</fullName>
        <description>The date the test was taken</description>
        <inlineHelpText>The date the test was taken</inlineHelpText>
        <label>Test Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Test_Type__c</fullName>
        <description>The Test type name. This should match the record type.</description>
        <inlineHelpText>The test type</inlineHelpText>
        <label>Test Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Test_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Test Score</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scores</pluralLabel>
    <recordTypes>
        <fullName>ACT</fullName>
        <active>true</active>
        <description>Record type for an ACT test scores</description>
        <label>ACT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Test_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>GRE</fullName>
    </customValue>
    <customValue>
        <fullName>MAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>TOEFL</fullName>
    </customValue>
    <customValue>
        <fullName>PSAT</fullName>
    </customValue>
    <customValue>
        <fullName>CLT</fullName>
    </customValue>
    <customValue>
        <fullName>IELTS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>PTE</fullName>
    </customValue>
    <customValue>
        <fullName>Accuplacer</fullName>
    </customValue>
    <customValue>
        <fullName>ACT or SAT official score</fullName>
    </customValue>
    <customValue>
        <fullName>GMAT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT2</fullName>
    </customValue>
    <customValue>
        <fullName>AP</fullName>
    </customValue>
    <customValue>
        <fullName>LSAT</fullName>
    </customValue>
    <customValue>
        <fullName>MAT or GRE</fullName>
    </customValue>
    <customValue>
        <fullName>PreACT</fullName>
    </customValue>
    <description>This is the list of test types which is used when recording test scores</description>
    <masterLabel>Test Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TDTM_Test_Score_Handler.cls
global class TDTM_Test_Score_Handler extends TDTMVirtualTriggerHandler {

    private Test_Score__c[] createTestScores(List<SObject> newList) {
        Id act_record_type = Schema.SObjectType.Test_Score__c.getRecordTypeInfosByName().get('ACT').getRecordTypeId();

        Id[] contact_ids = new List<Id>();
        for (SObject o : newList) {
            Interaction__c interaction = (Interaction__c) o;
            contact_ids.add(interaction.Contact__c);
        }

        Test_Score__c[] existing_scores = [SELECT Id, Name, ACT_Composite_Score__c, Test_Date__c, Contact__c FROM Test_Score__c WHERE Test_Type__c='ACT' AND Contact__c IN :contact_ids];

        List<Test_Score__c> new_test_scores = new List<Test_Score__c>();

        for (SObject o : newList) {
            Interaction__c interaction = (Interaction__c) o;

            if (interaction.Contact__c != null && interaction.ACT_Test_Results__c != null && interaction.ACT_Test_Results__c != 'none') {

                Map<String, String> act_scores = new Map<String, String>();
                for (String score : interaction.ACT_Test_Results__c.split('\n')) {
                    List<String> split_score = score.split(':');
                    // Excel sometimes send quotes and white space, so get rid of those.
                    act_scores.put(split_score[0].replace('"', '').trim(), split_score[1].replace('"', '').trim());
                }

                // probably could do this more efficiently
                Boolean test_score_exists = false;
                for(Test_Score__c ts : existing_scores){
                    Integer comp = Integer.valueOf(act_scores.get('ACT_Composite_Score__c'));
                    Date test_date = Date.parse(act_scores.get('ACT_Test_Date__c'));
                    if(ts.Contact__c==interaction.Contact__c && ts.ACT_Composite_Score__c==comp && ts.Test_Date__c == test_date){
                        test_score_exists = true;
                    }
                }

                System.debug('DOES TEST SCORE EXIST');
                System.debug(test_score_exists);
                System.debug('CONTACT ID');
                System.debug(interaction.Contact__c);
                if (!test_score_exists && act_scores.get('ACT_Composite_Score__c') != null) {
                    new_test_scores.add(new Test_Score__c(
                            RecordTypeId = act_record_type,
                            Contact__c = interaction.Contact__c,
                            Test_Type__c = 'ACT',
                            Document_Status__c = 'Received',
                            Status_Description__c = 'Official',
                            Display_to_Applicant__c = True,
                            Date_Test_Received__c = interaction.Date_ACT_Test_Received__c,
                            Test_Date__c = Date.parse(act_scores.get('ACT_Test_Date__c')),
                            ACT_Composite_Score__c = Integer.valueOf(act_scores.get('ACT_Composite_Score__c')),
                            ACT_English_Score__c = Integer.valueOf(act_scores.get('ACT_English_Score__c')),
                            ACT_Mathematics_Score__c = Integer.valueOf(act_scores.get('ACT_Mathematics_Score__c')),
                            ACT_Reading_Score__c = Integer.valueOf(act_scores.get('ACT_Reading_Score__c')),
                            ACT_Science_Score__c = Integer.valueOf(act_scores.get('ACT_Science_Score__c')),
                            ACT_Writing_Score__c = act_scores.get('ACT_Writing_Score__c') != '' ? Integer.valueOf(act_scores.get('ACT_Writing_Score__c')) : null
                    ));
                }
            }
        }

        return new_test_scores;
    }

    global override void onAfterInsert(List<SObject> newList, Map<Id, SObject> newMap, hed.TDTM_Runnable.DmlWrapper wrapper) {
        // grab the objects so we can do updates. Only grab the ones that don't have a source number. It should be all new sources
        // unless a source number was manually entered to override the default.
        System.debug('starting onAfterInsert TDTM_Test_Score_Handler');

        Test_Score__c[] new_scores = createTestScores(newList);

        if(new_scores.size() > 0){
            insert new_scores;
        }
    }

    global override void onAfterUpdate(List<SObject> newList, List<SObject> oldList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap, hed.TDTM_Runnable.DmlWrapper wrapper) {

        System.debug('starting onAfterUpdate TDTM_Test_Score_Handler');
        Test_Score__c[] new_scores = createTestScores(newList);

        if(new_scores.size() > 0){
            insert new_scores;
        }

    }

}