src/objects/Interaction__c.object
<CustomObject>
    <description>Interaction Log and Staging Object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Source__c</fullName>
        <description>The method by which the data is being added as an Interaction. Set to &quot;Manual Entry&quot; for hand entry, otherwise it represents the integration source (Webform, Purchase List, etc.) Also used in the Skip Mapping functionality on Interaction Mappings.</description>
        <label>Interaction Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Manual Entry</fullName>
                    <default>true</default>
                    <label>Manual Entry</label>
                </value>
                <value>
                    <fullName>Purchase List</fullName>
                </value>
                <value>
                    <fullName>Student Information System</fullName>
                </value>
                <value>
                    <fullName>Webform</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Register</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Family Member Create</fullName>
                </value>
                <value>
                    <fullName>Account Register</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interaction_Status__c</fullName>
        <description>When set to &quot;New,&quot; the Interaction Processor runs, then updates the Status based on the result to &quot;Imported&quot; or &quot;Audit Needed.&quot;</description>
        <inlineHelpText>Set the Status to &quot;New&quot; and save to kick off the Interaction process.</inlineHelpText>
        <label>Interaction Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Audit Required</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <description>Checked if the Source Number on this Interaction matches the value in the Primary Source Number field on its Opportunity.</description>
        <formula>if( 
Source_Number__c = Opportunity__r.Primary_Source_Number__c,
TRUE, 
FALSE 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Primary Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>The way in which the Lead or Contact&apos;s information was first received. Value &quot;Office Visit&quot; is required by the Interactions package tests.</description>
        <inlineHelpText>Indicate the initial source of this data.</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Application Change</fullName>
                </value>
                <value>
                    <fullName>Application Create</fullName>
                </value>
                <value>
                    <fullName>Application Submit</fullName>
                </value>
                <value>
                    <fullName>Camps</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Conferences &amp; Fairs</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event &amp; Visits</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>List &amp; Vendor</fullName>
                </value>
                <value>
                    <fullName>Office Visit</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Registrar</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Transcripts</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity created or updated by this Interaction, set by the Interaction Processor.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Detail__c</fullName>
        <description>Sub-field of Source Type.</description>
        <label>Source Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Lead_Source__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ACT - Purchased</fullName>
                </value>
                <value>
                    <fullName>ACT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>ActSix</fullName>
                </value>
                <value>
                    <fullName>Admitted Student Overnight</fullName>
                </value>
                <value>
                    <fullName>All State Music</fullName>
                </value>
                <value>
                    <fullName>Alumni</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Boys Basketball</fullName>
                </value>
                <value>
                    <fullName>Boys Soccer</fullName>
                </value>
                <value>
                    <fullName>Business Academy</fullName>
                </value>
                <value>
                    <fullName>Cappex</fullName>
                </value>
                <value>
                    <fullName>CASPA</fullName>
                </value>
                <value>
                    <fullName>CBSS</fullName>
                </value>
                <value>
                    <fullName>CCCU</fullName>
                </value>
                <value>
                    <fullName>Chegg/Zinch</fullName>
                </value>
                <value>
                    <fullName>Christian Connector</fullName>
                </value>
                <value>
                    <fullName>CLT - Purchased</fullName>
                </value>
                <value>
                    <fullName>CLT - Self submitted</fullName>
                </value>
                <value>
                    <fullName>Coach</fullName>
                </value>
                <value>
                    <fullName>College Board</fullName>
                </value>
                <value>
                    <fullName>College in the Schools</fullName>
                </value>
                <value>
                    <fullName>College Raptor</fullName>
                </value>
                <value>
                    <fullName>College Transcripts</fullName>
                </value>
                <value>
                    <fullName>Community College</fullName>
                </value>
                <value>
                    <fullName>Consortium</fullName>
                </value>
                <value>
                    <fullName>Converge</fullName>
                </value>
                <value>
                    <fullName>Cross Country</fullName>
                </value>
                <value>
                    <fullName>Cru</fullName>
                </value>
                <value>
                    <fullName>DACAC</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Number__c</fullName>
        <description>Updated by an Apex class Source_PrimaryHandler. Used to calculate primary source.</description>
        <label>Source Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Source_Number__c</fullName>
        <label>Primary Source Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Test_TDTM_Soucre_Primary_Handler.cls
/**
 * Created by ejc84332 on 2019-02-05.
 */

@IsTest
private class Test_TDTM_Soucre_Primary_Handler {

    @IsTest
    static void TestPrimarySourceHandler(){

        Test.startTest();

        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Soucre_Primary_Handler', 'Interaction__c', 'BeforeUpdate;AfterInsert;AfterUpdate;AfterDelete', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        Contact c_one = new Contact(FirstName='First', LastName='Last', Email='test@test.com');
        insert c_one;

        Contact c_two = new Contact(FirstName='First2', LastName='Last2', Email='test2@test.com');
        insert c_two;

        Opportunity opp = new Opportunity(Name='First Last Opp', AccountId=c_one.AccountId, Contact__c=c_one.Id, StageName='Inquired', CloseDate=Date.today(), Stage_Detail__c = 'Inquired');
        Opportunity opp_two = new Opportunity(Name='First2 Last2 Opp', AccountId=c_two.AccountId, Contact__c=c_two.Id, StageName='Inquired', CloseDate=Date.today(),  Stage_Detail__c = 'Inquired');
        insert opp;
        insert opp_two;

        Interaction__c int_one = new Interaction__c(First_Name__c='First', Last_Name__c='Last', Email__c='test@test.com', Lead_Source__c='Email', Source_Detail__c='Email', Opportunity__c=opp.Id);
        Interaction__c int_two = new Interaction__c(First_Name__c='First', Last_Name__c='Last', Email__c='test@test.com', Lead_Source__c='Email', Source_Detail__c='Email');
        Interaction__c int_three = new Interaction__c(First_Name__c='First', Last_Name__c='Last', Email__c='test@test.com');

        Interaction__c int_four = new Interaction__c(First_Name__c='First2', Last_Name__c='Last2', Email__c='test2@test.com', Lead_Source__c='Email', Source_Detail__c='Email');
        Interaction__c int_five = new Interaction__c(First_Name__c='First2', Last_Name__c='Last2', Email__c='test2@test.com');

        List<Interaction__c> ints = new List<Interaction__c>();
        ints.add(int_one);
        ints.add(int_two);
        ints.add(int_three);
        ints.add(int_four);
        ints.add(int_five);

        insert ints;

//        insert int_one;
//        insert int_two;
//        insert int_three;


        // have to add this after it creates for some reason
        int_one.Opportunity__c=opp.Id;
        int_two.Opportunity__c=opp.Id;
        int_three.Opportunity__c=opp.Id;
        int_four.Opportunity__c=opp_two.Id;
        int_five.Opportunity__c=opp_two.Id;
//        update int_one;
//        update int_two;
//        update int_three;
        update ints;

        int_one = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_one.Id];
        int_two = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_two.Id];
        int_three = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_three.Id];
        int_four = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_four.Id];
        int_five = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_five.Id];
        opp = [SELECT Id, Primary_Source_Number__c from Opportunity where Id = :opp.Id];
        opp_two = [SELECT Id, Primary_Source_Number__c from Opportunity where Id = :opp_two.Id];

        // int_one should be primary on the Opp
        System.assert(int_one.Source_Number__c == Integer.valueof(int_one.Name.split('-')[1]));
        System.assert(int_one.Source_Number__c == opp.Primary_Source_Number__c);
        System.assert(int_one.Is_Primary__c == true);

        // manually override int_two's number
        int_two.Source_Number__c=10;
        int_two.Opportunity__c=opp.Id;
        update int_two;

        int_one = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_one.Id];
        int_two = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_two.Id];
        int_three = [SELECT Id, Name, Contact__c, Opportunity__c, Interaction_Source__c, Interaction_Status__c, Source_Number__c, Is_Primary__c FROM Interaction__c WHERE Id = :int_three.Id];
        opp = [SELECT Id, Primary_Source_Number__c from Opportunity where Id = :opp.Id];


        System.assert(opp.Primary_Source_Number__c==10);
        System.assert(int_two.Is_Primary__c == true);
        System.assert(int_one.Is_Primary__c == false);
        int_two.Opportunity__c=opp.Id;
        delete int_two;

        opp = [SELECT Id, Primary_Source_Number__c from Opportunity where Id = :opp.Id];
        System.debug(opp);
        System.assert(opp.Primary_Source_Number__c!=10);

        System.assert(int_one.Source_Number__c == Integer.valueof(int_one.Name.split('-')[1]));


        // make sure it goes back to the name after its nulled out.
        Decimal old_number = int_one.Source_Number__c;
        int_one.Source_Number__c = null;
        update int_one;
        int_one = [SELECT Id, Name, Source_Number__c FROM Interaction__c WHERE Id = :int_one.Id];
        System.assert(int_one.Source_Number__c == old_number);


        Test.stopTest();


    }
}