src/objects/Mogli_SMS__SMS__c.object
<CustomObject>
    <fields>
        <fullName>Mogli_SMS__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SMS</relationshipLabel>
        <relationshipName>SMS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incoming</fullName>
                </value>
                <value>
                    <fullName>Outgoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Message__c</fullName>
        <label>Message</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mogli_SMS__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sending</fullName>
                </value>
                <value>
                    <fullName>Sent Successfully</fullName>
                </value>
                <value>
                    <fullName>Received Successfully</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS{YY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncomingSMSFlowLauncher_Test.cls
@IsTest
private class IncomingSMSFlowLauncher_Test {

    @IsTest
    static void testBehavior() {
        Contact contact = new Contact(
            LastName = 'Test Contact Magic Number',
            MobilePhone = '(500) 555-0006'
        );
        insert contact;

        Test.startTest();
        IncomingSMSFlowLauncher.reLaunch();
        Mogli_SMS__SMS__c incomingSMS = new Mogli_SMS__SMS__c(
            Mogli_SMS__Contact__c = contact.Id,
            Mogli_SMS__Phone_Number__c = '+15005550006',
            Mogli_SMS__Direction__c = 'Incoming',
            Mogli_SMS__Status__c = 'Received Successfully',
            Mogli_SMS__Message__c = 'Test Message!'
        );
        insert incomingSMS;
        Test.stopTest();

        System.assertNotEquals(0, [SELECT COUNT() FROM FlowInterview]);
    }

}