src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox goes on the &quot;close&quot; screen, and is used to indicate if the file is being Rejected or normally closed.</description>
        <label>Reject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdrawal_Reason__c</fullName>
        <description>Reason for not coming to Bethel; Data goes into Banner</description>
        <inlineHelpText>Reason for not coming to Bethel</inlineHelpText>
        <label>Withdrawal Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AN - Academic Fit</fullName>
                </value>
                <value>
                    <fullName>RA - Readmit</fullName>
                </value>
                <value>
                    <fullName>AT - Athletics</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Contact Info</fullName>
                </value>
                <value>
                    <fullName>BV - Bad Experience</fullName>
                </value>
                <value>
                    <fullName>CO - Community Fit</fullName>
                </value>
                <value>
                    <fullName>DR - Do Not Recruit</fullName>
                </value>
                <value>
                    <fullName>FA - Financial Aid</fullName>
                </value>
                <value>
                    <fullName>NA - App Not Complete</fullName>
                </value>
                <value>
                    <fullName>NR - No Response</fullName>
                </value>
                <value>
                    <fullName>PR - Personal</fullName>
                </value>
                <value>
                    <fullName>QD - Not Qualified</fullName>
                </value>
                <value>
                    <fullName>SC - STAR contact:not interested</fullName>
                </value>
                <value>
                    <fullName>ST - Switching Term/Prog</fullName>
                </value>
                <value>
                    <fullName>TC - Too close to home</fullName>
                </value>
                <value>
                    <fullName>TF - Too far from home</fullName>
                </value>
                <value>
                    <fullName>TU - High Tuition</fullName>
                </value>
                <value>
                    <fullName>UN - Unknown</fullName>
                </value>
                <value>
                    <fullName>WA - Wrong School/Catalog</fullName>
                </value>
                <value>
                    <fullName>WB - Wrong Bethel</fullName>
                </value>
                <value>
                    <fullName>WL - Waitlist/Not Selected</fullName>
                </value>
                <value>
                    <fullName>TL - Will transfer in later</fullName>
                </value>
                <value>
                    <fullName>SF - Switching to Future Term</fullName>
                </value>
                <value>
                    <fullName>BF - Better fit elsewhere</fullName>
                </value>
                <value>
                    <fullName>CH - Change of Plans</fullName>
                </value>
                <value>
                    <fullName>DF - Deferred to new term</fullName>
                </value>
                <value>
                    <fullName>WY - Wrong grad year</fullName>
                </value>
                <value>
                    <fullName>AC - Acad Dept Contact:not interest</fullName>
                </value>
                <value>
                    <fullName>AR - Admit record created</fullName>
                </value>
                <value>
                    <fullName>BA - Bad Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Test_TDTM_Calculate_Closed_Stage_Detail.cls
/**
 * Created by ejc84332 on 2019-03-30.
 */

@IsTest
private class Test_TDTM_Calculate_Closed_Stage_Detail {
    private static void move_opportunity_stage(Opportunity opp, String stages, Boolean reject){


        String final_name = opp.StageName;
        String final_detail = opp.Stage_Detail__c;

        // set the Opportunity stage, and keep track of the last stage it was at
        if(stages != null) {
            for (String stage : stages.split('-->')) {
                String[] name_and_detail = stage.split(':');
                System.debug('Updating to:');
                System.debug(name_and_detail);
                final_name = name_and_detail[0];
                final_detail = name_and_detail[1];
                opp.StageName = final_name;
                opp.Stage_Detail__c = final_detail;
                update opp;
            }
        }

        // now move to file closed and do an assertion.
        opp.StageName = 'File Closed';
        opp.Withdrawal_Reason__c = 'BV - Bad Experience';
        opp.Reject__c = reject;
        System.debug('Updating to:');
        System.debug(opp.StageName);
        update opp;
        System.assert(opp.StageName == 'File Closed');
        // todo expand this one
        opp = [SELECT Id, StageName, Stage_Detail__c from Opportunity where Id= :opp.Id];
        System.assert(opp.Stage_Detail__c.contains('File Closed'));
        System.debug(opp.StageName);
        System.debug(opp.Stage_Detail__c);
        System.assert(opp.Stage_Detail__c.contains(final_name) || opp.Stage_Detail__c.contains(final_detail));

    }

    @IsTest
    static void test_closed_stage_detail() {


        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Calculate_File_Closed_Stage_Detail', 'Opportunity', 'BeforeUpdate', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);


        Contact c_one = new Contact(FirstName='First', LastName='Last', Email='test@test.com');
        insert c_one;

        Opportunity opp = new Opportunity(Name='First Last Opp', CloseDate=Date.today(), AccountId=c_one.AccountId, Contact__c=c_one.Id, StageName='Inquired', Stage_Detail__c='Inquired');
        insert opp;
        
        Test.startTest();

        // todo: not sure how to test this without a lot of queries, but this does cover all lines.
        move_opportunity_stage(opp, 'Applied:App Submitted', false);

        // trigger the reject error
        try{
            move_opportunity_stage(opp, 'Inquired:Inquired', true);
        }catch (Exception e){
            System.assert(e.getMessage().contains('bad value for restricted picklist field') ? true : false);
        }



    }

}