src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Applicant)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Detail__c</fullName>
        <description>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</description>
        <inlineHelpText>Stage can have a Stage Detail (Substage) to determine where the Opportunity is in the process.</inlineHelpText>
        <label>Stage Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>Stage_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <description>Student Type is a based on several values from the application to determine the type of student. BUILD by program, transfer by if they are transfering data, PSEO by the PSEO question on the application, New is default and New Student Previous PSEO will be done manually</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BUILD</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>New Student Previous PSEO</fullName>
                </value>
                <value>
                    <fullName>PSEO</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Stage_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied</fullName>
    </customValue>
    <customValue>
        <fullName>App Started</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Enrolled</fullName>
    </customValue>
    <customValue>
        <fullName>Inquired - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Applied - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Wait Listed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Accepted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Submitted - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Completed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Paid - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Waived - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Registered - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Lead - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected - App Started - File Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown - File Close</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect - File Closed</fullName>
    </customValue>
    <description>The stage detail or substage of the Opportunity</description>
    <masterLabel>Stage Details</masterLabel>
</GlobalValueSet>

src/classes/Test_TDTM_Opportunity_Assignments.cls
/**
 * Created by ejc84332 on 2019-03-30.
 */


@IsTest
private class Test_TDTM_Opportunity_Assignments {


    @IsTest
    static void test_opportunity_assignments() {


        // first retrieve default HEDA trigger handlers
        List<hed.TDTM_Global_API.TdtmToken> tokens = hed.TDTM_Global_API.getTdtmConfig();
        // Create our trigger handler using the constructor
        tokens.add(new hed.TDTM_Global_API.TdtmToken('TDTM_Opportunity_Assignments', 'Opportunity', 'AfterInsert;AfterUpdate', 2.00));
        // Pass trigger handler config to set method for this test run
        hed.TDTM_Global_API.setTdtmConfig(tokens);

        // All this does is call the Assignment Engine Class, which has its own tests. So just create an opp to get
        // the trigger to run and trust those tests for the rest.

        Contact c_one = new Contact(FirstName='First', LastName='Last', Email='test@test.com');
        insert c_one;

        Test.startTest();

        Opportunity opp = new Opportunity(Name='First Last Opp', CloseDate=Date.today(), AccountId=c_one.AccountId, Contact__c=c_one.Id, StageName='Inquired', Stage_Detail__c='Inquired');
        insert opp;

        opp.Student_Type__c = 'PSEO';
        update opp;

    }
}