src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>REF-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>External_Email__c</fullName>
        <label>External Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reference_First_Name__c</fullName>
        <description>Answer to the references first name question</description>
        <label>Reference First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Last_Name__c</fullName>
        <description>Answer to reference&apos;s last name question</description>
        <label>Reference Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Reference object</description>
        <label>Reference</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item this response is for.</description>
        <label>Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateReferenceController.cls
/**
 * Created by ejc84332 on 2019-07-31.
 */

public with sharing class UpdateReferenceController {

    @AuraEnabled
    public static String updateReferenceResponses(Id referenceId, String firstName, String lastName, String emailAddress, String relationshipToApplicant) {

//        Reference__c update_ref = new Reference__c(Id=referenceId, First_Name__c=)

        Requirement_Response__c[] requirement_responses = [Select Id, Requirement_Item__r.Name from Requirement_Response__c where Reference__c = :referenceId
                                                and Requirement_Item__r.Name like '%Reference'];

        // this SHOULD only be a list of one
        for (Requirement_Response__c response : requirement_responses){

            if(response.Requirement_Item__r.Name.endsWith('Reference')){
                response.Reference_First_Name__c = firstName;
                response.Reference_Last_Name__c = lastName;
                response.External_Email__c = emailAddress;

                // this is the only requirement response, so just update it.
                update response;
            }

        }

        return referenceId;
    }



}